### ISSUE TITLE
Add dockerfile that supports GPU training

### ISSUE THREAD

**Issue by nicolas-chaulet** [nicolas-chaulet/torch-points3d#131]
Add a dockerfile to the repo that generates a docker image that can be used for training tasks.

**Comment by CCInc** [comment]
I made a basic dockerfile which should help people get started and avoid versioning issues like I ran into. If you like it I can submit a pull request to add it to the repo. It required a few changes to the requirements.txt which I've included as well.

I had issues with getting the poetry setup to work as poetry would install pytorch for cuda 10.2, even though the nvcc version was for cuda 10.1 - if that can be resolved I can easily switch it back to poetry.

https://gist.github.com/CCInc/246cce51cc90f72e047db3a6c049566a

**Comment by nicolas-chaulet** [comment]
Hey @CCInc Thanks a lot for that looks great! Yes a PR would be most welcome,  feel free to add a new dockerfile to this folder:
https://github.com/nicolas-chaulet/torch-points3d/tree/master/docker
Maybe call it `Dockerfile.train`?
Also, I think it would be better to use the `pyproject.toml` to control what gets installed. If you run `pip install .` in a folder that contains a pyproject.toml it will resolve and install dependencies. Maintaining the requirements.txt manually is not ideal. Once the PR is merged I'll setup a github action to push fresh docker images to Docker hub.
Thanks again,
Nicolas

**Comment by CCInc** [comment]
@nicolas-chaulet Sure, sounds good! I'll try to get the pyproject.toml installation working.

On another note, did I read somewhere you had a slack page for this project? I have a few small questions if you have a chance. Thanks!

**Comment by nicolas-chaulet** [comment]
Yes we do! Just send me your email and I'll add you to it

**Comment by zetyquickly** [comment]
> Hey @CCInc Thanks a lot for that looks great! Yes a PR would be most welcome, feel free to add a new dockerfile to this folder:
> https://github.com/nicolas-chaulet/torch-points3d/tree/master/docker
> Maybe call it `Dockerfile.train`?
> Also, I think it would be better to use the `pyproject.toml` to control what gets installed. If you run `pip install .` in a folder that contains a pyproject.toml it will resolve and install dependencies. Maintaining the requirements.txt manually is not ideal. Once the PR is merged I'll setup a github action to push fresh docker images to Docker hub.
> Thanks again,
> Nicolas

Hello @nicolas-chaulet. I am wondering is the `Dockerfile.train` he best option to setup this repo for development? I mean in case I want to add some new functionalities

**Comment by nicolas-chaulet** [comment]
Yes! You would need to have a GPU, otherwise the Dockerfile is good too. There is actually an up to date image on dockerhub:
`principialabs/torch-points3d:latest`
