### ISSUE TITLE
how to test custom dataset （pointcloud） using kpconv model.

### ISSUE THREAD

**Issue by Yuwenger** [nicolas-chaulet/torch-points3d#181]
@nicolas-chaulet 
 sorry to bother you, I defined my own dataset and trained. but how can i test the result of model.(I mean a full pointcloud pointwist prediction, in eval.py or in viz folder the data is part of a single item(mostly a slice of pointcloud within  a defined radius)).

**Comment by tchaton** [comment]
Hey @Yuwenger, excellent question! We didn t implement a prediction mapping for slices to full pointcloud. We will have to do it, but it isn t our priority right now. If you wish, you could add the functionality and make a PR. We could try to help you if needed. But it is a bit tricky to do correctly depending on pointcloud size (if it doesn t fit in memory and you have sampling transform, using Knn to interpolate predictions).

**Comment by Yuwenger** [comment]
hey @tchaton ，thanks for your reply ,I will deep in the code and have a try by myself. And look forward to your release.

**Comment by tchaton** [comment]
Hey @Yuwenger, we hava a Slack where we discuss about the project with several researchers.
Do you wanna join ? If yes, I will need your email adress ;)

**Comment by Yuwenger** [comment]
Hey @tchaton ,I am glad to join it .  My email adress is: gu_yu_feng@sina.com

**Comment by Yuwenger** [comment]
Hey @tchaton  ,I am glad to join it . My email adress will send to your email or you can get it from my github homepage profile.

**Comment by tchaton** [comment]
@Yuwenger Did you manage to run KPConv on your custom dataset ?

**Comment by tchaton** [comment]
https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/PartSegmentationKPConv.ipynb
