### ISSUE TITLE
problem in compute_sparse_delta

### ISSUE THREAD

**Issue by humanpose1** [nicolas-chaulet/torch-points3d#215]
I think there is a problem [here](https://github.com/nicolas-chaulet/deeppointcloud-benchmarks/blob/2cd595d5c10cb26674755e4e462fb5f546c449a5/src/core/data_transform/sparse_transforms.py#L87). Indeed, we are computing the difference between raw_pos(which is xyz coordinate) and data.pos which is now voxel coordinate. Therefore, the operation is not homogeneous.

**Comment by nicolas-chaulet** [comment]
Good catch
