### ISSUE TITLE
Question about function: neighbour finder

### ISSUE THREAD

**Issue by Luan-Zhaoliang** [nicolas-chaulet/torch-points3d#253]
Hi, 
can I know what is the mean of function **neighbour finder**, especially in KPConv model.

**Comment by nicolas-chaulet** [comment]
Hi,
The neighbour finder function looks for neighbours of each point within a fixed radius, see 
https://github.com/nicolas-chaulet/torch-points-kernels/blob/17d4f8aa12a3e391bf5f66da228ccab235cee791/torch_points_kernels/torchpoints.py#L171
for more details. 
Hope this helps!

**Comment by tchaton** [comment]
@Luan-Zhaoliang, We defined it this way, as several strategy could be used to select neighbours.
KPConv is using grid_sampling with doubling grid_cell 
PointNet2 is using radius search (which performs better than knn).
RandLANet is using Random Sampling
etc..
