### ISSUE TITLE
Question about shared MLP

### ISSUE THREAD

**Issue by yangj257** [nicolas-chaulet/torch-points3d#262]
Hi，
@nicolas-chaulet  Shared MLP is a common layer in 3D point cloud processing network like pointnet, RandLANet. I found you used nn.Linear to implement shared MLP (MLP). But I think nn.Linear is fully connected layers, not shared MLP. Is there something wrong with me? please tell me some thing more detail  about shared MLP.
Thanks a lot for your great work！

**Comment by tchaton** [comment]
Hi @yangj257,

It is actually the same thing :) 
If you have a 2d tensor, you can use nn.Linear
If you have a 3d tensor, you can use nn.Conv1d with kernel size 1
If you have a 4d tensor, you can use nn.Conv2d with kernel size 1x1

It is just a nice way to make fully connected without having the trouble to reshape or squeeze.

Best regards,
Thomas Chaton.

**Comment by yangj257** [comment]
@tchaton Thanks a lot，I got it！
