### ISSUE TITLE
installation without cuda

### ISSUE THREAD

**Issue by gabrielwaibel** [nicolas-chaulet/torch-points3d#275]
Is it possible to install the package without cuda?

**Comment by nicolas-chaulet** [comment]
Yes totally, our CI pipeline runs without CUDA for example and most model have a working forward and backward pass. Simply run the following to install on your machine and if CUDA is not there it will download the appropriate versions
```
pip install torch-points3d
```

**Comment by gabrielwaibel** [comment]
Thanks for the fast answer!
