### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by cinjon** [nicolas-chaulet/torch-points3d#276]
I am getting the following error when trying to install with pip:

```
ERROR: Could not find a version that satisfies the requirement torch==1.3.1 (from torch_points3d) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.5.0)

ERROR: No matching distribution found for torch==1.3.1 (from torch_points3d)
```

This is when installing on a GPU and into a virtualenv that already has torch=1.4.0. Is this expected?

UPDATE:
Just tried using poetry install and this happens there as well.

**Comment by cinjon** [comment]
I just tried again from a fresh conda env and got this error when trying to install it via pip:

(torch3d) [cr2668@gpu-27 ~]$ pip install torch_points3d
Collecting torch_points3d
  Downloading torch_points3d-1.0.0-py3-none-any.whl (228 kB)
     |████████████████████████████████| 228 kB 9.5 MB/s 
Collecting hydra-core<0.12.0,>=0.11.2
  Downloading hydra_core-0.11.3-py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 653 kB/s 
Collecting wandb<0.9.0,>=0.8.18
  Downloading wandb-0.8.36-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 25.9 MB/s 
Collecting tqdm<5.0,>=4.40
  Downloading tqdm-4.46.0-py2.py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 3.1 MB/s 
Collecting torch==1.3.1
  Downloading torch-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (734.6 MB)
     |████████████████████████████████| 734.6 MB 46 kB/s 
Collecting numpy<2.0.0,>=1.18.2
  Downloading numpy-1.18.4-cp36-cp36m-manylinux1_x86_64.whl (20.2 MB)
     |████████████████████████████████| 20.2 MB 53.3 MB/s 
Collecting torch-points-kernels<0.7.0,>=0.6.0
  Downloading torch-points-kernels-0.6.3.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/cr2668/.conda/envs/torch3d/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/state/partition1/job-9876040/pip-install-i_ljeu1h/torch-points-kernels/setup.py'"'"'; __file__='"'"'/state/partition1/job-9876040/pip-install-i_ljeu1h/torch-points-kernels/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /state/partition1/job-9876040/pip-install-i_ljeu1h/torch-points-kernels/pip-egg-info
         cwd: /state/partition1/job-9876040/pip-install-i_ljeu1h/torch-points-kernels/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/state/partition1/job-9876040/pip-install-i_ljeu1h/torch-points-kernels/setup.py", line 4, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/state/partition1/job-9876040/pip-install-i_ljeu1h/torch-points-kernels/setup.py", line 12, in <module>
        raise ModuleNotFoundError("Please install pytorch >= 1.1 before proceeding.")
    ModuleNotFoundError: Please install pytorch >= 1.1 before proceeding.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by nicolas-chaulet** [comment]
Hi, not sure what's going on here but we just published a new release that should fix your problem (it works with pytorch 1.3.1 and greater)

**Comment by nicolas-chaulet** [comment]
Hi @cinjon I am assuming this is working now, let me know if you have more troubles!

**Comment by cinjon** [comment]
I haven't actually tried it again. We needed ShapeNet55 as parts with labels, so we reconstructed that ourselves. Thanks for being on top of the issues though, much appreciated.
