### ISSUE TITLE
How to use KPConv as a part of my architecture?

### ISSUE THREAD

**Issue by gmcalo** [nicolas-chaulet/torch-points3d#279]
Could you show me a simple example of how to define KPFCNN  as  a model(net)? I want to bulid a architecture which use KPConv as a part of it.

**Comment by tchaton** [comment]
Dear @gmcalo, Thanks for giving a try to the framework.

I guess the simplest approach will be to use the API.

Please, find there a example of how to use KPConv through the API
https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/PartSegmentationKPConv.ipynb

However, if you wanted to change the model, you could have a look at the encoder / unet KPConv .yaml files there:
https://github.com/nicolas-chaulet/torch-points3d/tree/master/torch_points3d/applications/conf/kpconv

Here is an example on how to configure the point cloud for KPConv (needs multi-scale grid_sampling): https://github.com/nicolas-chaulet/torch-points3d/blob/master/conf/data/segmentation/shapenet.yaml
