### ISSUE TITLE
pointnet++ run on s3dis_fuse

### ISSUE THREAD

**Issue by guochengqian** [nicolas-chaulet/torch-points3d#325]
hi @nicolas-chaulet , 

why  `python train.py task=segmentation model_type=kpconv model_name=KPConvPaper dataset=s3disfused training=s3dis_benchmark/kpconv.yaml` works fine, 
but
`python train.py task=segmentation model_type=pointnet2 model_name=pointnet2_charlesssg dataset=s3disfused training=s3dis_benchmark/pointnet2.yaml`
will encounter problem of:
```
  File "/home/qiang/Documents/codefiles/3D/segmentation/mypoints3d/torch_points3d/datasets/batch.py", line 48, in from_data_list
    batch[key] = torch.stack(batch[key])
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 14072 and 14467 in dimension 1 at /opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/TH/generic/THTensor.cpp:612
```

any advice on how to solve this? 

Seems the dataloader also has a correlation with models (which should not)

**Comment by tchaton** [comment]
Hey @guochengqian,

The framework implements 4 different CONV_TYPE . 
DENSE, PARTIAL_DENSE, MESSAGE_PASSING and SPARSE.

The model.conv_type is used to select the collate function within dataloader to make a batch.
https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/datasets/base_dataset.py#L132

KPConv is "PARTIAL_DENSE" type. It means pointcloud instances of different size can be batched together on the node dimension.
PointNet ++ is "DENSE" type. It means pointcloud instances need to have the same number of points.

Within s3disfused, there is no FixedPoints sampling at the end to force the same number of points.
Therefore, when trying to collate samples on dimension 0, it tells you: "You have 2 pointcloud with different number of points 14072 and 14467 in dimension 1"

Add FixedPoint transform within the config and it will work :)

Best regards,
T.C

**Comment by guochengqian** [comment]
Amazing! Thanks for your explanation.
