### ISSUE TITLE
S3DIS data processing

### ISSUE THREAD

**Issue by guochengqian** [nicolas-chaulet/torch-points3d#326]
Hello torch-points3d team, 

in https://github.com/nicolas-chaulet/torch-points3d/blob/ea0a8629a269ea593e02b75bd6b6b12ca31ee5c9/conf/data/segmentation/s3disfused-fixed.yaml#L11, you pre sample the S3DIS in training, validation, and testing. 
That means you only use the subsampled version of S3DISFuse instead of the original ones. Then the sphere sample is conducted on the subsampled s3dis. 

Why this subsample preprocessing is necessary?

**Comment by tchaton** [comment]
Hey, 

In KPConv, points are voxelized on a grid.
We use a pre_compute to optimize dataloading, so points are already pre-voxelized.
However, the raw pointcloud is also saved within the dataset, and we can do full resolution evaluation by passing full_res=True to the metric tracker.
The full res is done by making knn interpolation from to low res to full res.
We kept KPConv convention, to use knn 1.

Hope it helps !

Best,
T.C

**Comment by guochengqian** [comment]
hi @tchaton, 
I will take a look into it. Thanks for your explanation.
