### ISSUE TITLE
Google Colab Stuck on ,Building wheels for collected packages 

### ISSUE THREAD

**Issue by shangguan91** [nicolas-chaulet/torch-points3d#331]
!pip install torch-points3d stuck on Building wheels for collected packages torch-points-kernels.

tried install torch points kernel saparate, stuck as well

**Comment by shangguan91** [comment]
`Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t8ohpa6_/torch-points-kernels/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t8ohpa6_/torch-points-kernels/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cs87ba9x/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.`

**Comment by nicolas-chaulet** [comment]
Not sure what is happening, here is an example of installation, I just ran it and it works fine. Could you ellaborate? Show the full logs?
https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/PartSegmentationKPConv.ipynb

**Comment by shangguan91** [comment]
this is my error，ERROR: Failed building wheel for torch-points-kernels

I think if you open the google colab run `!pip install pyvista
!pip install --upgrade jsonschema
!pip install torch-points3d
!apt-get install -qq xvfb libgl1-mesa-glx`

it will happen

**Comment by nicolas-chaulet** [comment]
No idea what is happening with your colab env. I just ran it today again and here is what I get:
![image](https://user-images.githubusercontent.com/3178237/86950413-10b00a80-c148-11ea-8cd7-aeb6f4c2d009.png)
Basically it works

**Comment by shangguan91** [comment]
![image](https://user-images.githubusercontent.com/64595972/86952988-157abb80-c154-11ea-9ef8-656fc7be260e.png)
Sorry, i should consider to show this hours ago. bascially it stuck at here about 30minutes, then come out with a error
 above.

**Comment by shangguan91** [comment]
it works, maybe my internet is too slow, which explain the stuck.
