### ISSUE TITLE
Example on how to change batch format

### ISSUE THREAD

**Issue by pvnieo** [nicolas-chaulet/torch-points3d#332]
Hi!

Thank you for the awesome library.

I was reading the medium blog about the library (https://towardsdatascience.com/torch-points3d-a-unifying-framework-for-deep-learning-on-point-clouds-94115c0be4fb), and it says that `The good news is that we support both data formats, and our data loader can easily switch from one to the other.`. However, I can't find in the documentation how to do that.

Can you please provide a small example on how to do that?

**Comment by nicolas-chaulet** [comment]
Hey, could you please ellaborate on your goal? What are you trying to achieve?

**Comment by pvnieo** [comment]
Hi @nicolas-chaulet Thank you for your response!

Actually, If my understanding is right, torch-points3d can grants the possibility of transforming a dataloader that returns packed batches to a dataloader that returns dense batches. 

Is my understanding correct? Actually, I'm interested in this option, and I know that pytorch-3d (https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/batching.md) can do this, but it would be cool if it's integrated in torch-points3d!

**Comment by nicolas-chaulet** [comment]
Ok, yes you can do that. The `BaseDataset` is in charge of creating the data loader via this method:
https://github.com/nicolas-chaulet/torch-points3d/blob/8e92c15ecc28685713f7c1c930f67f93f513f027/torch_points3d/datasets/base_dataset.py#L162

At that point, it looks at the `conv_type` property of the model and decides how to collate the batch. Does that help?

**Comment by pvnieo** [comment]
Yes, this help actually, thank you!
closing the issue.

**Comment by pvnieo** [comment]
hi @nicolas-chaulet 
let's say that I have a packed batch of data `batch` that has many keys (e.g pos, normals, rgb, etc) and I want to access it's `i`th element, so that I have a `Data` instance containing all the keys.

Is there

**Comment by nicolas-chaulet** [comment]
You would use the `batch` attribute which contains the element index for each point. For example:
```
pos_1 = batch.pos[batch.batch == 1]
```

**Comment by pvnieo** [comment]
I see. Thank you for your response.
