### ISSUE TITLE
implement model for classfication task in your repo?

### ISSUE THREAD

**Issue by shangguan91** [nicolas-chaulet/torch-points3d#333]
Dear nicolas,

i try to implement every possible method mentioned in your repo for my own data Data(pos=[2518, 3], y=[1) for classfication problem.
So, here is where i start?[]( https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/ObjectClassificationRSConv.ipynb)

In order to achieve this, what is best shortcut?
1. reshape data as pretrained model.
2. refactoring the model and training loop?

**Comment by nicolas-chaulet** [comment]
I am not sure I understand your data but I think the simplest is to create a new dataset, following that example:
https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/datasets/classification/modelnet.py
and also create the associated configuration file:
https://github.com/nicolas-chaulet/torch-points3d/blob/master/conf/data/classification/modelnet.yaml

Some detailed reading here:
https://torch-points3d.readthedocs.io/en/latest/src/tutorials.html#create-a-new-dataset

**Comment by shangguan91** [comment]
Thank you, it is acutally good example, however, i still have problem of write the inmemorydata script.
![image](https://user-images.githubusercontent.com/64595972/87022343-a5614980-c1d6-11ea-862c-eb6ef8515e85.png)

as i have already loaded data, if i could pass the download process? 

so bascially i have to diy again to make the form of dataset exactly like the modelnet.py example. when it comes to the implementation of diffrent models for classfication problem, you will build model again.

**Comment by nicolas-chaulet** [comment]
You can just keep the download method empty. Or not implement it. It will skip that step automatcially.
