### ISSUE TITLE
Installation error when building wheel for torch-scatter

### ISSUE THREAD

**Issue by LJL36** [nicolas-chaulet/torch-points3d#335]
Hi!
Thank you for your awesome job!
I have encountered the following error when i build wheel for torch-scatter during installation

>  /tmp/pip-install-_9adtem5/torch-scatter/csrc/scatter.cpp:117:13: error: ‘class at::Tensor’ has no member named ‘true_divide__’
>  &emsp;grad_in.true_divide_(count);

Other components have been built successfully.

**Environment information:**
Ubuntu 18.04.4 LTS
Python 3.7.6
Pytorch 1.4.0
CUDA 10.0

**Comment by nicolas-chaulet** [comment]
Hummm interesting, I ahve never had that problem. This is probably something for the torch scatter project itself:
https://github.com/rusty1s/pytorch_scatter
If building the wheels fail you can try to install the binaries directly:
https://github.com/rusty1s/pytorch_scatter#pytorch-140

**Comment by LJL36** [comment]
Thank you very much! I have succeeded.
