### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' when running dashboard.ipynb

### ISSUE THREAD

**Issue by niallomahony93** [nicolas-chaulet/torch-points3d#348]
I get the following error when running dasboard.ipynb in jupyter lab

> ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-6329f2835137> in <module>
      1 selector_model_name = pn.widgets.Select(name='Model name', options=experiment_manager.model_name_wviz)
----> 2 selector_paths = pn.widgets.Select(name='Available runs', options=experiment_manager.get_model_wviz_paths(selector_model_name.value))
      3 selector_epoch =  pn.widgets.Select(name='Epoch',options = experiment_manager.from_paths_to_epoch(selector_paths.value))
      4 selector_split =  pn.widgets.Select(name='Split',options = experiment_manager.from_epoch_to_split(selector_epoch.value))
      5 selector_file =  pn.widgets.Select(name='Sample',options = experiment_manager.from_split_to_file(selector_split.value))

/ichec/work/iecom001b/torch-points3d/torch_points3d/visualization/experiment_manager.py in get_model_wviz_paths(self, model_path)
    170 
    171     def get_model_wviz_paths(self, model_path):
--> 172         model_name = model_path + ".pt"
    173         self._current_exps = self._experiment_with_viz[model_name]
    174         return self._current_exps

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
> ---------------------------------------------------------------------------

All modules imported successfully. `model_path` seems to stay as it was initialized: 'None', should that be the case?

**Comment by nicolas-chaulet** [comment]
That's not correct no... We haven't been using those in a while. Have you run the following command before running the notebook?
```
jupyter labextension install @pyviz/jupyterlab_pyviz
```

**Comment by niallomahony93** [comment]
Yes, I ran that command before running the notebook. 

It seems to me that it is trying to get the model path before I have made any selections as to what run/model I want to visualise the results for.

**Comment by aboutyy** [comment]
> Yes, I ran that command before running the notebook.
> 
> It seems to be because I have nothing in the viz folder for the one run that I have from training votenet for object detection on scannet. How do I generate the visualizations for this?

I‘ve got the same problem, did u get any hint to solve this problem?

**Comment by nicolas-chaulet** [comment]
Ok, makes sense now. The visualisation dashboard is only working for a few specific models on segmentation tasks (I think pointnet++ and maybe kpconv). If you want to visualise the output I would suggest that you implement a notebook from scratch and save the output after each epoch. You can take a look at what we did for PointGroup:
https://github.com/nicolas-chaulet/torch-points3d/blob/12dfca3e94add3981f7f37db25df1e5acee640fe/torch_points3d/models/panoptic/pointgroup.py#L189-L205
And the notebook:
https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/pointgroup_debug.ipynb

You can probably also reuse this notebook to explore the visuals:
https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/scannet_object_explorer.ipynb

Does that help?

**Comment by niallomahony93** [comment]
Yes, that's helpful. It will probably be a while before I get to that stage with my own custom model but it looks to be clear what needs to be done for creating custom visualizations, Thanks.
