### ISSUE TITLE
Problem with downloading Shapenet dataset with https

### ISSUE THREAD

**Issue by MCvin** [nicolas-chaulet/torch-points3d#350]
Hi,

I am trying to run the Notebook PartSegmentationKPConv and since the website https://www.shapenet.org/
has an expired certificate, the https download from the class ShapeNetDataset fails:
```
Downloading https://shapenet.cs.stanford.edu/media/shapenetcore_partanno_segmentation_benchmark_v0_normal.zip
---------------------------------------------------------------------------
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)
```
Is there a way to perform this download manually and pass it to the class or to switch off the SSL secure download ?

**Comment by tchaton** [comment]
Hey @MCvin,

Here is the url link in the code: https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/datasets/segmentation/shapenet.py#L58

DATA_URL: "https://shapenet.cs.stanford.edu/media/" "shapenetcore_partanno_segmentation_benchmark_v0_normal.zip"

It will be downloaded with this `download` function: https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/datasets/segmentation/shapenet.py#L175

It will be then processed: https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/datasets/segmentation/shapenet.py#L252

If you put the data into {dataset_name}/raw as described within download it should work.

Best regards,
T.C

**Comment by MCvin** [comment]
Thanks a lot @tchaton !

**Comment by nicolas-chaulet** [comment]
Closing for now as this is temporary hopefully
