### ISSUE TITLE
Reimplementation Modelnet40

### ISSUE THREAD

**Issue by shangguan91** [nicolas-chaulet/torch-points3d#352]
dear Author,

if i want to reimplement different model, eg. Conpoint, KPcov on my own dataset, i need to write Classfication model bymyself?

there is no pretrained example?

**Comment by tchaton** [comment]
Hi @shangguan91,

I am not sure to fully grasp the question. KPConv and other models are already implemented. You can use them.
If you have your own custom dataset, then you will have to implement it.

If you want to run any model on ModelNet. Create a new directory classification on model. add a new yaml file with the name of the model. 
Example for kpconv as model_name. 

1. Copy the config from this encoder configuration : https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/applications/conf/kpconv/encoder_4.yaml into conf/models/classification/kpconv.yaml

class: kpconv.KPConvEncoder is a pointer to a class `KPConvEncoder` within a file within torch_points3d/models/{}/kpconv
This file doesn't exist yet.

So create a file kpconv in orch_points3d/models/classification and add a KPConvEncoder (you can find an example in segmentation as KPConvPaper).

You will just have to implement __init__, set_input, forward and backward function and it will works fine.

```
python train.py task=classification dataset=modelnet model_name=kpconv model_type=KPConvEncoder.
```

Best regards,
T.C

**Comment by sidml** [comment]
@tchaton 
It will be great if you could provide a toy example about using kpconv using raw pointcloud data. Maybe something like this ?
```
from torch_points3d.applications.kpconv import KPConv 
from torch_points3d.datasets.batch import SimpleBatch 
model = KPConv( 
         architecture="unet", 
         input_nc=3, 
         output_nc=10,  
         num_layers=4, 
     )    

nb_points = 100 
pos = torch.randn((nb_points, 3)) 
y = torch.tensor([range(10) for i in range(pos.shape[0])], dtype=torch.float) 
d = Data(pos=pos, y=y)  
b = SimpleBatch.from_data_list([d, d])
model(b)
```

This is just to give an idea. The above code doesn't work.. I get the following error

> Exception: batch_x and batch_y should be provided.

**Comment by shangguan91** [comment]
@tchaton 
Thank you for the elaboration, i get the idea now. 
And how far do i have to modify the architecture from Segmentation to Classifcation.
I think ppl who is new like me starting from classification problem of point cloud will be appreciated if the classifcation for Modelnet40 could be showed in your repo as well

**Comment by tchaton** [comment]
Hey @shangguan91,

You are entirely right. I will add it when I have time and ping you if you didn't manage to make it work.

Here is the example notebook where we trained RSconv using the API on ModelNet: https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/ObjectClassificationRSConv.ipynb

Best regards,
Thomas Chaton.

**Comment by tchaton** [comment]
@sidml @shangguan91 Here is the example for segmentation
```
import numpy as np
import torch
from torch_points3d.applications.kpconv import KPConv 
from torch_geometric.data import Batch, Data

# KPConv is implemented with PARTIAL_DENSE format. Therefore, data need an attribute batch containing the indice for each point

input_nc = 0
num_classes = 10
batch_size = 2
num_points_per_sample = [20, 30]

model = KPConv( 
         architecture="unet", # Could be encoder here to perform classification
         input_nc=input_nc, # KPconv is particular. Pos aren't features. It needs a tensor of ones + any features available as rgb or intensity
         output_nc=num_classes,  
         num_layers=4, 
     )    

samples = []
for idx_batch in range(batch_size):
    nb_points = num_points_per_sample[idx_batch]
    pos = torch.randn((nb_points, 3)) 
    y = torch.from_numpy(np.random.choice(range(num_classes), nb_points))
    x = torch.ones((nb_points, 1))
    samples.append(Data(pos=pos, y=y, x=x))
data = Batch.from_data_list(samples)

print(data)
# Batch(batch=[50], pos=[50, 3], x=[50, 1], y=[50])

print(data.batch)
# tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
#        1, 1, 

output = model.forward(data)
print(output)
# Batch(batch=[50], block_idx=2, idx_neighboors=[50, 25], pos=[50, 3], x=[50, 10], y=[50])
```

**Comment by tchaton** [comment]
@sidml @shangguan91 Here is the example for classification.

Just changed `unet` into `encoder ` :)

```
import numpy as np
import torch
from torch_points3d.applications.kpconv import KPConv 
from torch_geometric.data import Batch, Data

# KPConv is implemented with PARTIAL_DENSE format. Therefore, data need an attribute batch containing the indice for each point

input_nc = 0
num_classes = 10
batch_size = 2
num_points_per_sample = [20, 30]

model = KPConv( 
         architecture="encoder", # Could be encoder here to perform classification
         input_nc=input_nc, # KPconv is particular. Pos aren't features. It needs a tensor of ones + any features available as rgb or intensity
         output_nc=num_classes,  
         num_layers=4, 
     )    

samples = []
for idx_batch in range(batch_size):
    nb_points = num_points_per_sample[idx_batch]
    pos = torch.randn((nb_points, 3)) 
    y = torch.from_numpy(np.random.choice(range(num_classes), nb_points))
    x = torch.ones((nb_points, 1))
    samples.append(Data(pos=pos, y=y, x=x))
data = Batch.from_data_list(samples)

print(data)
# Batch(batch=[50], pos=[50, 3], x=[50, 1], y=[50])

print(data.batch)
# tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
#        1, 1, 

output = model.forward(data)
print(output)
# Batch(batch=[2], block_idx=10, idx_neighboors=[50, 38], pos=[2, 3], x=[2, 10], y=[50])
```

**Comment by tchaton** [comment]
Here is PR with the code samples: https://github.com/nicolas-chaulet/torch-points3d/pull/353/files

**Comment by sidml** [comment]
@tchaton Thanks ! It's very helpful.

**Comment by shangguan91** [comment]
@tchaton Thank you so much!

**Comment by nicolas-chaulet** [comment]
CLsoing for now!
