### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by pvnieo** [nicolas-chaulet/torch-points3d#354]
Hi,

Thanks for the great library.

This is not an issue, but a feature request. Would it be possible to add for each implemented model the possibility to use a pretrained version of it, on some dataset that is used in the literature, e.g shapenet? Ideally, this would be just a parameter to use while instantiating the model `pretrained=False`.

Thank you.

**Comment by tchaton** [comment]
Hi @pvnieo,

It is already supported :)

```
model = PretainedRegistry.from_pretrained("pointnet2_largemsg-s3dis-1")
```
It will download and create a pointnet2_largemsg trained on s3dis fold 1.

What is left is to train models and weights url to the `PretainedRegistry`. The tag name needs to be consistent with model and training.

I hope I will you add some newly trained models. 

Best regards,
Thomas Chaton.

**Comment by pvnieo** [comment]
Thank you for your response. It's clear for me. I will try to add some new models.
