### ISSUE TITLE
Models for mesh classification

### ISSUE THREAD

**Issue by shangguan91** [nicolas-chaulet/torch-points3d#355]
Dear Author, 

do you know models other than SplineCnn, which deal with Mesh data? 
SplineCNN also deal with the node classification, does that mean any model dealing with node classifcation can be used in Mesh?

**Comment by loicland** [comment]
https://ranahanocka.github.io/MeshCNN/ rely on edges

**Comment by shangguan91** [comment]
@loicland  thank you for reply. However, is there only two or three methods for mesh classification?  Do you happen to know some paper wraping up methods?

**Comment by nicolas-chaulet** [comment]
Closing for now, if you want to keep exploring this feel free to join our slack!
