### ISSUE TITLE
The difference among object Classification, shape classification and Segmentation

### ISSUE THREAD

**Issue by shangguan91** [nicolas-chaulet/torch-points3d#364]
Dear all, 

I have started  to implement different models on point cloud since last month, most task is point cloud classification on eg. Modelnet40. However, i encounter different key-words like object classifcation and shape classification. what is the difference?

**Comment by tchaton** [comment]
Dear @shangguan91 ,

object classifcation is the same as shape classification: Classification of 3d shapes. Each point cloud is going to be classified: Example: a chair, table, etc..

Segmentation: It is point-wise classification. Each point is being assigned to a class. 

From segmentation, you extend it to object detection or panoptic segmentation.

object detection: Finding bounding boxes for objects

panoptic segmentation equals instance segmentation: Each point is going to say. I belong to this class + this object

**Comment by shangguan91** [comment]
so if i have a Church point cloud data with different Label. e.g. Gotic and Romantic. This task for classfiying one church to another belong to object classification?

**Comment by tchaton** [comment]
Yes.
