### ISSUE TITLE
if all models in torch-point3d can be applied for Classifcation task

### ISSUE THREAD

**Issue by shangguan91** [nicolas-chaulet/torch-points3d#365]
eg, RandLA-Net is specifically designed for Semantic Segmentation, could also be applied in Classfication with just lines of code refactoring?

**Comment by nicolas-chaulet** [comment]
Yes, please take a look at this notebook for an example:
https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/ObjectClassificationRSConv.ipynb
