### ISSUE TITLE
How to change n_kernel_points in kpconv ?

### ISSUE THREAD

**Issue by sidml** [nicolas-chaulet/torch-points3d#368]
Hi.
I was wondering if it's possible to change n_kernel_points in kpconv.
I tried passing n_kernel_points in kpconv as a parameter while defining the model but it doesn't work. 
I also tried adding a new field named n_kernel_points in kpconv in the yaml file.
Any help is appreciated. Thanks.

**Comment by tchaton** [comment]
Dear @sidml, yes it is possible. 

Not sure we connected it properly from configuration file to the KPConvLayer class creation.

Here is the `n_kernel_points ` params: 
https://github.com/nicolas-chaulet/torch-points3d/blob/94454627a3d5243b586fe1452f8071a9f2e1caa1/torch_points3d/modules/KPConv/kernels.py#L42

Would you mind connecting it to the configuration and opening a PR ?

Best regards,
Thomas Chaton.
