### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by romaintha** [nicolas-chaulet/torch-points3d#371]
Hi,
I ve encountered an installation issue. After running:
`pip install torch`
and
`pip install torch-points3d`

I tried to import this in a python shell:
`from torch_points3d.models.segmentation.pointcnn import PointCNNSeg`

I got the following error:
`RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_sparse has CUDA version 0.0. Please reinstall the torch_sparse that matches your PyTorch install.`

I would first like to be able to use torch-points3d without CUDA (for test and CICD purposes). For prod, I will use a docker image.

**Details:**
OS: Ubuntu 20.04
Python: 3.8.2

`pip freeze
absl-py==0.9.0
ase==3.19.2
backcall==0.2.0
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
configparser==5.0.0
cycler==0.10.0
decorator==4.4.2
docker-pycreds==0.4.0
future==0.18.2
gitdb==4.0.5
GitPython==3.1.7
google-auth==1.20.0
google-auth-oauthlib==0.4.1
googledrivedownloader==0.4
gql==0.2.0
graphql-core==1.1
grpcio==1.30.0
h5py==2.10.0
hydra-core==0.11.3
idna==2.10
imageio==2.9.0
ipython==7.16.1
ipython-genutils==0.2.0
isodate==0.6.0
jedi==0.17.2
Jinja2==2.11.2
joblib==0.16.0
jsonpatch==1.26
jsonpointer==2.0
kiwisolver==1.2.0
llvmlite==0.32.1
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==3.3.0
networkx==2.4
numba==0.49.1
numpy==1.19.1
nvidia-ml-py3==7.352.0
oauthlib==3.1.0
omegaconf==1.4.1
pandas==1.1.0
parso==0.7.1
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
promise==2.3
prompt-toolkit==3.0.5
protobuf==3.12.2
psutil==5.7.2
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.6.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytorch-metric-learning==0.9.89
pytz==2020.1
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.1
rdflib==5.0.0
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-image==0.16.2
scikit-learn==0.23.1
scipy==1.5.2
sentry-sdk==0.16.2
shortuuid==1.0.1
six==1.15.0
smmap==3.0.4
subprocess32==3.5.4
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
threadpoolctl==2.1.0
torch==1.6.0
torch-cluster==1.5.6
torch-geometric==1.6.0
torch-points-kernels==0.6.7
torch-points3d==1.0.1
torch-scatter==2.0.5
torch-sparse==0.6.6
torchfile==0.1.0
torchnet==0.0.4
torchvision==0.7.0
tornado==6.0.4
tqdm==4.48.0
traitlets==4.3.3
urllib3==1.25.10
visdom==0.1.8.9
wandb==0.8.36
watchdog==0.10.3
wcwidth==0.2.5
websocket-client==0.57.0
Werkzeug==1.0.1`

Stacktrace: 

` <ipython-input-1-8e449cf48170> in <module>
----> 1 from torch_points3d.models.segmentation.pointcnn import PointCNNSeg

~/Envs/test/lib/python3.8/site-packages/torch_points3d/models/segmentation/pointcnn.py in <module>
----> 1 from .base import Segmentation_MP
      2 from torch_points3d.modules.PointCNN import *
      3 
      4 
      5 class PointCNNSeg(Segmentation_MP):

~/Envs/test/lib/python3.8/site-packages/torch_points3d/models/segmentation/base.py in <module>
      4 from typing import Any
      5 
----> 6 from torch_points3d.models.base_architectures import UnetBasedModel
      7 from torch_points3d.datasets.segmentation import IGNORE_LABEL
      8 

~/Envs/test/lib/python3.8/site-packages/torch_points3d/models/base_architectures/__init__.py in <module>
----> 1 from .unet import *
      2 from .backbone import *

~/Envs/test/lib/python3.8/site-packages/torch_points3d/models/base_architectures/unet.py in <module>
      1 from torch import nn
----> 2 from torch_geometric.nn import (
      3     global_max_pool,
      4     global_mean_pool,
      5     fps,

~/Envs/test/lib/python3.8/site-packages/torch_geometric/__init__.py in <module>
      1 from .debug import is_debug_enabled, debug, set_debug
----> 2 import torch_geometric.nn
      3 import torch_geometric.data
      4 import torch_geometric.datasets
      5 import torch_geometric.transforms

~/Envs/test/lib/python3.8/site-packages/torch_geometric/nn/__init__.py in <module>
      1 from .meta import MetaLayer
----> 2 from .data_parallel import DataParallel
      3 from .reshape import Reshape
      4 from .conv import *  # noqa
      5 from .norm import *  # noqa

~/Envs/test/lib/python3.8/site-packages/torch_geometric/nn/data_parallel.py in <module>
      3 
      4 import torch
----> 5 from torch_geometric.data import Batch
      6 
      7 

~/Envs/test/lib/python3.8/site-packages/torch_geometric/data/__init__.py in <module>
----> 1 from .data import Data
      2 from .batch import Batch
      3 from .dataset import Dataset
      4 from .in_memory_dataset import InMemoryDataset
      5 from .dataloader import DataLoader, DataListLoader, DenseDataLoader

~/Envs/test/lib/python3.8/site-packages/torch_geometric/data/data.py in <module>
      5 import torch
      6 import torch_geometric
----> 7 from torch_sparse import coalesce, SparseTensor
      8 from torch_geometric.utils import (contains_isolated_nodes,
      9                                    contains_self_loops, is_undirected)

~/Envs/test/lib/python3.8/site-packages/torch_sparse/__init__.py in <module>
     25 
     26     if t_major != major or t_minor != minor:
---> 27         raise RuntimeError(
     28             f'Detected that PyTorch and torch_sparse were compiled with '
     29             f'different CUDA versions. PyTorch has CUDA version '

RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_sparse has CUDA version 0.0. Please reinstall the torch_sparse that matches your PyTorch install.`

**Comment by nicolas-chaulet** [comment]
This is an error coming from torch sparse library: https://github.com/rusty1s/pytorch_sparse
Please double check their installation instructions. It should work out of the box in principle but sometime it doesn't...

**Comment by romaintha** [comment]
I see, then I encoutered this error: 
`OSError: /home/romain/Envs/test/lib/python3.8/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs`

[Here](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1) they suggested building PyTorch from source....
I guess I m gonna use the docker image also locally

**Comment by nicolas-chaulet** [comment]
Clsoing for now
