### ISSUE TITLE
How to train PointGroup on S3DIS dataset?

### ISSUE THREAD

**Issue by fengziyue** [nicolas-chaulet/torch-points3d#377]
There is no pointgroup code in torch-points3d/applications, so how to train pointgroup on s3dis?

**Comment by tchaton** [comment]
Dear @fengziyue,

We don't have implemented s3dis panoptic yet. We support s3dis only for segmentation for now in 3 different modes.
Feel free to implement s3dis for panoptic by opening a PR. 
Look at scannet panoptic for implementation and PointGroup input interface :)

Best regards,
Thomas Chaton.

**Comment by nicolas-chaulet** [comment]
Just to complement on @tchaton's answer, the data object that is returns by the dataloader needs to contain the following items:
https://github.com/nicolas-chaulet/torch-points3d/blob/d798b11df8e6a0756685918fc9f9208a8df0f294/torch_points3d/models/panoptic/structures.py#L52-L58

and you can take a look at scannet version as an example:
https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/datasets/panoptic/scannet.py

After that you should be good to go!
Just be aware that we haven't replicated the exact performance advertised in the original paper and Minkowski Engine is notably slower than spconv (sparse convolutions used in the original implementation). We are still working on reproducing the exact performance and Minkowski should get faster soon.

**Comment by fengziyue** [comment]
So is there any instance segmentation model implemented on S3DIS?

**Comment by nicolas-chaulet** [comment]
No, the dataset does not expose instances at the moment. So no way to train models on it! As soon as it does then it's easy to train PointGroup

**Comment by fengziyue** [comment]
what do you mean "does not expose instances"?
I found there are annotations per instance in the raw data folder, like "chair_1.txt", "chair_2.txt"

**Comment by tchaton** [comment]
Dear @fengziyue,

The raw data contains instances. We just have written the parsers for segmentation. Instance segmentation need to be implemented.

Best,
T.C

**Comment by fengziyue** [comment]
Thank you @tchaton 
I want to train an instance seg model on S3DIS, maybe PointGroup, or do you have other recommendations?
Don't know should I modify from the original PointGroup repository or torch-points3d. Do you have any suggestions?

Thank you!

**Comment by tchaton** [comment]
Hey @fengziyue,

We don't support instance segmentation for s3dis yet. Only scannet. 
If you want to train PointGroup or similar model, you have 3 choices:
1. Either you can check the original PointGroup codebase and try to make it work.
2. Or you can add S3dis instance segmentation to TorchPoints3d, and train our re-implementation of PointGroup on it 👍 
3. Train PointGroup on Scannet panoptic.

Best regards,
Thomas Chaton.

**Comment by tchaton** [comment]
Hey @fengziyue,

I have a PR pending with s3dis panoptic: https://github.com/nicolas-chaulet/torch-points3d/pull/403
If you want to give a try. I also added cylindricSampling.

Best,
T.C

**Comment by nicolas-chaulet** [comment]
Looks like a duplicate
