### ISSUE TITLE
Please fix the certificate for download data

### ISSUE THREAD

**Issue by shangguan91** [nicolas-chaulet/torch-points3d#382]
most url for dataset in pretrained model failed to download, anyway to modify code with no certificate check?

**Comment by tchaton** [comment]
Should be resolved after merging this PR: https://github.com/nicolas-chaulet/torch-points3d/pull/370/files I will do it this week.

**Comment by shangguan91** [comment]
@tchaton btw, i have tried notebooks/ObjectClassificationRSConv.ipynb, when i train, it crashed at first epoch. when i run the code again,
![image](https://user-images.githubusercontent.com/64595972/89179384-e5c2a600-d58f-11ea-8294-0cbd99d27888.png)
