### ISSUE TITLE
poetry fail to install dependencies

### ISSUE THREAD

**Issue by shangguan91** [nicolas-chaulet/torch-points3d#384]
![image](https://user-images.githubusercontent.com/64595972/89157056-21e40f80-d56c-11ea-94ae-606442d90949.png)

**Comment by nicolas-chaulet** [comment]
Hey, sorry about that, could you please show the entire error message?

**Comment by shangguan91** [comment]
_• Installing torch-points-kernels (0.6.6): Failed

  EnvCommandError

  Command ['/root/.cache/pypoetry/virtualenvs/torch-points3d-hAkkEUNl-py3.6/bin/pip', 'install', '--no-deps', '/root/.cache/pypoetry/artifacts/42/04/b5/1848f5b22cf2f0c33e8d5d248d9559ac4feb244fd4b50c471d1f6d9f82/torch-points-kernels-0.6.6.tar.gz'] errored with the following return code 1, and output: 
  Processing /root/.cache/pypoetry/artifacts/42/04/b5/1848f5b22cf2f0c33e8d5d248d9559ac4feb244fd4b50c471d1f6d9f82/torch-points-kernels-0.6.6.tar.gz
  Building wheels for collected packages: torch-points-kernels
    Building wheel for torch-points-kernels (setup.py): started
    Building wheel for torch-points-kernels (setup.py): finished with status 'error'
    ERROR: Failed building wheel for torch-points-kernels
    Running setup.py clean for torch-points-kernels
  Failed to build torch-points-kernels
  DEPRECATION: Could not build wheels for torch-points-kernels which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
  Installing collected packages: torch-points-kernels
      Running setup.py install for torch-points-kernels: started
      Running setup.py install for torch-points-kernels: finished with status 'error'
  ERROR: Command errored out with exit status 1: /root/.cache/pypoetry/virtualenvs/torch-points3d-hAkkEUNl-py3.6/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mh94elzg/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mh94elzg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nxsoxemi/install-record.txt --single-version-externally-managed --compile --install-headers /root/.cache/pypoetry/virtualenvs/torch-points3d-hAkkEUNl-py3.6/include/site/python3.6/torch-points-kernels Check the logs for full command output.
  

  at /usr/local/lib/python3.6/dist-packages/poetry/utils/env.py:915 in _run
       911│                 output = subprocess.check_output(
       912│                     cmd, stderr=subprocess.STDOUT, **kwargs
       913│                 )
       914│         except CalledProcessError as e:
    →  915│             raise EnvCommandError(e, input=input_)
       916│ 
       917│         return decode(output)
       918│ 
       919│     def execute(self, bin, *args, **kwargs):

  • Installing torch-scatter (2.0.5)
  • Installing torch-sparse (0.6.6): Installing...
  • Installing torchnet (0.0.4)
  • Installing wandb (0.8.36)
  • Installing torch-cluster (1.5.5)
  • Installing torch-geometric (1.6.0)
  • Installing torch-points-kernels (0.6.6): Failed

  EnvCommandError

  Command ['/root/.cache/pypoetry/virtualenvs/torch-points3d-hAkkEUNl-py3.6/bin/pip', 'install', '--no-deps', '/root/.cache/pypoetry/artifacts/42/04/b5/1848f5b22cf2f0c33e8d5d248d9559ac4feb244fd4b50c471d1f6d9f82/torch-points-kernels-0.6.6.tar.gz'] errored with the following return code 1, and output: 
  Processing /root/.cache/pypoetry/artifacts/42/04/b5/1848f5b22cf2f0c33e8d5d248d9559ac4feb244fd4b50c471d1f6d9f82/torch-points-kernels-0.6.6.tar.gz
  Building wheels for collected packages: torch-points-kernels
    Building wheel for torch-points-kernels (setup.py): started
    Building wheel for torch-points-kernels (setup.py): finished with status 'error'
    ERROR: Failed building wheel for torch-points-kernels
    Running setup.py clean for torch-points-kernels
  Failed to build torch-points-kernels
  DEPRECATION: Could not build wheels for torch-points-kernels which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
  Installing collected packages: torch-points-kernels
      Running setup.py install for torch-points-kernels: started
      Running setup.py install for torch-points-kernels: finished with status 'error'
  ERROR: Command errored out with exit status 1: /root/.cache/pypoetry/virtualenvs/torch-points3d-hAkkEUNl-py3.6/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mh94elzg/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mh94elzg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nxsoxemi/install-record.txt --single-version-externally-managed --compile --install-headers /root/.cache/pypoetry/virtualenvs/torch-points3d-hAkkEUNl-py3.6/include/site/python3.6/torch-points-kernels Check the logs for full command output.
  

  at /usr/local/lib/python3.6/dist-packages/poetry/utils/env.py:915 in _run
       911│                 output = subprocess.check_output(
       912│                     cmd, stderr=subprocess.STDOUT, **kwargs
       913│                 )
       914│         except CalledProcessError as e:
    →  915│             raise EnvCommandError(e, input=input_)
       916│ 
       917│         return decode(output)
       918│ 
       919│     def execute(self, bin, *args, **kwargs):_

**Comment by shangguan91** [comment]
@nicolas-chaulet 
Btw, i also tried to install torch-point 3d normally by pip on Google colab, However, following  error shows up
![image](https://user-images.githubusercontent.com/64595972/89165315-ab014380-d578-11ea-9cb0-e35608ceb20a.png)

**Comment by shangguan91** [comment]
@nicolas-chaulet 
is it normal to take 40 minutes to install torch-point-kernel?  do you need a good internet to install it on google colab?
i have problem installing it, and it is so frustrated.

**Comment by nicolas-chaulet** [comment]
No it should not take that long. I think it is not only torch-points-kernels that takes time. torch-cluster and torch-sparse are time consuming to compile as well... You can use pre built wheels, I will update the colab notebooks so that they use those instead

**Comment by shangguan91** [comment]
could you please give me a notice after you update the notebooks? thank you in advance!

**Comment by nicolas-chaulet** [comment]
So, I just checked and looks like there is not much you can do for colab, it just takes time to compile the different libraries, and binaries for the latest pytorch have not been released yet (it's not only torch-points-kernels but also all the binaries from pytorch geometric). 

Going back to your initial error, I was not able to reproduce without more context sorry.

I also ran this colab notebook: https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/PartSegmentationKPConv.ipynb and it installs just fine, it just takes time...

**Comment by shangguan91** [comment]
thank you, note book now are all fine

**Comment by wfeng66** [comment]
It is still a problem now. The following is the error when running the above notebook on Colab:

Building wheels for collected packages: numba, scikit-image, torch-cluster, torch-geometric, torch-points-kernels, torch-scatter, torch-sparse, torchnet, gql, llvmlite, nvidia-ml-py3, subprocess32, visdom, graphql-core
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for numba (setup.py) ... error
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for scikit-image (setup.py) ... error
  ERROR: Failed building wheel for scikit-image
  Running setup.py clean for scikit-image

**Comment by msh003** [comment]
I face the error . Is there anyone who can solved the problem?
```
Downloading jsonpointer-3.0.0-py2.py3-none-any.whl (7.6 kB)
Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
Building wheels for collected packages: numba, scikit-image, torch-cluster, torch-geometric, torch-points-kernels, torch-scatter, torch-sparse, torchnet, gql, llvmlite, nvidia-ml-py3, subprocess32, visdom, graphql-core
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for numba (setup.py) ... error
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
```
