### ISSUE TITLE
Differences between author's and this KPConv implementation

### ISSUE THREAD

**Issue by sidml** [nicolas-chaulet/torch-points3d#388]
Hi.

I was wondering what are the major differences between the author's pytorch implementation [here](https://github.com/HuguesTHOMAS/KPConv-PyTorch) and this repo's implementation. 
After a cursory look, i had the following doubts:
1. The configuration file located [here](https://github.com/nicolas-chaulet/torch-points3d/blob/d6a3b93bb5003bf0fd9b1552d7b62fd671b35dd1/torch_points3d/applications/conf/kpconv/unet_4.yaml) defines networks for which dataset (s3dis, semantic kitti or something else ?)
2. The parameter max_neighbors corresponds to which parameter in the original implementation ?
3. Why is bn_momentum= 0.2,  [here](https://github.com/nicolas-chaulet/torch-points3d/blob/d6a3b93bb5003bf0fd9b1552d7b62fd671b35dd1/torch_points3d/applications/conf/kpconv/unet_4.yaml#L6) ? In original [implementation](https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/train_S3DIS.py),  it's set as 0.02 

Any help is appreciated. Thanks.

**Comment by nicolas-chaulet** [comment]
Yes, it is slightly different indeed.
1. It should be working on any dataset really, hyper parameters don't impact the results that much in my experience
2. This sets the maximum number of neighbours we use when doing the point convolution. This parameter is computed dynamically in the original implementation and we use the values that the automation is giving.
3. For no particular reason. Again, it does not affect the results that much

**Comment by sidml** [comment]
Thanks for the quick reply.

I personally think **in_grid_size** parameter is quite significant. For example: in the  [original implementation](https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/9bae9a3a2a04a3675fa4ec6e5993711438a32e9f/train_SemanticKitti.py#L99) it is set as 4.0 for semantic kitti  and 1.5 for [s3dis](https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/9bae9a3a2a04a3675fa4ec6e5993711438a32e9f/train_S3DIS.py#L97).  Also, in_grid_size seems to have a big impact on the training time.

**Comment by nicolas-chaulet** [comment]
Hi, 
that's not `in_grid_size`, this is related to the dataset. It means that we sample spheres of 4m or 1.5m radius to feed to the network. `in_grid_size` should be equal to the size of the voxel of the input point cloud (3cm -> 0.03 for S3DIS for example). We have decoupled completely the dataset parameters from the model parameters and the only link is this grid size parameter, that's it. All the others can be chosen completely independently.
Does that make things clearer? When using the API to build a KPConv model you can pass any parameter defined in the `define_constants:` section [here](https://github.com/nicolas-chaulet/torch-points3d/blob/d6a3b93bb5003bf0fd9b1552d7b62fd671b35dd1/torch_points3d/applications/conf/kpconv/unet_4.yaml) as a keyword argument. That's how you can change the grid_sie parameter of the model, it does not have to be 0.02.

**Comment by sidml** [comment]
Okay.  I mentioned this particular parameter because for beginners it mayn't be readily apparent and they may always go with the default value in yaml file.

i was wondering if you have been able to replicate the kpconv paper's results on any of the dataset using this repo's implementation. If so, is it possible to access the pretrained models ? Thanks.

**Comment by nicolas-chaulet** [comment]
Yes, you are right it is not super intuitive. The best place to have more info is the API documentation here:
https://torch-points3d.readthedocs.io/en/latest/src/api/models.html

Regarding pre trained, we have a few pretrained kpconv models, please refer to this part of the README for more details
https://github.com/nicolas-chaulet/torch-points3d#add-your-model-to-the-pretrainedregistry
