### ISSUE TITLE
KPConv implementation

### ISSUE THREAD

**Issue by pvnieo** [nicolas-chaulet/torch-points3d#394]
Hi,

Thank you for the great library.

I have a question concerning the implementation of KPConv used in this library. I noticed that some things that exist in the original [implementation](https://github.com/HuguesTHOMAS/KPConv), `kernel radius`, `repulsive regularization`, `number of points in kernel`, `density_parameter`, `Influence function` ('constant', 'linear', 'gaussian'), etc,  are not present in your implementation. 

What is the motivation behind this choice? and what is the impact of this choice on the performance?

Thank you in advance.

**Comment by nicolas-chaulet** [comment]
Those are actually present, simply not exposed in the API. The only one that would make sense to expose in my opinion is the number of points in kernel, the others don't seem to improve the results too much. Do you have a particular idea in mind?

**Comment by pvnieo** [comment]
Hi @nicolas-chaulet,

Thank you for your response.

Actually, I don't have an idea in mind, but I only want to know how different is your implementation from the original one.

Actually, I used this implementation for one application, and I get better result from the original one, and I want to explain that. Why it gives better result?

**Comment by nicolas-chaulet** [comment]
Interesting... It is most likely on some hyper parameters, you can probably spot those in the print of the model. A couple of key ones to look for are number of neighbours and grid size at the input of your network.

**Comment by pvnieo** [comment]
How do I get the print of the model?

**Comment by pvnieo** [comment]
Thank you for your response. 

Did you run a reproduction experiment to compare the result of the two implementations?

**Comment by nicolas-chaulet** [comment]
Yes, we did on S3DIS and it matches.
