### ISSUE TITLE
How to implement models without a dataset?

### ISSUE THREAD

**Issue by cisprague** [nicolas-chaulet/torch-points3d#396]
Hi! I'm working on an application that requires the online implementation of PointNet (or similar architectures) within a larger model in a reinforcement learning setting. I've looked through the docs on how to create a dataset, but, in my case, I am just dealing with a single tensor `T`, with `n` `m`-dimensional points; i.e. `T.shape == (n, m)`. Is there a straightforward way to input `T` into a model in order to output a feature vector `v`, e.g. `v.shape == (1024,)` in the case of PointNet.

This is what I want to do:
```python
from torch_points3d.applications.pointnet2 import PointNet2

model = PointNet2(
   architecture="unet",
   input_nc=3,
   output_nc=1024,
   num_layers=3,
   multiscale=True,
   config=None,
)

# Number of points (n) and their dimension (m)
n, m = 1000, 3

# pointcloud
T = torch.randn((n, m))

# compute 1024 feature vector
v = model(T)
assert(v.shape == (1024,))
```

**Comment by nicolas-chaulet** [comment]
A couple of things:

- you need to wrap your positions into a PyTorch geometric `Data` object: `data = Data(pos = T, x=feature_tensor)` assuming that T holds the position of your points
- PointNet++ and RSConv except Dense batches, the shape of your input should be `[batch, num_points, dimension]`, take a look at our Medium post for more details: https://towardsdatascience.com/torch-points3d-a-unifying-framework-for-deep-learning-on-point-clouds-94115c0be4fb

**Comment by cisprague** [comment]
@nicolas-chaulet thanks for the reply!

- What if the node positions are the features? In that case, would it be `data = Data(pos=T, x=T)`? 
- And, what if `T` does not represent positions, but some other physically meaningful quantities, e.g. velocity?

In my application, I will always have only one batch. But, I find that I need to provide more than one batch in order to use `PointNet2`, see below:
```python
T = torch.randn((1000, 3)).unsqueeze(0)

data = Data(x=T, pos=T)
data = Batch.from_data_list([data, data])

model = PointNet2(
    architecture='encoder',
    input_nc=3,
    num_layers=3,
    output_nc=10,
    multiscale=True
)

res = model(data)
```
- If I use `data = Batch.from_data_list([data])` instead, I get `ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 10, 1])`. 
- Further, I noticed that when I use `model.eval()`, `res.x[0]` and `res.x[1]` are not the same — shouldn't they be?

**Comment by tchaton** [comment]
You have some examples for KPConv here: https://github.com/nicolas-chaulet/torch-points3d/blob/master/examples/kpconv_segmentation_forward.py

**Comment by tchaton** [comment]
```
import torch
from torch_points3d.applications.pointnet2 import PointNet2
from torch_geometric.data import Batch, Data

num_points = 1024
num_classes = 10
input_nc = 5

pos = torch.randn((num_points, 3)).unsqueeze(0)
T = torch.randn((num_points, input_nc)).unsqueeze(0)

data = Data(pos=pos, x=T)
data = Batch.from_data_list([data, data])

print(data)
# Batch(batch=[2], pos=[2, 1024, 3], x=[2, 1024, 5])

# pos gets concatenated with x features
model = PointNet2(architecture="unet", input_nc=input_nc, num_layers=3, output_nc=num_classes)

res = model(data)
print(res)
# Data(pos=[2, 1024, 3], x=[2, 10, 1024])
```

**Comment by cisprague** [comment]
@tchaton thank you for the example!
Last question: why is `data` different after executing `model(data)`?
After running the above code, `data` returns `
Batch(batch=[2], pos=[2, 1024, 3], x=[2, 5, 1024])`.
The shape of `data.x` has changed.

**Comment by shangguan91** [comment]
@cisprague hey, i am wondering if you could help me. have you already reimplement the classification task for modelnet40 by using list of model in this repo?

**Comment by nicolas-chaulet** [comment]
> After running the above code, `data` returns ` Batch(batch=[2], pos=[2, 1024, 3], x=[2, 5, 1024])`.
> The shape of `data.x` has changed.

Yes, it is modified in place by the model. If you want to keep it unchanged just run `model(data.clone())`
