### ISSUE TITLE
How to install with specific CUDA version?

### ISSUE THREAD

**Issue by cisprague** [nicolas-chaulet/torch-points3d#402]
I've installed `pytorch-geometric` with Torch 1.6.0 and CUDA 10.2, using their installation instructions.
However, when I follow the instruction to install `torch-points3d`, it reinstalls all of `pytorch-geometric` without CUDA. So, then I have to install `pytorch-geometric` again. How can install `torch-points3d` with a specific CUDA version?

Also, when I do the above, I get this error from `pip3`: `torch-points3d 1.1.1 requires torch-cluster<1.5.6, but you'll have torch-cluster 1.5.7 which is incompatible.`.

And, when I do this:
```python
from torch_points3d.applications.pointnet2 import PointNet2
```
I get this `ImportError: /usr/local/lib/python3.6/dist-packages/torch_points_kernels/points_cpu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIfEEEPKNS_6detail12TypeMetaDataEv`

**Comment by nicolas-chaulet** [comment]
Hey this looks like some issues with  your CUDA setup, did you run through the troubleshooting steps in the readme?

**Comment by nicolas-chaulet** [comment]
Closing for lack of response
