### ISSUE TITLE
How to set tracker for my owndata

### ISSUE THREAD

**Issue by shangguan9191** [nicolas-chaulet/torch-points3d#404]
From the example of your notebook for classifcation problem
i have transform my own data from data[face,pos,y] to SimpleBatch(pos=[12, 1024, 3], x=[12, 1024, 3], y=[12, 1]), which is ready for train for pointnet and rsconv. 

However, my dataset do not have tracker.  I simply create train and test dataloader respectively from train_folder and test_folder.

do i need to write entire code like : classification/modelnet.py. or i can simply concatenate tracker on my own data

**Comment by nicolas-chaulet** [comment]
You can easily reuse some of the trackers already implemented:
https://github.com/nicolas-chaulet/torch-points3d/tree/master/torch_points3d/metrics

**Comment by shangguan91** [comment]
@nicolas-chaulet 

I set train and test tracker using : traintracker=ClassificationTracker(train_loader.dataset,stage='train')
                                                      testtracker=ClassificationTracker(val_loader.dataset,stage='test')
and modify the code for train_epoch: 
![image](https://user-images.githubusercontent.com/64595972/89890108-18dde880-dbd3-11ea-8b14-5709e3a5b3cf.png)

However, when i train, i still need define tracker, is there any way that i can combine traintracker and testtracker into one tracker.

**Comment by nicolas-chaulet** [comment]
Hey, this goes beyond the scope of this issue tracker, if you want to discuss it further feel free to join our slack channel:
https://torchgeometricco.slack.com/join/shared_invite/zt-hn9vter8-EQn4L4wLfE7PZEYbLMlw~Q#/
