### ISSUE TITLE
torch points kernels version

### ISSUE THREAD

**Issue by pvnieo** [nicolas-chaulet/torch-points3d#418]
Hi!

I'm using `torch-points3d` with `torch-points-kernels` version 1.0.1, however `torch-points3d` requires version 0.7.0 max. Would that be a problem?

Thank you in advance!

**Comment by nicolas-chaulet** [comment]
Not sure how this is possible, it seems that we are still only at version 0.6.8:
https://pypi.org/project/torch-points-kernels/0.6.8/#history

You might mistake the version number with `torch-points3d` version number.
