### ISSUE TITLE
Print average accuracy over epochs in Notebook-ObjectClassificationRSConv

### ISSUE THREAD

**Issue by shangguan9191** [nicolas-chaulet/torch-points3d#421]
In the notebook, tracker is used for capturing the result. How can put the test accuracy into list, so i can sum and divide number of epochs

**Comment by nicolas-chaulet** [comment]
We compute the accuracy at each epoch. You can always aggregate each accuracy value yourself outside the tracker and do what you want to do.
Closing for now.
