### ISSUE TITLE
FastBatchNorm1d squeezes tensors to 1D for 2D tensors

### ISSUE THREAD

**Issue by Wundersam** [nicolas-chaulet/torch-points3d#428]
Hi,
I think I stumbled upon some unwanted behavior.
If [FastBatchNorm1d's](https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/core/common_modules/base_modules.py)  `_forward_sparse` receives a [N, 1] tensor, it gets squeezed into a [N] tensor before returning.
This causes problems for a KPConv forward pass if the feature tensor has size 1 in the second dimension.

If wanted, I can open a pull request that changes the responsible line.

**Comment by tchaton** [comment]
Dear @Wundersam ,

Please, open a PR for it 👍 

Best regards,
TC
