### ISSUE TITLE
how to test the trained model on test set?

### ISSUE THREAD

**Issue by DiegoWangSys** [nicolas-chaulet/torch-points3d#433]
Thanks for your excellent work! I have trained KPConvPaper model on Scannet, but how could I test the .pt model and get the label file(scene00707_00.txt)?

**Comment by nicolas-chaulet** [comment]
Hi,
You can use the eval.py script for that. First you will ahve to edit the eval.yaml:
https://github.com/nicolas-chaulet/torch-points3d/blob/dfa4e26eccfd8f589532097404e831f08595685a/conf/eval.yaml#L6
Change the directory to where the .pt file leaves

Then change the make_submission flag at that line to True:
https://github.com/nicolas-chaulet/torch-points3d/blob/dfa4e26eccfd8f589532097404e831f08595685a/conf/eval.yaml#L14

This will run through val and test set and generate the output files for the test set. They will be located under `<chekpoint_dir>/eval/<data_time>/`

I don't think we have tried that so let us know if you are facing some problems!

**Comment by DiegoWangSys** [comment]
Hi, thanks for your quick reply. I did what you said, and I guess maybe the "eval.yaml" is not complete, the "has_visialization" seems to be needed in "eval.yaml" 
but I commit the 251~252 in /torch_point3d/trainer.py to ignore the visualization function
and it seems good for prediction

**Comment by nicolas-chaulet** [comment]
Yes good point, I have just merged a PR that fixes that.
