### ISSUE TITLE
Docker OSError: [Errno 9] Bad file descriptord

### ISSUE THREAD

**Issue by qshzh** [nicolas-chaulet/torch-points3d#443]
Hello, I am using the torch-point3d inside docker. However, I encounter the following error complains
```shell
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 230, in _feed
    close()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 177, in close
    self._close()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 361, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 230, in _feed
    close()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 177, in close
    self._close()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 361, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
```
How to reproduce:
```shell
docker run --gpus all --rm -it principialabs/torch-points3d bash
python3 train.py  \
    task=segmentation model_type=pointnet2 model_name=pointnet2_charlesssg dataset=shapenet-fixed
```
[wandb project](https://wandb.ai/qinsheng/default/runs/2qztnxmj/overview?workspace=user-qinsheng_) record the details of experiments.

**Comment by qshzh** [comment]
The problem also happens when I run the latest code from github repo, not only the original code contained in the docker image.

**Comment by nicolas-chaulet** [comment]
Looks like you are running out of memory:
```
RuntimeError: DataLoader worker (pid 8161) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit. 
```
See this issue for example: https://github.com/pytorch/pytorch/issues/2244

And it's normal the code on master gives the same, it is the same code as in the docker image :)

**Comment by qshzh** [comment]
Hi nicolas, thanks for your reply and help. 

I noticed the memory issue and added the space of shared memory (64G should be enough for the tutorial example). However, I am not sure that it is the reason that causes the error complain. The error exists before the run out of memory and there is another run([wandb log](https://wandb.ai/qinsheng/default/runs/2rias7ts/logs?workspace=user-qinsheng)), which finishes the example but also reporting  `OSError: [Errno 9] Bad file descriptord` all the time.

From the Traceback, I guessed it is the issue caused by `torch.utils.data.DataLoader`. Then I set the `num_workers=0`. In this case, there is no error and the training time is much faster. (40min vs 1.2 min). [log](https://wandb.ai/qinsheng/default/runs/3drjb3mz/logs?workspace=) .  But I do not know how to debug when `num_workers>0`.

**Comment by nicolas-chaulet** [comment]
This is really strange... Not sure it has anything to do with torch points though, looks more like an issue with the data loader from PyTorch. What happens when you change "Cap" for Airplane"? Could be related to really small datasets somehow

**Comment by CCInc** [comment]
@qshzh you may want to try running with `--ipc=host`. docker limits the shared memory space which pytorch dataloader utilizes (https://github.com/pytorch/pytorch#docker-image)

**Comment by qshzh** [comment]
@CCInc  Thanks for your suggestion. In my  previous experiments, I used the `--shm` to increase the space. I try the `--ipc=host` does it shows the same results and error complains as `--shm`.
@nicolas-chaulet  Yes, it seems not a issue of torch points.  Nothing wrong happens with the simple `num_workers=0`. I try Airplane data, it shows another error
```shell
Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f9ef35270b8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1101, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
```
But I do not have the issue with `s3dis`.

**Comment by nicolas-chaulet** [comment]
Hey, other people have reported this issue (see #452 for example) really no idea what's causing it though... Let us know if you find another solution than setting the number of workers to 0

**Comment by uniwuppes** [comment]
I have the exact same issue.

**Comment by kenomo** [comment]
I am facing the same issue, but not in a Docker container, using torch-points3d:1.1.1. Setting num_workers: 1 "fixed" it.

**Comment by Sheldonmao** [comment]
I have exactly the same issue.  There's also another ValueError relates to it.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/points3d/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/anaconda3/envs/points3d/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/anaconda3/envs/points3d/lib/python3.7/multiprocessing/queues.py", line 263, in _feed
    queue_sem.release()
ValueError: semaphore or lock released too many times
```

However, in spite of keep throwing out errors, the code seems to proceed anyway.

**Comment by warlock8hz** [comment]
Came across the same problem. 

Setting num_workers: 1 "fixed" it. Still errors (ValueError: semaphore or lock released too many times) but can get a result. 

But I still want to say thank you for the excellent job @nicolas-chaulet

**Comment by nicolas-chaulet** [comment]
To be honest, I have the same error as well from time to time and no idea where it comes from or how to fix it...

**Comment by nicolas-chaulet** [comment]
Can

**Comment by yangninghua** [comment]
torch-points3d-1.2.0/conf/training/default.yaml

```
num_workers: 0

......

wandb:
    entity: ""
    project: default
    log: False
    notes:
    name:
    public: True # It will be display the model within wandb log, else not.
    config:
        model_name: ${model_name}
```
