### ISSUE TITLE
how to cite your repo as acknowledgement in my master thesis?

### ISSUE THREAD

**Issue by shangguan9191** [nicolas-chaulet/torch-points3d#445]
Dear author,

i reimplement your code for classification problem.
do you know the way to cite your work for paper? should I include in reference or acknowledgment?

**Comment by nicolas-chaulet** [comment]
Hi @shangguan9191, thanks for asking, you can use the repo as a reference for now, or we will have a published paper in the coming month.
@misc{
  tp3d,
  author = {Chaton, T. and Chaulet N.},
  title = {Torch Points3D}, year = {2020},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/nicolas-chaulet/torch-points3d}}
}

**Comment by nicolas-chaulet** [comment]
Hey! We've just updated the bibtex, could you please use:
```
@inproceedings{
  tp3d,
  title={Torch-Points3D: A Modular Multi-Task Frameworkfor Reproducible Deep Learning on 3D Point Clouds},
  author={Chaton, Thomas and Chaulet Nicolas and Horache, Sofiane and Landrieu, Loic},
  booktitle={2020 International Conference on 3D Vision (3DV)},
  year={2020},
  organization={IEEE}
  url = {\url{https://github.com/nicolas-chaulet/torch-points3d}}
}
```
