### ISSUE TITLE
About RandLANet implementation

### ISSUE THREAD

**Issue by a18700** [nicolas-chaulet/torch-points3d#453]
Hello, first, thanks for the amazing work.

But, I found out that the implementation of RandLANet is currently unavailable, thereby, I wonder if there exists any plan for it.

Thank you again.

**Comment by nicolas-chaulet** [comment]
Hi! We haven't really put too much efforts into RandLA-Net, our main reason is that it does not seem to bring significanta dvantages compared to something like  PPNet and arguably PN++

**Comment by a18700** [comment]
But, in contrast to PPNet, RandLA-Net can handle the large-sized ( >10^6 ) points, right?

And second, is the randla module, not the backbone, is released, but i'm not sure it's the complete implementation. Is it same as original implementation?

Thank you very much.

**Comment by nicolas-chaulet** [comment]
Hey, you are right our current implementation is not complete. As to the scalability I have to say that I am sceptical. The switch between fps and random sampling does not solve memory issues that we have seen with such point based methods (they take a lot of GPU memory).
