### ISSUE TITLE
Error with torch_cluster

### ISSUE THREAD

**Issue by luciaL** [nicolas-chaulet/torch-points3d#457]
Thank you for your hard work.

I installed torch_geometric first and work well first. 
Then I installed torch-point3d and when I import torch-point3d, error happed:
OSError: /home//anaconda3/envs/pytorch160/lib/python3.6/site-packages/torch_cluster/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
When I import torch_geometric the same error happed:
OSError: /home/anaconda3/envs/pytorch160/lib/python3.6/site-packages/torch_cluster/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

I guess there is some mismatch between different versions of torch_cluster.

here is the version detail:

Successfully installed Click-7.1.2 GitPython-3.1.9 configparser-5.0.1 docker-pycreds-0.4.0 gitdb-4.0.5 gql-0.2.0 graphql-core-1.1 hydra-core-0.11.3 jsonpatch-1.26 jsonpo0.32.1 numba-0.49.1 nvidia-ml-py3-7.352.0 omegaconf-1.4.1 pathtools-0.1.2 plyfile-0.7.2 promise-2.3 psutil-5.7.2 pytorch-metric-learning-0.9.94.dev0 pyzmq-19.0.2 scikit--sdk-0.18.0 shortuuid-1.0.1 smmap-3.0.4 subprocess32-3.5.4 torch-cluster-1.5.5 torch-points-kernels-0.6.8 torch-points3d-1.1.1 torchfile-0.1.0 torchnet-0.0.4 tornado-6.0andb-0.8.36 watchdog-0.10.3 websocket-client-0.57.0

**Comment by luciaL** [comment]
The version of torch-cluster in torch-geometric is the latest(1.5.7) and here is 15.5.

**Comment by nicolas-chaulet** [comment]
Hi @luciaL this very much look like you ahve updated pytorch after installing torch_cluster. Please follow those steps to uninstall and force recompilation of the relevant packages against the latest pytorch:
https://github.com/nicolas-chaulet/torch-points3d#undefined-symbol--updating-pytorch

Let me know if that does not work

**Comment by nicolas-chaulet** [comment]
Stale for some time, closing now
