### ISSUE TITLE
can not setup the repo using poetry command

### ISSUE THREAD

**Issue by PointCloudYC** [nicolas-chaulet/torch-points3d#462]
Hi! A very interesting repo for point cloud analysis using deep learning models. Thanks for your efforts.

**When I set up this repo, an error occurred. Below is what I have done:**
- clone this repo
- install the poetry using `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python`
- then run the command `poetry install --no-root`, an error occurred. 

```
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

  SolverProblemError

  Because torch-points3d depends on open3d (0.10.0.0) which doesn't match any versions, version solving failed.

  at ~/.local/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

P.S.: based on the error message "Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.", I tried the solution based on https://github.com/python-poetry/poetry/issues/1614, but still in vain.

Looking forward to your prompt reply.

**Comment by nicolas-chaulet** [comment]
Could you try poetry update?

**Comment by zetyquickly** [comment]
I have the same error. Tried the poetry update.
Also tried `poetry` command with open3d installed with pip

**Comment by nicolas-chaulet** [comment]
Hey, could you try again with the latest master? I just ran it without troubles here

**Comment by nicolas-chaulet** [comment]
Closing for now as it should be resolved.
