### ISSUE TITLE
Error trying to run demo_registration_3dm.ipynb

### ISSUE THREAD

**Issue by cartacamilla** [nicolas-chaulet/torch-points3d#465]
Hello! Thank you for this repo, seems very interesting.

I'm trying to run your registration example, and I encoutered this error while loading the pretrained model:

`Error trying to create train_transform, [{'transform': 'SaveOriginalPosId'}, {'transform': 'FixedPoints', 'lparams': [20000]}, {'transform': 'RandomNoise', 'params': {'sigma': 0.005, 'clip': 0.05}}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 0}}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 1}}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 2}}, {'transform': 'RandomScaleAnisotropic', 'params': {'scales': [0.9, 1.2]}}, {'transform': 'XYZFeature', 'params': {'add_x': True, 'add_y': True, 'add_z': True}}, {'transform': 'GridSampling', 'params': {'size': '${data.first_subsampling}', 'quantize_coords': True, 'mode': 'last'}}, {'transform': 'AddOnes'}, {'transform': 'AddFeatByKey', 'params': {'add_to_x': True, 'feat_name': 'ones'}}, {'transform': 'Jitter'}]
Traceback (most recent call last):
  File "/home/ccarta/.virtualenvs/point3d/lib/python3.6/site-packages/torch_points3d/datasets/base_dataset.py", line 125, in set_transform
    transform = instantiate_transforms(getattr(dataset_opt, key_name))
  File "/home/ccarta/.virtualenvs/point3d/lib/python3.6/site-packages/torch_points3d/core/data_transform/__init__.py", line 86, in instantiate_transforms
    transforms.append(instantiate_transform(transform))
  File "/home/ccarta/.virtualenvs/point3d/lib/python3.6/site-packages/torch_points3d/core/data_transform/__init__.py", line 69, in instantiate_transform
    return cls(**tr_params)
TypeError: __init__() got an unexpected keyword argument 'quantize_coords'
Error trying to create test_transform, [{'transform': 'SaveOriginalPosId'}, {'transform': 'FixedPoints', 'lparams': [20000]}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 0}}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 1}}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 2}}, {'transform': 'XYZFeature', 'params': {'add_x': True, 'add_y': True, 'add_z': True}}, {'transform': 'GridSampling', 'params': {'size': '${data.first_subsampling}', 'quantize_coords': True, 'mode': 'last'}}, {'transform': 'AddOnes'}, {'transform': 'AddFeatByKey', 'params': {'add_to_x': True, 'feat_name': 'ones'}}]
Traceback (most recent call last):
  File "/home/ccarta/.virtualenvs/point3d/lib/python3.6/site-packages/torch_points3d/datasets/base_dataset.py", line 125, in set_transform
    transform = instantiate_transforms(getattr(dataset_opt, key_name))
  File "/home/ccarta/.virtualenvs/point3d/lib/python3.6/site-packages/torch_points3d/core/data_transform/__init__.py", line 86, in instantiate_transforms
    transforms.append(instantiate_transform(transform))
  File "/home/ccarta/.virtualenvs/point3d/lib/python3.6/site-packages/torch_points3d/core/data_transform/__init__.py", line 69, in instantiate_transform
    return cls(**tr_params)
TypeError: __init__() got an unexpected keyword argument 'quantize_coords'
` 

Do you have any pointers for me as to what is wrong? I'm running pytorch==1.6.0 for cuda=10.1 and python=3.6
Thanks!

**Comment by humanpose1** [comment]
Hi, thank you for your interest in the framework.
This error is due to the fact that it didn't save the right transformations (we have updated the transforms). But, normally the model is working, you can use the model to compute features and registrate scene (tell me if it's not the case).
Maybe I will retrain the model not to have the error.

**Comment by cartacamilla** [comment]
Thank you for your reply.
For now I have patched the error with: 
```python
try:
    model = PretainedRegistry.from_pretrained("minkowski-registration-3dmatch").cuda()
except TypeError:
    pass
```
and the model seems to work, as you said, so I'll close this. I might suggest you add a line in the README to direct other people that could have the same issue?

Have a nice day!

**Comment by humanpose1** [comment]
Thank you for your suggestion !!
