### ISSUE TITLE
typo error in README

### ISSUE THREAD

**Issue by Leerw** [nicolas-chaulet/torch-points3d#467]
@inproceedings{
  tp3d,
  title={Torch-Points3D: A Modular Multi-Task Frameworkfor Reproducible Deep Learning on 3D Point Clouds},
  author={Chaton, Thomas and Chaulet Nicolas and Horache, Sofiane and Landrieu, Loic},
  booktitle={2020 International Conference on 3D Vision (3DV)},
  year={2020},
  organization={IEEE}
  url = {\url{https://github.com/nicolas-chaulet/torch-points3d}},
}

there should be a comma after organization={IEEE}

**Comment by nicolas-chaulet** [comment]
Thanks! COrrecting that now
