### ISSUE TITLE
Use KPConv on another dataset

### ISSUE THREAD

**Issue by jdolbecq** [nicolas-chaulet/torch-points3d#471]
Hi! 

I want to train a KPConv network on a dataset that is not implemented in your framwork (in this case, the DALES dataset made of aerial LiDAR data).

I'm a bit confused about the framwork classes I need to implement and/or modify. Could you give me any advice? Do I have to implement torch_geometric/datasets/dales.py and torch_points3d.datasets/segmentation/dales.py ?

**Comment by nicolas-chaulet** [comment]
Hey,
You need to add two files:
```
torch_points3d/datasets/segmentation/dales.py
```
and 
```
conf/data/segmentation/dales.yaml
```
The `dales.py` will contain the logic of your raw dataset `Dales` that should probably inherit from the `torch_geometric` `InMemory` dataset but does not have to, it could just be a raw pytorch dataset. Once this is in place you need to wrap that dataset into a  class that inherits from TP3d `BaseDataset` class and that basically handles the logic of building data loaders, creating the data transforms based on the `yaml` file and other bits and bobs. You can take a look at [SemanticKitti](https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/datasets/segmentation/semantickitti.py) that is quite basic.

**Comment by jdolbecq** [comment]
Hi, 
Thank you for your answer, it's clearer for me now.
