### ISSUE TITLE
How to use KPCONV as a encoder?

### ISSUE THREAD

**Issue by Yellowshuohahaha** [nicolas-chaulet/torch-points3d#472]
Hi,
   I want to use KPCONV as encoder in the input point cloud  to produce a 1024 dims feature vector. But I have no idea about using t3d to do it. Can you give me some advices? Thanks.

**Comment by nicolas-chaulet** [comment]
Hey,
Yes, of course! This notebook should be a good place to start in terms of how to use KPConv as a backbone network. The example covers an encoder/decoder but it is very similar for a simple encoder. You can use the API to do that first create a the encoder:
```
from torch_points3d.applications.kpconv import KPConv
encoder = KPConv(
            architecture="encoder", 
            input_nc= <number of features>, 
            num_layers=4, 
            in_grid_size=0.02
            )
```
You can access the output size of the encoder like that:
```
encoderoutput = encoder.output_nc
```
Then you can take the output of the encoder and run it through a linear layer to get the 1024 size you want.
Does that help? Also, don't hesitate to join our Slack channel if you need more help!
