### ISSUE TITLE
Questions about forwarding

### ISSUE THREAD

**Issue by lwx-bupt** [nicolas-chaulet/torch-points3d#473]
Hi,
I've trained a (modified) KPConv model on S3DISFused dataset for semantic segmentation, and I 've got some unannotated point cloud files (*.ply). Now I need to perform a forwarding on the model with the point cloud as input to make the prediction.
P.S. My code is based on v1.0.1 release of this repo, which runs normally with pytorch 1.4.0 on my machine
Questions:
1. Do I need to convert the files to another format like *.txt?
2. How should I arrange the input data?
3. What need to be modified in forward.py and config.yaml files?
Could anybody give me some information on that? I'd really appreciate your help

Updated 2020/10/23 22:15PM
I think I need to modify the run() method to feed the 'data' parameter in:
model.set_input (data, device)
Hope it goes well~

**Comment by harry1576** [comment]
Did you have any luck? 
Could you please share?
