### ISSUE TITLE
Google Colab - ModuleNotFoundError: No module named 'torch_points3d'

### ISSUE THREAD

**Issue by albertotono** [nicolas-chaulet/torch-points3d#474]
Hi @nicolas-chaulet , 

I am running this https://colab.research.google.com/github/nicolas-chaulet/torch-points3d/blob/master/notebooks/PartSegmentationKPConv.ipynb#scrollTo=eQFRmfUYzXX1 directly in Google Colab, 

but I installed torch_points3d like this 

`!pip install torch_points3d`

```
# The first time you run this cell, it will download the dataset 
from torch_points3d.datasets.segmentation import ShapeNetDataset
dataset = ShapeNetDataset(params)
dataset
```

I am getting this message

```
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-23-762064fa17b9> in <module>()
      1 # The first time you run this cell, it will download the dataset
----> 2 from torch_points3d.datasets.segmentation import shapenet
      3 dataset = ShapeNetDataset(params)
      4 dataset

**ModuleNotFoundError: No module named 'torch_points3d'**
```
Any help?

**Comment by nicolas-chaulet** [comment]
Hey @albertotono, thanks for trying the notebook! I just ran the notebook from the beginning again and everything seems to work just fine. The install step takes ages due to the number of libraries that need to be installed if you run it on colab but once it's done all works well. Could you try again?

**Comment by albertotono** [comment]
Thanks, I rerun the code and everything works perfectly now, thanks again

**Comment by albertotono** [comment]
Sorry @nicolas-chaulet  I am having the issue when I run it locally now. Not sure why.
