### ISSUE TITLE
 CUDA out of memory

### ISSUE THREAD

**Issue by jianguoYao** [nicolas-chaulet/torch-points3d#479]
Do you meet this question ,how do it

**Comment by nicolas-chaulet** [comment]
Could you please clarify? Out of memory is usually because you use a batch size that is too large. Try reducing it.

**Comment by jianguoYao** [comment]
> Could you please clarify? Out of memory is usually because you use a batch size that is too large. Try reducing it.
yes，i did. but a epoch,when i run pointnet2 of s3dis, it's too slow.
