### ISSUE TITLE
Training with Shapenet, tensor size are not equal

### ISSUE THREAD

**Issue by molnarszilard** [nicolas-chaulet/torch-points3d#485]
Hi, I was able to train a pointnet2 model a couple of days ago for the shapenet dataset. But yesterday I have updated to the latest commits and since I am getting the following error:
RuntimeError: stack expects each tensor to be equal size, but got [2270, 3] at entry 0 and [2699, 3] at entry 1

The full log is:
python train.py task=segmentation model_type=pointnet2 model_name=pointnet2_charlesssg dataset=shapenet
DEVICE : cuda
wandb: Tracking run with wandb version 0.8.36
wandb: Wandb version 0.10.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Run data is saved locally in wandb/run-20201029_115602-2adwx5ce
wandb: Syncing run solar-butterfly-65
wandb: ⭐ View project at https://app.wandb.ai/molnarszilard/default
wandb: 🚀 View run at https://app.wandb.ai/molnarszilard/default/runs/2adwx5ce
wandb: Run `wandb off` to turn off syncing.

Using category information for the predictions with 16 categories
Setting batchnorm momentum at 0.1
Using category information for the predictions with 16 categories
PointNet2_D(
  (model): UnetSkipConnectionBlock(
    (down): PointNetMSGDown(
      (mlps): ModuleList(
        (0): MLP2D(
          (0): Conv2D(
            (0): Conv2d(6, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
          (1): Conv2D(
            (0): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
          (2): Conv2D(
            (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
        )
      )
    )
    (submodule): UnetSkipConnectionBlock(
      (down): PointNetMSGDown(
        (mlps): ModuleList(
          (0): MLP2D(
            (0): Conv2D(
              (0): Conv2d(131, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (1): Conv2D(
              (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (2): Conv2D(
              (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
          )
        )
      )
      (submodule): UnetSkipConnectionBlock(
        (inner): GlobalDenseBaseModule: 725248 (aggr=max, MLP2D(
          (0): Conv2D(
            (0): Conv2d(259, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
          (1): Conv2D(
            (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
          (2): Conv2D(
            (0): Conv2d(512, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
        ))
        (up): DenseFPModule: 394240 (MLP2D(
          (0): Conv2D(
            (0): Conv2d(1280, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
          (1): Conv2D(
            (0): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
        ))
      )
      (up): DenseFPModule: 131840 (MLP2D(
        (0): Conv2D(
          (0): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
    )
    (up): DenseFPModule: 50304 (MLP2D(
      (0): Conv2D(
        (0): Conv2d(131, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): LeakyReLU(negative_slope=0.01)
      )
      (1): Conv2D(
        (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): LeakyReLU(negative_slope=0.01)
      )
      (2): Conv2D(
        (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): LeakyReLU(negative_slope=0.01)
      )
    ))
  )
  (FC_layer): Seq(
    (0): Conv1D(
      (0): Conv1d(144, 128, kernel_size=(1,), stride=(1,), bias=False)
      (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): LeakyReLU(negative_slope=0.01)
    )
    (1): Dropout(p=0.5, inplace=False)
    (2): Conv1D(
      (0): Conv1d(128, 50, kernel_size=(1,), stride=(1,))
    )
  )
)
Optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    initial_lr: 0.001
    lr: 0.001
    weight_decay: 0
)
Learning Rate Scheduler: ExponentialLR({'gamma': 0.9885}, update_scheduler_on=on_epoch)
BatchNorm Scheduler: BNMomentumScheduler(base_momentum: 0.1, update_scheduler_on=on_epoch)
Accumulated gradients: None
Model size = 1406898
Dataset: ShapeNetDataset 
train_pre_batch_collate_transform = None
val_pre_batch_collate_transform = None
test_pre_batch_collate_transform = None
pre_transform = Compose([
    NormalizeScale(),
    GridSampling3D(grid_size=0.02, quantize_coords=False, mode=mean),
])
test_transform = None
train_transform = Compose([
    RandomNoise(sigma=0.01, clip=0.05),
    RandomScaleAnisotropic([0.9, 1.1]),
])
val_transform = None
inference_transform = Compose([
    NormalizeScale(),
    GridSampling3D(grid_size=0.02, quantize_coords=False, mode=mean),
])
Size of train_dataset = 12137
Size of test_dataset = 2874
Size of val_dataset = 1870
Batch size = 16
Available stage selection datasets:  ['test', 'val'] 
The models will be selected using the metrics on following dataset:  val 
Access tensorboard with the following command <tensorboard --logdir=/home/cuda/torch-points3d/outputs/2020-10-29/13-56-02/tensorboard>
EPOCH 1 / 100
  0%|                                                                                                                                                                               | 0/759 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    main()
  File "/home/cuda/.local/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/cuda/.local/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/cuda/.local/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/cuda/.local/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 15, in main
    trainer.train()
  File "/home/cuda/torch-points3d/torch_points3d/trainer.py", line 143, in train
    self._train_epoch(epoch)
  File "/home/cuda/torch-points3d/torch_points3d/trainer.py", line 193, in _train_epoch
    for i, data in enumerate(tq_train_loader):
  File "/home/cuda/.local/lib/python3.6/site-packages/tqdm/std.py", line 1165, in __iter__
    for obj in iterable:
  File "/home/cuda/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/cuda/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/cuda/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/cuda/.local/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cuda/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cuda/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/cuda/torch-points3d/torch_points3d/datasets/base_dataset.py", line 160, in _collate_fn
    return col
wandb: Waiting for W&B process to finish, PID 13841
late_fn(batch)
  File "/home/cuda/torch-points3d/torch_points3d/datasets/batch.py", line 48, in from_data_list
    batch[key] = torch.stack(batch[key])
RuntimeError: stack expects each tensor to be equal size, but got [2270, 3] at entry 0 and [2699, 3] at entry 1

wandb: Program failed with code 1. Press ctrl-c to abort syncing.
wandb: Process crashed early, not syncing files

**Comment by nicolas-chaulet** [comment]
Yes, that's normal. Each sample in the batch need to have the same size for PN++. Therefore you need to apply a FixedPoints transform in you data transforms. use `hapenet-fixed` instead of `shapenet` and it should work straight away.

**Comment by molnarszilard** [comment]
Thank you. It solved my problem.
