### ISSUE TITLE
Training with Scannet,TypeError: expected Tensor as element 0 in argument 0, but got float

### ISSUE THREAD

**Issue by daili650** [nicolas-chaulet/torch-points3d#488]
Hi, I try to train a votenet model for the scannet dataset， but I am getting the following error:
TypeError: expected Tensor as element 0 in argument 0, but got float
The full log is:
python train.py task=object_detection model_type=votenet dataset=scannet-fixed model_name=VoteNetPaper training=votenet
DEVICE : cuda
The config will be used to build the model
Setting batchnorm momentum at 0.5
The config will be used to build the model
VoteNetModel(
  (backbone_model): PointNet2Unet(
    (down_modules): ModuleList(
      (0): PointNetMSGDown(
        (mlps): ModuleList(
          (0): MLP2D(
            (0): Conv2D(
              (0): Conv2d(3, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(64, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (1): Conv2D(
              (0): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(64, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (2): Conv2D(
              (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
          )
        )
      )
      (1): PointNetMSGDown(
        (mlps): ModuleList(
          (0): MLP2D(
            (0): Conv2D(
              (0): Conv2d(131, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (1): Conv2D(
              (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (2): Conv2D(
              (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
          )
        )
      )
      (2): PointNetMSGDown(
        (mlps): ModuleList(
          (0): MLP2D(
            (0): Conv2D(
              (0): Conv2d(259, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (1): Conv2D(
              (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (2): Conv2D(
              (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
          )
        )
      )
      (3): PointNetMSGDown(
        (mlps): ModuleList(
          (0): MLP2D(
            (0): Conv2D(
              (0): Conv2d(259, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (1): Conv2D(
              (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (2): Conv2D(
              (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
          )
        )
      )
    )
    (inner_modules): ModuleList(
      (0): Identity()
    )
    (up_modules): ModuleList(
      (0): DenseFPModule: 197632 (MLP2D(
        (0): Conv2D(
          (0): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
      (1): DenseFPModule: 197632 (MLP2D(
        (0): Conv2D(
          (0): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
    )
  )
  (voting_module): VotingModule(
    (conv1): Conv1d(256, 256, kernel_size=(1,), stride=(1,))
    (conv2): Conv1d(256, 256, kernel_size=(1,), stride=(1,))
    (conv3): Conv1d(256, 259, kernel_size=(1,), stride=(1,))
    (bn1): BatchNorm1d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
    (bn2): BatchNorm1d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
  )
  (proposal_cls_module): ProposalModule(
    (vote_aggregation): PointNetMSGDown(
      (mlps): ModuleList(
        (0): MLP2D(
          (0): Conv2D(
            (0): Conv2d(259, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
          (1): Conv2D(
            (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
          (2): Conv2D(
            (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
        )
      )
    )
    (conv1): Conv1d(128, 128, kernel_size=(1,), stride=(1,))
    (conv2): Conv1d(128, 113, kernel_size=(1,), stride=(1,))
    (conv3): Conv1d(113, 99, kernel_size=(1,), stride=(1,))
    (bn1): BatchNorm1d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
    (bn2): BatchNorm1d(113, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
  )
)
Optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    initial_lr: 0.001
    lr: 0.001
    weight_decay: 0
)
Learning Rate Scheduler: ExponentialLR({'gamma': 0.9885}, update_scheduler_on=on_epoch)
BatchNorm Scheduler: BNMomentumScheduler(base_momentum: 0.5, update_scheduler_on=on_epoch)
Accumulated gradients: None
Model size = 950572
Dataset: ScannetDataset 
pre_transform = Compose([
    GridSampling3D(grid_size=0.02, quantize_coords=False, mode=mean),
])
test_transform = None
train_transform = Compose([
    GridSampling3D(grid_size=0.05, quantize_coords=False, mode=mean),
    FixedPoints(50000, replace=True),
    RandomNoise(sigma=0.01, clip=0.05),
    RandomScaleAnisotropic([0.9, 1.1]),
    Random symmetry of axes: x=True, y=False, z=False,
    Random3AxisRotation(apply_rotation=True, rot_x=2, rot_y=2, rot_z=180),
])
val_transform = Compose([
    GridSampling3D(grid_size=0.05, quantize_coords=False, mode=mean),
    FixedPoints(50000, replace=True),
])
inference_transform = Compose([
    GridSampling3D(grid_size=0.02, quantize_coords=False, mode=mean),
])
Size of train_dataset = 1201
Size of test_dataset = 0
Size of val_dataset = 312
Batch size = 2
Available stage selection datasets:  ['val'] 
The models will be selected using the metrics on following dataset:  val 
Access tensorboard with the following command <tensorboard --logdir=/media/MD/torch-points3d/outputs/2020-10-30/22-45-06/tensorboard>
EPOCH 1 / 200
  0%|          | 0/601 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/media/MD/torch-points3d/train.py", line 21, in <module>
    main()
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "/media/MD/torch-points3d/train.py", line 13, in main
    trainer.train()
  File "/media/MD/torch-points3d/torch_points3d/trainer.py", line 140, in train
    self._train_epoch(epoch)
  File "/media/MD/torch-points3d/torch_points3d/trainer.py", line 190, in _train_epoch
    for i, data in enumerate(tq_train_loader):
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/media/MD/torch-points3d/torch_points3d/datasets/batch.py", line 51, in from_data_list
    batch[key] = torch.stack(batch[key])
TypeError: expected Tensor as element 0 in argument 0, but got float

Process finished with exit code 1

**Comment by nicolas-chaulet** [comment]
Nice one, it is a bug. It should be fixed by #489

**Comment by nicolas-chaulet** [comment]
@daili650 it should be fixed on master now! Let us know if you still have troubles

**Comment by daili650** [comment]
Thank you. It solved my problem.
