### ISSUE TITLE
mAP

### ISSUE THREAD

**Issue by daili650** [nicolas-chaulet/torch-points3d#492]
Hi，I have a question.Is there any mAP calculation about VoteNet in this code?

**Comment by nicolas-chaulet** [comment]
Yes there is! The object detection tracker tracks mAP:
https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/metrics/object_detection_tracker.py

**Comment by daili650** [comment]
I  tell the path and model name  correctly in the eval file, but the result doesn't show the map.
This is the full log.
/home/daili/anaconda3/envs/votenet/bin/python3.6 /home/daili/media/MD/torch-points3d/eval.py
batch_size: 1
checkpoint_dir: /home/daili/media/MD/torch-points3d/outputs/2020-11-07/23-32-48
cuda: 0
enable_cudnn: true
enable_dropout: false
model_name: VoteNetPN2
num_workers: 1
precompute_multi_scale: true
tracker_options:
  full_res: true
  make_submission: true
voting_runs: 1
weight_name: latest

[2020-11-12 16:47:25,753][torch_points3d.trainer][INFO] - DEVICE : cuda
[2020-11-12 16:47:25,753][torch_points3d.metrics.model_checkpoint][INFO] - Loading checkpoint from /home/daili/media/MD/torch-points3d/outputs/2020-11-07/23-32-48/VoteNetPN2.pt
[2020-11-12 16:50:24,779][torch_points3d.metrics.model_checkpoint][INFO] - Available weights : ['latest', 'vote_loss', 'objectness_loss', 'center_loss', 'heading_reg_loss', 'size_cls_loss', 'size_reg_loss', 'sem_cls_loss', 'box_loss', 'loss', 'acc', 'pos', 'neg']
[2020-11-12 16:50:24,779][torch_points3d.metrics.model_checkpoint][INFO] - Model loaded from VoteNetPN2.pt:latest
[2020-11-12 16:50:24,794][torch_points3d.core.schedulers.bn_schedulers][INFO] - Setting batchnorm momentum at 0.5
[2020-11-12 16:50:24,800][torch_points3d.trainer][INFO] - VoteNet2(
  (backbone_model): PointNet2Unet(
    (down_modules): ModuleList(
      (0): PointNetMSGDown(
        (mlps): ModuleList(
          (0): MLP2D(
            (0): Conv2D(
              (0): Conv2d(3, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(64, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (1): Conv2D(
              (0): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(64, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (2): Conv2D(
              (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
          )
        )
      )
      (1): PointNetMSGDown(
        (mlps): ModuleList(
          (0): MLP2D(
            (0): Conv2D(
              (0): Conv2d(131, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (1): Conv2D(
              (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (2): Conv2D(
              (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
          )
        )
      )
      (2): PointNetMSGDown(
        (mlps): ModuleList(
          (0): MLP2D(
            (0): Conv2D(
              (0): Conv2d(259, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (1): Conv2D(
              (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (2): Conv2D(
              (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
          )
        )
      )
    )
    (inner_modules): ModuleList(
      (0): GlobalDenseBaseModule: 659968 (aggr=max, MLP2D(
        (0): Conv2D(
          (0): Conv2d(259, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(512, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(1024, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
    )
    (up_modules): ModuleList(
      (0): DenseFPModule: 919552 (MLP2D(
        (0): Conv2D(
          (0): Conv2d(1280, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
      (1): DenseFPModule: 657408 (MLP2D(
        (0): Conv2D(
          (0): Conv2d(768, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
      (2): DenseFPModule: 230400 (MLP2D(
        (0): Conv2D(
          (0): Conv2d(640, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
      (3): DenseFPModule: 49664 (MLP2D(
        (0): Conv2D(
          (0): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
    )
  )
  (voting_module): VotingModule(
    (conv1): Conv1d(128, 128, kernel_size=(1,), stride=(1,))
    (conv2): Conv1d(128, 128, kernel_size=(1,), stride=(1,))
    (conv3): Conv1d(128, 131, kernel_size=(1,), stride=(1,))
    (bn1): BatchNorm1d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
    (bn2): BatchNorm1d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
  )
  (proposal_cls_module): ProposalModule(
    (vote_aggregation): PointNetMSGDown(
      (mlps): ModuleList(
        (0): MLP2D(
          (0): Conv2D(
            (0): Conv2d(131, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
          (1): Conv2D(
            (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
        )
      )
    )
    (conv1): Conv1d(128, 128, kernel_size=(1,), stride=(1,))
    (conv2): Conv1d(128, 112, kernel_size=(1,), stride=(1,))
    (conv3): Conv1d(112, 97, kernel_size=(1,), stride=(1,))
    (bn1): BatchNorm1d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
    (bn2): BatchNorm1d(112, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
  )
)
[2020-11-12 16:50:24,809][torch_points3d.utils.colors][INFO] - Optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    initial_lr: 0.001
    lr: 0.001
    weight_decay: 0
)
[2020-11-12 16:50:24,809][torch_points3d.utils.colors][INFO] - Learning Rate Scheduler: ExponentialLR({'gamma': 0.9885}, update_scheduler_on=on_epoch)
[2020-11-12 16:50:24,809][torch_points3d.utils.colors][INFO] - BatchNorm Scheduler: BNMomentumScheduler(base_momentum: 0.5, update_scheduler_on=on_epoch)
[2020-11-12 16:50:24,809][torch_points3d.utils.colors][INFO] - Accumulated gradients: None
[2020-11-12 16:50:24,810][torch_points3d.trainer][INFO] - Model size = 2806756
[2020-11-12 16:50:24,811][torch_points3d.trainer][INFO] - Dataset: ScannetDataset 
pre_transform = Compose([
    GridSampling3D(grid_size=0.02, quantize_coords=False, mode=mean),
])
test_transform = None
train_transform = Compose([
    GridSampling3D(grid_size=0.05, quantize_coords=False, mode=mean),
    FixedPoints(50000, replace=True),
    RandomNoise(sigma=0.01, clip=0.05),
    RandomScaleAnisotropic([0.9, 1.1]),
    Random symmetry of axes: x=True, y=False, z=False,
    Random3AxisRotation(apply_rotation=True, rot_x=2, rot_y=2, rot_z=180),
])
val_transform = Compose([
    GridSampling3D(grid_size=0.05, quantize_coords=False, mode=mean),
    FixedPoints(50000, replace=True),
])
inference_transform = Compose([
    GridSampling3D(grid_size=0.02, quantize_coords=False, mode=mean),
])
Size of train_dataset = 1201
Size of test_dataset = 0
Size of val_dataset = 312
Batch size = 1
[2020-11-12 16:50:25,346][torch_points3d.datasets.base_dataset][INFO] - Available stage selection datasets:  ['val'] 
[2020-11-12 16:50:25,346][torch_points3d.datasets.base_dataset][INFO] - The models will be selected using the metrics on following dataset:  None 
100%|██████████| 312/312 [01:25<00:00,  3.66it/s, val_acc=0.859, val_neg=0.535, val_pos=0.158)]
[2020-11-12 16:51:52,554][torch_points3d.metrics.base_tracker][INFO] - ==================================================
[2020-11-12 16:51:52,554][torch_points3d.metrics.base_tracker][INFO] -     val_acc = 0.8593992873992358
[2020-11-12 16:51:52,554][torch_points3d.metrics.base_tracker][INFO] -     val_pos = 0.1585286458333333
[2020-11-12 16:51:52,554][torch_points3d.metrics.base_tracker][INFO] -     val_neg = 0.5359074519230771
[2020-11-12 16:51:52,554][torch_points3d.metrics.base_tracker][INFO] - ==================================================

Process finished with exit code 0

**Comment by nicolas-chaulet** [comment]
Hey, yes you need to activate it explicitely by changing the eval.yaml and adding `track_boxes: True` in the `tracker_options` section

**Comment by daili650** [comment]
I do what you said,but still have some error.
/home/daili/anaconda3/envs/votenet/bin/python3.6 /home/daili/media/MD/torch-points3d/eval.py
batch_size: 1
checkpoint_dir: /home/daili/media/MD/torch-points3d/outputs/2020-11-07/23-32-48
cuda: 0
enable_cudnn: true
enable_dropout: false
model_name: VoteNetPN2
num_workers: 1
precompute_multi_scale: true
tracker_options:
  full_res: false
  make_submission: true
  track_boxes: true
voting_runs: 1
weight_name: latest

[2020-11-12 17:37:02,376][torch_points3d.trainer][INFO] - DEVICE : cuda
[2020-11-12 17:37:02,376][torch_points3d.metrics.model_checkpoint][INFO] - Loading checkpoint from /home/daili/media/MD/torch-points3d/outputs/2020-11-07/23-32-48/VoteNetPN2.pt
[2020-11-12 17:39:21,542][torch_points3d.metrics.model_checkpoint][INFO] - Available weights : ['latest', 'vote_loss', 'objectness_loss', 'center_loss', 'heading_reg_loss', 'size_cls_loss', 'size_reg_loss', 'sem_cls_loss', 'box_loss', 'loss', 'acc', 'pos', 'neg']
[2020-11-12 17:39:21,542][torch_points3d.metrics.model_checkpoint][INFO] - Model loaded from VoteNetPN2.pt:latest
[2020-11-12 17:39:21,547][torch_points3d.core.schedulers.bn_schedulers][INFO] - Setting batchnorm momentum at 0.5
[2020-11-12 17:39:21,577][torch_points3d.trainer][INFO] - VoteNet2(
  (backbone_model): PointNet2Unet(
    (down_modules): ModuleList(
      (0): PointNetMSGDown(
        (mlps): ModuleList(
          (0): MLP2D(
            (0): Conv2D(
              (0): Conv2d(3, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(64, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (1): Conv2D(
              (0): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(64, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (2): Conv2D(
              (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
          )
        )
      )
      (1): PointNetMSGDown(
        (mlps): ModuleList(
          (0): MLP2D(
            (0): Conv2D(
              (0): Conv2d(131, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (1): Conv2D(
              (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (2): Conv2D(
              (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
          )
        )
      )
      (2): PointNetMSGDown(
        (mlps): ModuleList(
          (0): MLP2D(
            (0): Conv2D(
              (0): Conv2d(259, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (1): Conv2D(
              (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
            (2): Conv2D(
              (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
              (2): LeakyReLU(negative_slope=0.01)
            )
          )
        )
      )
    )
    (inner_modules): ModuleList(
      (0): GlobalDenseBaseModule: 659968 (aggr=max, MLP2D(
        (0): Conv2D(
          (0): Conv2d(259, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(512, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(1024, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
    )
    (up_modules): ModuleList(
      (0): DenseFPModule: 919552 (MLP2D(
        (0): Conv2D(
          (0): Conv2d(1280, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
      (1): DenseFPModule: 657408 (MLP2D(
        (0): Conv2D(
          (0): Conv2d(768, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
      (2): DenseFPModule: 230400 (MLP2D(
        (0): Conv2D(
          (0): Conv2d(640, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
      (3): DenseFPModule: 49664 (MLP2D(
        (0): Conv2D(
          (0): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
        (1): Conv2D(
          (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
          (2): LeakyReLU(negative_slope=0.01)
        )
      ))
    )
  )
  (voting_module): VotingModule(
    (conv1): Conv1d(128, 128, kernel_size=(1,), stride=(1,))
    (conv2): Conv1d(128, 128, kernel_size=(1,), stride=(1,))
    (conv3): Conv1d(128, 131, kernel_size=(1,), stride=(1,))
    (bn1): BatchNorm1d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
    (bn2): BatchNorm1d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
  )
  (proposal_cls_module): ProposalModule(
    (vote_aggregation): PointNetMSGDown(
      (mlps): ModuleList(
        (0): MLP2D(
          (0): Conv2D(
            (0): Conv2d(131, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
          (1): Conv2D(
            (0): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
            (2): LeakyReLU(negative_slope=0.01)
          )
        )
      )
    )
    (conv1): Conv1d(128, 128, kernel_size=(1,), stride=(1,))
    (conv2): Conv1d(128, 112, kernel_size=(1,), stride=(1,))
    (conv3): Conv1d(112, 97, kernel_size=(1,), stride=(1,))
    (bn1): BatchNorm1d(128, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
    (bn2): BatchNorm1d(112, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
  )
)
[2020-11-12 17:39:21,579][torch_points3d.utils.colors][INFO] - Optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    initial_lr: 0.001
    lr: 0.001
    weight_decay: 0
)
[2020-11-12 17:39:21,579][torch_points3d.utils.colors][INFO] - Learning Rate Scheduler: ExponentialLR({'gamma': 0.9885}, update_scheduler_on=on_epoch)
[2020-11-12 17:39:21,579][torch_points3d.utils.colors][INFO] - BatchNorm Scheduler: BNMomentumScheduler(base_momentum: 0.5, update_scheduler_on=on_epoch)
[2020-11-12 17:39:21,579][torch_points3d.utils.colors][INFO] - Accumulated gradients: None
[2020-11-12 17:39:21,579][torch_points3d.trainer][INFO] - Model size = 2806756
[2020-11-12 17:39:21,579][torch_points3d.trainer][INFO] - Dataset: ScannetDataset 
pre_transform = Compose([
    GridSampling3D(grid_size=0.02, quantize_coords=False, mode=mean),
])
test_transform = None
train_transform = Compose([
    GridSampling3D(grid_size=0.05, quantize_coords=False, mode=mean),
    FixedPoints(50000, replace=True),
    RandomNoise(sigma=0.01, clip=0.05),
    RandomScaleAnisotropic([0.9, 1.1]),
    Random symmetry of axes: x=True, y=False, z=False,
    Random3AxisRotation(apply_rotation=True, rot_x=2, rot_y=2, rot_z=180),
])
val_transform = Compose([
    GridSampling3D(grid_size=0.05, quantize_coords=False, mode=mean),
    FixedPoints(50000, replace=True),
])
inference_transform = Compose([
    GridSampling3D(grid_size=0.02, quantize_coords=False, mode=mean),
])
Size of train_dataset = 1201
Size of test_dataset = 0
Size of val_dataset = 312
Batch size = 1
[2020-11-12 17:39:21,721][torch_points3d.datasets.base_dataset][INFO] - Available stage selection datasets:  ['val'] 
[2020-11-12 17:39:21,722][torch_points3d.datasets.base_dataset][INFO] - The models will be selected using the metrics on following dataset:  None 
  0%|          | 0/312 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/daili/media/MD/torch-points3d/eval.py", line 18, in <module>
    main()
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/daili/anaconda3/envs/votenet/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/daili/media/MD/torch-points3d/eval.py", line 12, in main
    trainer.eval()
  File "/home/daili/media/MD/torch-points3d/torch_points3d/trainer.py", line 165, in eval
    self._test_epoch(epoch, "val")
  File "/home/daili/media/MD/torch-points3d/torch_points3d/trainer.py", line 248, in _test_epoch
    self._tracker.track(self._model, data=data, **self.tracker_options)
  File "/home/daili/media/MD/torch-points3d/torch_points3d/metrics/object_detection_tracker.py", line 67, in track
    self._add_box_pred(outputs, data, model.conv_type)
  File "/home/daili/media/MD/torch-points3d/torch_points3d/metrics/object_detection_tracker.py", line 71, in _add_box_pred
    pred_boxes = outputs.get_boxes(self._dataset, apply_nms=True, duplicate_boxes=False)
  File "/home/daili/media/MD/torch-points3d/torch_points3d/modules/VoteNet/votenet_results.py", line 183, in get_boxes
    corners_3d = box_corners_from_param(box_size, heading_angle, self.center[i, j, :])
  File "/home/daili/media/MD/torch-points3d/torch_points3d/utils/box_utils.py", line 21, in box_corners_from_param
    corners_3d[0, :] = corners_3d[0, :] + center[0]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Is there some settings I did not do?

**Comment by nicolas-chaulet** [comment]
No, now you're good that's a bug. Let me open a PR with a fix

**Comment by nicolas-chaulet** [comment]
Actually, can you change this line https://github.com/nicolas-chaulet/torch-points3d/blob/47e6227a38a0de17a6eb5ba015bfdd48d64bf6a8/torch_points3d/modules/VoteNet/votenet_results.py#L183
```
 corners_3d = box_corners_from_param(box_size, heading_angle, self.center[i, j, :].cpu())
```
and see if that fixes it?

**Comment by daili650** [comment]
Thank you, this solved my problem!

**Comment by nicolas-chaulet** [comment]
Great to hear! Would you be able to submit a pull request with this fix?
Thanks!

**Comment by nicolas-chaulet** [comment]
Fixed
