### ISSUE TITLE
Error when running PointGroup with scannet-sparse

### ISSUE THREAD

**Issue by 1zb** [nicolas-chaulet/torch-points3d#497]
> cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.

The error is shown above.
The command line is
`python train.py task=panoptic model_type=pointgroup model_name=PointGroup dataset=scannet-sparse training=pointgroup training.cuda=0`

**Comment by nicolas-chaulet** [comment]
Indeed, that's a mistake on our side, pushing a fix now and thanks for reporting!
