### ISSUE TITLE
BoxData is_gt calculation is wrong

### ISSUE THREAD

**Issue by egeozsoy** [nicolas-chaulet/torch-points3d#499]
The description says: Basic data structure to hold a box prediction or ground truth
    if an score is provided then it will be treated as a prediction. Else, it is a ground truth box.

But the is_gt function returns the opposite

`return self.score is not None`

So if the score is not None, the function returns true, which implies the box data is for a ground truth box.

Fix: Very simple, the function should be 

`return self.score is None`

**Comment by nicolas-chaulet** [comment]
Good point, fixing that now but it is actually never used.
