### ISSUE TITLE
ModuleNotFoundError: No module named 'omegaconf.base'

### ISSUE THREAD

**Issue by DiegoWangSys** [nicolas-chaulet/torch-points3d#508]
Hi
When I use "torch.load(.pth)"
I got error like:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ma-user/work/test2/lib/python3.7/site-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ma-user/work/test2/lib/python3.7/site-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'omegaconf.base'

I thought its the version of omegaconf's problem but after I update the omegaconf I could not run your code!

So do we have other methods to load weights?

**Comment by DiegoWangSys** [comment]
I got the weights file .pth by omegaconf 2.0  
but the points3d is built on omegaconf 1.4
So hope we could upgrade points3d to omegaconf 2.0

**Comment by DiegoWangSys** [comment]
I del the .pth file "config" and solve the issue

**Comment by nicolas-chaulet** [comment]
I think upgrading is a bit of work unfortunately...

**Comment by omry** [comment]
I think you should REALLY upgrader to Hydra 1.0.
It should be pretty straight forward.

**Comment by nicolas-chaulet** [comment]
hehe alright I'll give it a go 👍 How do do you get notified of such things @omry ??

**Comment by omry** [comment]
hehe, I don't.
I got a saved [GitHub search](https://github.com/search?l=Python&o=desc&q=omegaconf&s=indexed&type=Code) I am looking at periodically.

Specifically Hydra is hard to search for because the name is too common so I search for omegaconf :).

**Comment by omry** [comment]
By the way, 1.0 is amazing. Check out the [blog post](https://hydra.cc/blog/2020/09/03/Hydra_1.0) if you missed it.

**Comment by nicolas-chaulet** [comment]
Yes we saw that and contemplated migrating at that point but we are doing this on our free time at the moment and trying to really focus our efforts...

**Comment by omry** [comment]
Beyond the new features which you can choose to use or not, there are multiple new plugins that only work with 1.0 and about a million fixed bugs.
You can opt in to Structured Configs when you have time (or not at all).

**Comment by nicolas-chaulet** [comment]
Yeah, the Structured Config is nice
