### ISSUE TITLE
Labels not being carried over for MultiScaleData

### ISSUE THREAD

**Issue by ThorJonsson** [nicolas-chaulet/torch-points3d#510]
See: https://github.com/nicolas-chaulet/torch-points3d/blob/de93a5e8e613bec96dbea49e39cce111330cfa0a/torch_points3d/datasets/multiscale_data.py#L19

I believe it should say

`super().__init__(x=x, y=y, pos=pos, multiscale=multiscale, upsample=upsample, **kwargs)`

**Comment by nicolas-chaulet** [comment]
That's a very good remark but surprisingly it actually always worked for me for some reason... I've changed that anyway. Thanks!
