### ISSUE TITLE
Installation issues with torch-cluster

### ISSUE THREAD

**Issue by TheFloHub** [nicolas-chaulet/torch-points3d#515]
Hey, after successfully installing pytoch 1.7.0 with cuda 10.1 I tried to install torch-points3d but the installation always breaks, when reaching torch-cluster. I'm working on a Windows 10 machine with Python 3.7.6.

My current packages:
Package           Version
----------------- -----------
click             7.1.2
dataclasses       0.6
future            0.18.2
itsdangerous      1.1.0
Jinja2            2.11.2
MarkupSafe        1.1.1
numpy             1.19.3
Pillow            8.0.1
pip               20.3.1
Python-dev        2.0.0.dev0
setuptools        51.0.0
torch             1.7.0+cu101
torchaudio        0.7.0
torchvision       0.8.1+cu101
typing-extensions 3.7.4.3
Werkzeug          1.0.1
wheel             0.36.1

This is the error I get:
Collecting torch-cluster<1.5.6
  Using cached torch_cluster-1.5.5.tar.gz (37 kB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\virtualenv\points3dtorch\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Florian\\AppData\\Local\\Temp\\pip-install-zhosh9sv\\torch-cluster_ef51ef4a171a42508d507c74e73e6aee\\setup.py'"'"'; __file__='"'"'C:\\Users\\Florian\\AppData\\Local\\Temp\\pip-install-zhosh9sv\\torch-cluster_ef51ef4a171a42508d507c74e73e6aee\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-fiqxnrqt'
         cwd: C:\Users\Florian\AppData\Local\Temp\pip-install-zhosh9sv\torch-cluster_ef51ef4a171a42508d507c74e73e6aee\
    Complete output (40 lines):
    running egg_info
    creating C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-fiqxnrqt\torch_cluster.egg-info
    writing C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-fiqxnrqt\torch_cluster.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-fiqxnrqt\torch_cluster.egg-info\dependency_links.txt
    writing requirements to C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-fiqxnrqt\torch_cluster.egg-info\requires.txt
    writing top-level names to C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-fiqxnrqt\torch_cluster.egg-info\top_level.txt
    writing manifest file 'C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-fiqxnrqt\torch_cluster.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Florian\AppData\Local\Temp\pip-install-zhosh9sv\torch-cluster_ef51ef4a171a42508d507c74e73e6aee\setup.py", line 89, in <module>
        packages=find_packages(),
      File "d:\virtualenv\points3dtorch\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "d:\python3.7.6\Lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\python3.7.6\Lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "d:\python3.7.6\Lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\virtualenv\points3dtorch\lib\site-packages\setuptools\command\egg_info.py", line 298, in run
        self.find_sources()
      File "d:\virtualenv\points3dtorch\lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources
        mm.run()
      File "d:\virtualenv\points3dtorch\lib\site-packages\setuptools\command\egg_info.py", line 536, in run
        self.add_defaults()
      File "d:\virtualenv\points3dtorch\lib\site-packages\setuptools\command\egg_info.py", line 572, in add_defaults
        sdist.add_defaults(self)
      File "d:\python3.7.6\Lib\distutils\command\sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "d:\python3.7.6\Lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "d:\python3.7.6\Lib\distutils\cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "d:\python3.7.6\Lib\distutils\dist.py", line 858, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "d:\virtualenv\points3dtorch\lib\site-packages\torch\utils\cpp_extension.py", line 325, in __init__
        super().__init__(*args, **kwargs)
      File "d:\virtualenv\points3dtorch\lib\site-packages\torch\utils\cpp_extension.py", line 330, in __init__
        super(BuildExtension, self).__init__(*args, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'no_python_abi_suffix'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Does anybody understand the problem? Also, why is it explicitly looking for a version torch-cluster<1.5.6?

Thank you.

**Comment by ttsesm** [comment]
Try installing it with the following command `pip install torch-cluster==1.5.5 --no-cache -v`

There is also a [troubleshooting](https://github.com/nicolas-chaulet/torch-points3d#undefined-symbol--updating-pytorch) mention that might be related.

**Comment by nicolas-chaulet** [comment]
I would recommend going on [torch cluster repo](https://github.com/rusty1s/pytorch_cluster) and you can find links to precompiled libraries there.

**Comment by TheFloHub** [comment]
Thanks for the help, but unfortunately no-chache doesn't help and gives the same results.

I also checked the issues in the torch-cluster repos, but couldn't find anything.
They also offer only precompiled libraries for pytorch 1.7 that have version greater than 1.5.5 (only 1.5.8).

I tried to install pytorch 1.5.1 to continue from there but when I run "pip install torch-points3d" it automatically updates pytorch to 1.7.

**Comment by nicolas-chaulet** [comment]
Hey, I have removed the requirement for 1.5.5 in the latest code on master. Can you try
```
pip install git+https://github.com/nicolas-chaulet/torch-points3d.git
```

**Comment by TheFloHub** [comment]
Hey thanks, this didn't work directly, but I could now preinstall torch-cluster via:
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
and then run your command. Then torch-points is not complaining anymore. I think just running torch-points3d is not installing the right cluster package for me then.
But in genreally this worked.
Unfortunately I get the same error now with torch-points-kernels. But there is probably a similar solution. I think I can figure it out.
Thanks again =)
