### ISSUE TITLE
[QUESTION] Config for FCGF Descriptor?

### ISSUE THREAD

**Issue by chuong98** [nicolas-chaulet/torch-points3d#519]
Hi. I am new to torch-points3d, and I see that FCGF is supported according to the Readme.
However, I could not find its config. Please help with my newbie questions:
1. Is the `model = PretainedRegistry.from_pretrained("minkowski-registration-3dmatch")` the correct model to extract FCGF ?
2. Can we switch it to `torchsparse` backend? I guess I am confused between `Minkowski` network and `Minkowski` backend?
3. Do we have a benchmark for 3DMatch, as mentioned in #118 ? For example, this figure. 

![fps_acc](https://user-images.githubusercontent.com/15174756/102110815-dcc1cb00-3df2-11eb-8af7-4c64e472d3fd.png)

Thank you for your help.

**Comment by humanpose1** [comment]
Hi,

thank you for your interest for `torch-points3d`.
1. Yes this is the FCGF model maybe the architecture is a bit different, but we could reproduce the results of the paper.
to reproduce the results you can launch this command:
`python train train.py task=registration model_type=minkowski model_name=MinkUNet_Fragment dataset=fragment3dmatch_sparse training=sparse_fragment_reg training.epochs=200`


2. Unfortunately this model doesn't support the torchsparse backend (it was written before that...). I've made another version with torchsparse lib (and here you can change the backend). The code is almost here and the conf file is missing (I'll push that).

3. Unfortunately, the benchmark is not here yet. For 3DMatch there is the Fragment version, (to train FCGF and D3Feat-like models) and there is the Patch version see [here](https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/datasets/registration/general3dmatch.py) for the dataset.
But the other methods haven't been implemented. It's not that complicated but it takes time.
Btw, for FCGF you can replace the sparse convolution with kpconv or pointnet++ (after all, it's just a unet architecture). But in practice, results are better for sparse conv.

Don't hesitate if you have other questions ;)

**Comment by chuong98** [comment]
Thank you.
