### ISSUE TITLE
KPConv with own dataset

### ISSUE THREAD

**Issue by dgriffiths3** [nicolas-chaulet/torch-points3d#520]
I am trying to use the KPConv encoder in a separate project, with my own dataset. My data is a `x = torch.tensor()` with size `[b, n, 3]`.

To make the data compatible I convert to a pytorch geometric object with the line:

`x = torch_geometric.data.Data(x=x, pos=x)`

This works fine with the PointNet2 model, however, I run into the error when using KPConv:

`AttributeError: 'Data' object has no attribute 'batch'`

I'm not  familiar with the pytorch geometric library. Could you give me a pointer what `.batch' should contain?

**Comment by humanpose1** [comment]
HI @dgriffiths3  
Unlike Pointnet and pointnet++,  kpconv can handle batch of point cloud of different sizes. the pos contains one big point cloud which is the concatenation of your point clouds. the size is therefore`[N, 3]`, In the variable `batch` , you need to indicate for each point the index of the batch
For example.
```python
import torch
from torch_geometric.data import Batch
pos1 = torch.tensor([[0,0,0],[0,0.5,0]])
pos2 = torch.tensor([[1,1,1],[10, 1, 2], [0,-1,3.5]])
pos3 = torch.tensor([[0,0,0]])

pos = torch.cat([pos1, pos2, pos3], 0)
batch = torch.tensor([0, 0, 1, 1, 1, 2]).long()
x = torch.tensor([1,1,1,1,1,1]).float()
batch = Batch(x=x, pos=pos, batch=batch)
```
Btw, unlike pointnet and pointnet++, the features can be ones in KPConv (as mentionned in the [original paper](https://openaccess.thecvf.com/content_ICCV_2019/papers/Thomas_KPConv_Flexible_and_Deformable_Convolution_for_Point_Clouds_ICCV_2019_paper.pdf)),but it can also be the position, the normals or the colors.

**Comment by dgriffiths3** [comment]
Great, that worked thanks!
