### ISSUE TITLE
cannot find "RandomRotate" transform

### ISSUE THREAD

**Issue by Hafplo** [nicolas-chaulet/torch-points3d#526]
I am trying some transformations on point clouds (as data augmentations). And I would like to rotate the cloud (e.g. around some axis or plane)

The "RandomRotate" transform appears on config files (yaml) and in the README, but I cannot locate the origin. So I cannot know how it transforms the data.

**Comment by nicolas-chaulet** [comment]
We actually give access to all pytorch geometric transform through the config file in addition to our own transform. So if you can't find it in the code then it comes from pytorch geometric! Help for those is here:
https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html
