### ISSUE TITLE
How to use torch-points3d to do semantic segmentation in my own point cloud data?

### ISSUE THREAD

**Issue by yellowhahaha** [nicolas-chaulet/torch-points3d#527]
Hi,
   I have a point cloud of about several million points and want to use torch-points3d to do semantic segmentation in this data with pretrained model. How can I achiieve that or is there any API？ Sorry to bother you, I'm a new guy in this field.

**Comment by CCInc** [comment]
Hi!

Firstly you will need to create a dataset class for your data. You can use the examples in torch_points3d/datasets/segmentation as reference.  Take a look at the [docs](https://torch-points3d.readthedocs.io/en/latest/src/tutorials.html#) for tips. You will have to split your point cloud up into smaller sizes to feed into the network, you can use the `RandomSphere` transform for that. 

Once you have the dataset, you can run experiments directly on it. To train from scratch you can run from the command line, or to train with a model in the PretrainedRegistry take a look at notebooks/demo_registration_3dm.ipynb and demo_registration_kitti.ipynb.

**Comment by yellowhahaha** [comment]
I will try it, thanks a lot!
