### ISSUE TITLE
About model implementation

### ISSUE THREAD

**Issue by Obarads** [nicolas-chaulet/torch-points3d#534]
thanks for your project.
Does this library have a plan (roadmap) of model implementation?

**Comment by nicolas-chaulet** [comment]
Hey, great question! I have added a new tag to the issues "model", those are the models that we would like to have. We have very limited implementation capacity at the moment and any help is more than welcome! You can also join our Slack if you want to chat about that in more detail:
https://join.slack.com/t/torchgeometricco/shared_invite/zt-kijf8k6b-ClJZ3ieYmViQrcjvMG2apQ
