### ISSUE TITLE
training with "shapenet-fixed"

### ISSUE THREAD

**Issue by talelkkc** [nicolas-chaulet/torch-points3d#540]
![Sans titre](https://user-images.githubusercontent.com/32612513/105151077-d0254680-5b05-11eb-91b1-a54ad07840b6.png)
when started the training , i see this error each "epoch",but at the same time It is finished the training. and when executed the "forward.py"  i have another problem .
- the question : the error of training do have any impact in the output.

**Comment by nicolas-chaulet** [comment]
In principle this error does not harm training. There was an update yesterday that should have fixed it, are you up to date with master?

**Comment by talelkkc** [comment]
so, why i have this error with configuration next  ???
-error : 
![Sanus titre](https://user-images.githubusercontent.com/32612513/105183150-20180380-5b2e-11eb-9130-8b1803b9e3c8.png)

-configuration : 
![Sans0 titre](https://user-images.githubusercontent.com/32612513/105183759-d845ac00-5b2e-11eb-9b4f-ffb6760d54eb.png)

**Comment by nicolas-chaulet** [comment]
Hey, this is an error that is now fixed in master. If you train your network again it should be good.
