### ISSUE TITLE
PointNet Classification Model

### ISSUE THREAD

**Issue by PaulJWright** [nicolas-chaulet/torch-points3d#541]
Is the PointNet classification model implemented?

For segmentation, the following runs fine
```
python train.py task=segmentation model_type=pointnet model_name=PointNet dataset=shapenet-fixed
```

but there is no `models/classification/pointnet.yaml`, for when `task=classification`. If this isn't implemented, I am guessing the best way to do this is to follow the example notebook here: https://colab.research.google.com/github/nicolas-chaulet/torch-points3d/blob/master/notebooks/ObjectClassificationRSConv.ipynb?

Cheers!

**Comment by humanpose1** [comment]
Hi @PaulJWright 
Yes, you can follow the example notebook, (in the API pointnet is not available but pointnet++ is available). 
If you want to use the command line, you can:
- fork the tp3d repo
- write the models in torch_points3d/models/classification/pointnet.py 
- write the associated yaml conf/models/classification/pointnet.yaml
and normally,  you'll be able to run.
```
python train.py task=segmentation model_type=pointnet model_name=PointNet dataset=modelnet
```
Don't hesitate if you have other questions :)
