### ISSUE TITLE
Pytorch <1.7 DataLoader Bug

### ISSUE THREAD

**Issue by CCInc** [nicolas-chaulet/torch-points3d#547]
#538 introduces a breaking bug for pytorch<1.7.0. 

`persistent_workers` is not implemented for earlier versions of pytorch.

I'll look for fix.

**Comment by nicolas-chaulet** [comment]
Shall we just impose pytorch 1.7 as a minimum then?

**Comment by CCInc** [comment]
We could, I'm not sure if it's worth it for just this one issue though. It's an easy fix either way.

**Comment by nicolas-chaulet** [comment]
Yes right so fixing is the best option, are you able to make a small PR? Thanks!

**Comment by CCInc** [comment]
As I was making a fix, I realized that a few other features we are using are 1.7+ specific, for example torch.nn.SiLU. So, it's probably easiest just to bump the min version to 1.7+ 😄

**Comment by CCInc** [comment]
Although, in theory, we could still support <1.7 as long as they don't use minkowski. So, let me know if you still want me to push the PR.
