### ISSUE TITLE
CUDA version mismatch

### ISSUE THREAD

**Issue by kudo1026** [nicolas-chaulet/torch-points3d#553]
Hi,

I followed the poetry installation procedure, but when I tried to do the unit test, all tests come back with the error:
`RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_sparse has CUDA version 11.2. Please reinstall the torch_sparse that matches your PyTorch install.
`

Any idea how should I solve it?

**Comment by kudo1026** [comment]
I followed the approach https://github.com/nicolas-chaulet/torch-points3d/issues/545#issuecomment-771233853, and now the test does not experience the this error.

**Comment by CamilleMaurice** [comment]
Hi ! 
I am facing the same issue but I do not have access anymore to your solution.
Anybody can help ?
Thank you
Camille
