### ISSUE TITLE
RandLaNet on S3DIS (fused or 1x1) data issue

### ISSUE THREAD

**Issue by PhysicsOfAI** [nicolas-chaulet/torch-points3d#554]
Hi,
When choosing randlanet models (both RandlaNet_Res and Randlanet_Conv) and s3dis (both fused and 1x1) data sets, I encountered tensor dimension errors when the training starts. For example, when choosing Randlanet_Conv on s3dis1x1, I got
"ValueError: Encountered tensor with size 65536 in dimension -2, but expected size 16384."; when choosing Randlanet_Conv on s3disfused, I got
"ValueError: Encountered tensor with size 245216 in dimension -2, but expected size 61304".
I am wondering if I missed anything in configs?
It is fine when choosing pointnet2 on s3dis1x1.
Thanks!

**Comment by nicolas-chaulet** [comment]
Hey! We haven't updated randlanet in quite some time and it might very well be outdated. Sorry about that.
