### ISSUE TITLE
error while inital_voxelize in PVCNN.

### ISSUE THREAD

**Issue by sinAshish** [nicolas-chaulet/torch-points3d#556]
I do the foll. to create a voxel:
```python
x= torch.rand(2, 512, 3) #BxNxC
coords = torch.cat([x, x.size()[:2].unsqueeze(-1)], -1) #BxNx(C+1)
pc = SparseTensor(x, coords.int()).to(device)
z = PointTensor(pc.F, pc.C.float()).to(device)
x0 = initial_voxelize(z, 1., 0.01)
```
I get the foll. error:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in initial_voxelize
  File "/usr/local/lib/python3.6/dist-packages/torchsparse/nn/functional/voxelize.py", line 25, in spvoxelize
    return VoxelizeGPU.apply(feat, idx, cnt)
  File "/usr/local/lib/python3.6/dist-packages/torchsparse/nn/functional/voxelize.py", line 11, in forward
    out = torchsparse_cuda.insertion_forward(feat.float().contiguous(),
AttributeError: module 'torchsparse_cuda' has no attribute 'insertion_forward'
```
I get the same error, when I do the following too:
```python
x=torch.randn(1024, 3)
coords = torch.cat([x, x[:,0].unsqueeze(-1)], -1)
x = SparseTensor(x, coords)
z = PointTensor(x.F,x.C.float())
x0=initial_voxelize(z, 1., 0.01)
```

How do I solve this?
I want to get a voxel of dim: #BxCxRxRxR, given that I have a PC of dim: BxNxC.
Any help would be appreciated!

**Comment by CCInc** [comment]
That sort of thing usually indicates torchsparse didn't install correctly, can you try uninstalling and reinstalling?

```
pip uninstall torchsparse
pip install --no-cache-dir -vv git+https://github.com/mit-han-lab/torchsparse.git
```

Post logs if you run into any errors when doing that.

**Comment by sinAshish** [comment]
it works fine now after re-installation.
but now after  running:
`x0=initial_voxelize(z, 1., 0.01)`
i get a tensor which is filled with only 0

**Comment by nicolas-chaulet** [comment]
Hi @sinAshish thanks for the report, this seems like a bug with torchsparse, would you mind raising an issue on their repo?

**Comment by sinAshish** [comment]
yes I've opened an issue there, and they're looking into it

**Comment by sinAshish** [comment]
works well with Cuda tensors only

**Comment by nicolas-chaulet** [comment]
Awesome!
