### ISSUE TITLE
Error loading Data in Tutorial: PartSegmentationKPConv 

### ISSUE THREAD

**Issue by TommasoPappagallo** [nicolas-chaulet/torch-points3d#558]
Hello, thanks for putting up the notebooks. In PartSegmentationKPConv 
"from torch_points3d.datasets.segmentation import ShapeNetDataset
dataset = ShapeNetDataset(params)
dataset"
I'm getting the error to do with torch_sparse :

RuntimeError:
attribute assignment is not defined on torch.torch_sparse.storage.SparseStorage:
File "/Users/parrot/Envs/test2/lib/python3.7/site-packages/torch_sparse/storage.py", line 145
def empty(self):
self = SparseStorage.new(SparseStorage)
self._row = None
~~~~~~~~~~~~~~~~ <--- HERE
self._rowptr = None
self._value = None

as well as

OSError: dlopen(/Users/parrot/Envs/torch3.8/lib/python3.8/site-packages/torch_sparse/_version.so, 6): Symbol not found: _ZN3c106detail12infer_schema20make_function_schemaENS_8ArrayRefINS1_11ArgumentDefEEES4
Referenced from: /Users/parrot/Envs/torch3.8/lib/python3.8/site-packages/torch_sparse/_version.so
Expected in: /Users/parrot/Envs/torch3.8/lib/python3.8/site-packages/torch/lib/libtorch_cpu.dylib
in /Users/parrot/Envs/torch3.8/lib/python3.8/site-packages/torch_sparse/_version.so

**Comment by nicolas-chaulet** [comment]
Hey! Looks like a compilation issue, can you try those steps?
https://github.com/nicolas-chaulet/torch-points3d#troubleshooting

**Comment by TommasoPappagallo** [comment]
Hi Nicolas sorry for not getting back earlier just saw this. Yes indeed was a compilation issue :) May i ask whether there is an info on changes that need to be made to the KP conv segmentation google colab notebook in order to implement on ones own dataset. I have mac os so my only option to access a cuda gpu is via google's gpu. I have a large labeled pointcloud dataset ready to go on my local but struggling to integrate into your very good and very helpful google colab notebook. Even a brief outline of what areas to change i think would be super useful for less experienced future users! (ie: what to change in the yaml etc..) All the best T

**Comment by nicolas-chaulet** [comment]
Hey! Glad that's fixed, we have this tutorial if that helps:
https://torch-points3d.readthedocs.io/en/latest/src/tutorials.html#create-a-new-dataset
