### ISSUE TITLE
Create my own dataset

### ISSUE THREAD

**Issue by Oliver927-lab2** [nicolas-chaulet/torch-points3d#562]
Hello. Can you tell me how to create my own dataset to train the pointnet2 network?  I have done several tests (task = segmentation, dataset = shapenet)
I would like to create my own labels and therefore my own dataset.
Is there a tool or a guide?

**Comment by nicolas-chaulet** [comment]
There is a good place to start!
https://torch-points3d.readthedocs.io/en/latest/src/tutorials.html#create-a-new-dataset
