### ISSUE TITLE
pip install torch-points3d failed. Cuda version?

### ISSUE THREAD

**Issue by rdmato33** [nicolas-chaulet/torch-points3d#566]
Hi,

I tried installing torch-points3d following the documentation (https://torch-points3d.readthedocs.io/en/latest/). 

I did:
```
pip install torch
pip install torch-points3d
```

I use:
- Python 3.7
- Cuda 10.1
- Visual Studio 2019

It seems some modules caused troubles at installation, especially torch-cluster, torch-scatter, torch-sparse and torch-points-kernels. I succeed to fix torch-cluster, torch-scatter and torch-sparse installation using the following command by replacing with specific torch and CUDA versions (as expressed here https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html):

`pip install torch-cluster torch-scatter torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html`

Torch and Cuda versions were checked using the following commands:
```
python -c "import torch; print(torch.__version__)"
1.8.0+cpu
```

```
python -c "import torch; print(torch.version.cuda)"
None
```

I also succeed to `pip install torch-points-kernels==0.7.0` but torch-points3d needs torch-points-kernels<0.7.0,>=0.6.6.

When launching a good version of torch-points-kernels, such as `pip install torch-points-kernels==0.6.6`, it gives:

`No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'`

`C:\Users\..\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: [WinError 2]`

`c10/cuda/impl/cuda_cmake_macros.h'ÿ: No such file or directory`

`error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2`

It seems I have a problem with the CUDA macros. 
I uninstalled and reinstalled CUDA 10.1, I did the same thing for Visual Studio 2019, but I didn't found any solution.
I also tried with torch==1.7.0 and torch==1.7.0+cpu

How could I fix it?

Thanks

**Comment by CCInc** [comment]
You are installing CPU versions of all these packages, that's why it's failing. "https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html" indicates CPU version, plus your pytorch version is CPU. Install the correct cuda versions and you should be good.

**Comment by rdmato33** [comment]
Well, I restarted all the process following those steps:
1) Install Visual Studio 2019
2) Install Visual Studio Build Tools 2019
3) Install Cuda 10.1
4) Create a new conda environment in Python 3.6
5) `pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html` (following the documentation here https://pytorch.org/get-started/previous-versions/)
6) `pip install torch-cluster torch-scatter torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html` (torch-1.7.1+cu101.html doesn't exist but torch-cluster, torch-scatter and torch-sparse could be installed anyway).

At this stage, `pip list` is:

```
Package             Version
------------------- -------------------
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.3.0
backcall            0.2.0
bleach              3.3.0
certifi             2020.12.5
cffi                1.14.5
chardet             4.0.0
colorama            0.4.4
dataclasses         0.8
decorator           4.4.2
defusedxml          0.7.1
entrypoints         0.3
idna                2.10
importlib-metadata  3.7.3
ipykernel           5.5.0
ipython             7.16.1
ipython-genutils    0.2.0
jedi                0.18.0
Jinja2              2.11.3
joblib              1.0.1
jsonschema          3.2.0
jupyter-client      6.1.12
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
llvmlite            0.36.0
MarkupSafe          1.1.1
mistune             0.8.4
nbclient            0.5.3
nbconvert           6.0.7
nbformat            5.1.2
nest-asyncio        1.5.1
numba               0.53.0
numpy               1.19.5
oauthlib            3.1.0
packaging           20.9
pandocfilters       1.4.3
parso               0.8.1
pickleshare         0.7.5
Pillow              8.1.2
pip                 21.0.1
prometheus-client   0.9.0
promise             2.3
prompt-toolkit      3.0.17
pyasn1              0.4.8
pyasn1-modules      0.2.8
pycparser           2.20
Pygments            2.8.1
pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.1
pywin32             300
pywinpty            0.5.7
pyzmq               22.0.3
requests            2.25.1
rsa                 4.7.2
scikit-learn        0.24.1
scipy               1.5.4
Send2Trash          1.5.0
setuptools          52.0.0.post20210125
six                 1.15.0
smmap               3.0.5
terminado           0.9.3
testpath            0.4.4
threadpoolctl       2.1.0
torch               1.7.1+cu101
torch-cluster       1.5.9
torch-scatter       2.0.6
torch-sparse        0.6.9
torchaudio          0.7.2
torchvision         0.8.2+cu101
tornado             6.1
traitlets           4.3.3
typing-extensions   3.7.4.3
urllib3             1.26.4
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.36.2
wincertstore        0.2
zipp                3.4.1
```

7) Then, I did a `pip install torch-points-kernels==0.6.10` (which is a compatible version with torch-points3d), and again, I got similar errors when building wheel:

`C:\Users\..\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: [WinError 2] `

```
 2 errors detected in the compilation of "C:/Users/R05BB~1.DE-/AppData/Local/Temp/tmpxft_00000620_00000000-7_chamfer_dist_gpu.cpp1.ii".
  chamfer_dist_gpu.cu
  error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for torch-points-kernels
```
Any help is appreciated.

**Comment by rdmato33** [comment]
Well, I finally found a way to install torch-points3d. Here are the steps I followed:

1) Clone the git repository
`git clone https://github.com/nicolas-chaulet/torch-points3d.git`

2) Installing those modules (in my case, pytorch works with conda but not with pip):
```
conda create -n torchdev python=3.7
conda activate torchdev
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
pip install torch-points-kernels==0.6.6
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
```

3) Edit the "requirements.txt" file from the git repository and remove the previous modules from the list.

4) `pip install -r .\requirements.txt`

**Comment by nicolas-chaulet** [comment]
Awesome thanks!
