### ISSUE TITLE
Running KPConv with my own dataset containing 3D local descriptors in PLY format

### ISSUE THREAD

**Issue by abhimandal** [nicolas-chaulet/torch-points3d#567]
Hey Good 3d point Samaritans,

Thanks a lot for this awesome repo. 
I am evaluating different works to use for my Master Thesis and I find this repo really helpful and something which I can use. 

Basically, in my thesis, I have **Patient Data for Intracranial Aneurysms** (in simple words blood vessels in brains that can lead to life-threatening haemorrhage). I have pre-processed my data and have a  single PLY file for each patient. I want to predict the Wall Shear Stress (WSS) values, the high value of which causes blood vessels to burst and then brain haemorrhage. 

Now, I am planning to use KPConv part segmentation to predict these WSS values. Additionally in my pre-processing, I have computed 2 local descriptors i.e. FPFH and SHOT. My other research question is how the addition of these impact the prediction.

So, I wanted to take advice on the following:

1.  Can these features be added to the dataset for training? - I guess I need to use AddFeatsByKeys[https://torch-points3d.readthedocs.io/en/latest/src/api/transforms.html#torch_points3d.core.data_transform.AddFeatsByKeys](url) and add them. 
These descriptors are a list of list values in PLY. One patient data sample is in [https://drive.google.com/drive/folders/1-m-AZ8tJo_5qWGu0ZuanNKE5Ga4HWr-J?usp=sharing](url)
2. I need to decrease the shape of these descriptors maybe by using PCA. There is a PCACompute transform, but I wanted to confirm if that has to be done on one patient file (point cloud) or can be for a batch?  I think the most efficient one will be to pre-compute the features and save them. What do you think? 
3. These descriptors are having some NaN values. Should those be handled before creating a Dataset object or can I use some kind of transform (Sorry for asking this as I am completely new to PyTorch based architectures)

Thanks for your valuable time.

**Comment by humanpose1** [comment]
Hi,
I'll try to answer your questions.
1. Yes, with `AddFeatsByKeys` you can add features on x. You can try to add FPFH or SHOT features, but KPConv has reported good results without any feature (just adding ones is enough) on Modelnet and Shapenet part, it has good results even without normals.
2. The `PCATransform` is maybe depreciated, you'll need to add your own transform. If it is too slow, it is possible to pre process and store the results (this is the role of `pre_transform`). 
3. networks doesn't handle NaN values, so I think it is better to handle them before (it can be before creating the dataset or in the `pre_transform` step)
