### ISSUE TITLE
Loading Pretrained Pointgroup Model

### ISSUE THREAD

**Issue by Changyangli** [nicolas-chaulet/torch-points3d#569]
Hello, thank you for the great work! I was trying to load the pretrained pointgroup model using
`model = PretainedRegistry.from_pretrained("pointgroup-scannet")`

This failed because in pretrained_api.py, the MOCK_USED_PROPERTIES is empty for "pointgroup-scannet". May I know if there are specific instructions of using the pretrained pointgroup model? Thanks!

**Comment by nicolas-chaulet** [comment]
Hey! We haven't maintained that in some time and to be honest we never managed to replicate the performance of pointgroup unfortunately...

**Comment by Changyangli** [comment]
> Hey! We haven't maintained that in some time and to be honest we never managed to replicate the performance of pointgroup unfortunately...

Oh, I see... Thanks for your reply!
