### ISSUE TITLE
Shadow points initialization

### ISSUE THREAD

**Issue by kimihailv** [nicolas-chaulet/torch-points3d#576]
Hello, I have a question, in official implementation of KPConv author uses [1e6 for shadow points](https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/kernels/convolution_ops.py#L190),  but in your implementation you use zeros. Can you please explain it?

**Comment by nicolas-chaulet** [comment]
What makes you think we use 0?
https://github.com/nicolas-chaulet/torch-points3d/blob/d2dbd0b56bcb71ebb47ecb6279062bac9e23c530/torch_points3d/modules/KPConv/convolution_ops.py#L49

**Comment by kimihailv** [comment]
Oh sorry, I mixed up shadow features with shadow points. Sorry. Thank you for reply.
