### ISSUE TITLE
Failed to train kpconv on SemanticKItti

### ISSUE THREAD

**Issue by cvhabitat** [nicolas-chaulet/torch-points3d#583]
Dear Nicolas,

Many thanks for your great work. I'm trying to train the **kpconv** on **semantickitti**. I can successfully process the raw data. But, I cannot start to train the model using the following command:

> python train.py task=segmentation model_type=kpconv model_name=KPDeformableConvPaper dataset=semanticKitti training=kpconv visualization.activate=True

The errors I got as following:

> Traceback (most recent call last):
>   File "train.py", line 21, in <module>
>     main()
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
>     strict=strict,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
>     overrides=args.overrides,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
>     job_subdir_key=None,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
>     ret.return_value = task_function(task_cfg)
>   File "train.py", line 12, in main
>     trainer = Trainer(cfg)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/trainer.py", line 44, in __init__
>     self._initialize_trainer()
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/trainer.py", line 90, in _initialize_trainer
>     self._model: BaseModel = instantiate_model(copy.deepcopy(self._cfg), self._dataset)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/models/model_factory.py", line 23, in instantiate_model
>     resolve_model(model_config, dataset, task)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/utils/model_buil
> wandb: Waiting for W&B process to finish, PID 7649
> ding_utils/model_definition_resolver.py", line 17, in resolve_model
>     constants.update(dict(model_config.define_constants))
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 93, in __getitem__
>     return self.__getattr__(key)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 85, in __getattr__
>     return self.get(key=key, default_value=None)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 99, in get
>     default_value=default_value,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 153, in _resolve_with_default
>     return self._resolve_single(value) if isinstance(value, str) else value
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 487, in _resolve_single
>     return Config._resolve_value(root, match.group(1), match.group(2))
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 463, in _resolve_value
>     "{} interpolation key '{}' not found".format(inter_type, inter_key)

Could you help me with these problems, please?

Thanks in advance,
Oliver

**Comment by CCInc** [comment]
@cvhabitat Is there more to that error message besides just the traceback? It should print something as well

**Comment by cvhabitat** [comment]
Hi Christopher,

Thank you for your quick response.

These are the complete outputs:

> DEVICE : cuda
> wandb: Tracking run with wandb version 0.8.36
> wandb: Wandb version 0.10.25 is available!  To upgrade, please run:
> wandb:  $ pip install wandb --upgrade
> wandb: Run data is saved locally in wandb/run-20210411_223225-3rsybyi3
> wandb: Syncing run kpconv-bn02
> wandb: ⭐️ View project at https://app.wandb.ai/p3d/s3dis
> wandb: 🚀 View run at https://app.wandb.ai/p3d/s3dis/runs/3rsybyi3
> wandb: Run `wandb off` to turn off syncing.
> 
> Traceback (most recent call last):
>   File "train.py", line 21, in <module>
>     main()
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
>     strict=strict,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
>     overrides=args.overrides,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
>     job_subdir_key=None,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
>     ret.return_value = task_function(task_cfg)
>   File "train.py", line 12, in main
>     trainer = Trainer(cfg)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/trainer.py", line 44, in __init__
>     self._initialize_trainer()
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/trainer.py", line 90, in _initialize_trainer
>     self._model: BaseModel = instantiate_model(copy.deepcopy(self._cfg), self._dataset)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/models/model_factory.py", line 23, in instantiate_model
>     resolve_model(model_config, dataset, task)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/utils/model_building_utils/model_definition_resolver.py", line 17, in resolve_model
>     constants.update(dict(model_config.define_constants))
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 93, in __getitem__
>     return self.__getattr__(key)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 85, in __getattr__
>     return self.get(key=key, default_value=None)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/d
> wandb: Waiting for W&B process to finish, PID 2735
> ictconfig.py", line 99, in get
>     default_value=default_value,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 153, in _resolve_with_default
>     return self._resolve_single(value) if isinstance(value, str) else value
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 487, in _resolve_single
>     return Config._resolve_value(root, match.group(1), match.group(2))
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 463, in _resolve_value
>     "{} interpolation key '{}' not found".format(inter_type, inter_key)
> KeyError: "str interpolation key 'data.first_subsampling' not found"
> wandb: Program failed with code 1. Press ctrl-c to abort syncing.
> wandb: Process crashed early, not syncing files

Any suggestions, please?

**Comment by CCInc** [comment]
@cvhabitat Please try replacing "grid_size" with "first_subsampling" every time it occurs in `semanticKitti.yaml` and let me know the progress.  This should be changed anyways, I will make a PR for this.

**Comment by CCInc** [comment]
As a side note, I don't know how performant KPConv in its current implementation is. If I may, I would suggest trying one of the sparseconv3d networks based on 3d sparse convolutions. They perform very well on many kinds of datasets

**Comment by cvhabitat** [comment]
> @cvhabitat Please try replacing "grid_size" with "first_subsampling" every time it occurs in `semanticKitti.yaml` and let me know the progress. This should be changed anyways, I will make a PR for this.

After I changed all "grid_size" to "first_subsampling", it displays as follows:

> DEVICE : cuda
> wandb: Tracking run with wandb version 0.8.36
> wandb: Wandb version 0.10.25 is available!  To upgrade, please run:
> wandb:  $ pip install wandb --upgrade
> wandb: Run data is saved locally in wandb/run-20210411_224804-15ce2l4k
> wandb: Syncing run kpconv-bn02
> wandb: ⭐ View project at https://app.wandb.ai/p3d/s3dis
> wandb: 🚀 View run at https://app.wandb.ai/p3d/s3dis/runs/15ce2l4k
> wandb: Run `wandb off` to turn off syncing.
> 
> Error trying to create train_transform, [{'transform': 'ElasticDistortion'}, {'transform': 'Random3AxisRotation', 'params': {'apply_rotation': '${data.apply_rotation}', 'rot_x': 2, 'rot_y': 2, 'rot_z': 180}}, {'transform': 'RandomScaleAnisotropic', 'params': {'scales': [0.9, 1.1]}}, {'transform': 'GridSampling3D', 'params': {'size': '${data.first_subsampling}', 'quantize_coords': True, 'mode': '${data.mode}'}}]
> Traceback (most recent call last):
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/datasets/base_dataset.py", line 129, in set_transform
>     transform = instantiate_transforms(getattr(dataset_opt, key_name))
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/core/data_transform/__init__.py", line 91, in instantiate_transforms
>     transforms.append(instantiate_transform(transform))
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/core/data_transform/__init__.py", line 74, in instantiate_transform
>     return cls(**tr_params)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 93, in __getitem__
>     return self.__getattr__(key)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 85, in __getattr__
>     return self.get(key=key, default_value=None)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 99, in get
>     default_value=default_value,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 153, in _resolve_with_default
>     return self._resolve_single(value) if isinstance(value, str) else value
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 487, in _resolve_single
>     return Config._resolve_value(root, match.group(1), match.group(2))
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 463, in _resolve_value
>     "{} interpolation key '{}' not found".format(inter_type, inter_key)
> KeyError: "str interpolation key 'data.first_subsampling' not found"
> Error trying to create val_transform, [{'transform': 'GridSampling3D', 'params': {'size': '${data.first_subsampling}', 'quantize_coords': True, 'mode': '${data.mode}'}}]
> Traceback (most recent call last):
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/datasets/base_dataset.py", line 129, in set_transform
>     transform = instantiate_transforms(getattr(dataset_opt, key_name))
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/core/data_transform/__init__.py", line 91, in instantiate_transforms
>     transforms.append(instantiate_transform(transform))
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/core/data_transform/__init__.py", line 74, in instantiate_transform
>     return cls(**tr_params)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 93, in __getitem__
>     return self.__getattr__(key)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 85, in __getattr__
>     return self.get(key=key, default_value=None)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 99, in get
>     default_value=default_value,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 153, in _resolve_with_default
>     return self._resolve_single(value) if isinstance(value, str) else value
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 487, in _resolve_single
>     return Config._resolve_value(root, match.group(1), match.group(2))
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 463, in _resolve_value
>     "{} interpolation key '{}' not found".format(inter_type, inter_key)
> KeyError: "str interpolation key 'data.first_subsampling' not found"
> Error trying to create test_transform, [{'transform': 'GridSampling3D', 'params': {'size': '${data.first_subsampling}', 'quantize_coords': True, 'mode': '${data.mode}'}}]
> Traceback (most recent call last):
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/datasets/base_dataset.py", line 129, in set_transform
>     transform = instantiate_transforms(getattr(dataset_opt, key_name))
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/core/data_transform/__init__.py", line 91, in instantiate_transforms
>     transforms.append(instantiate_transform(transform))
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/core/data_transform/__init__.py", line 74, in instantiate_transform
>     return cls(**tr_params)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 93, in __getitem__
>     return self.__getattr__(key)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 85, in __getattr__
>     return self.get(key=key, default_value=None)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 99, in get
>     default_value=default_value,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 153, in _resolve_with_default
>     return self._resolve_single(value) if isinstance(value, str) else value
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 487, in _resolve_single
>     return Config._resolve_value(root, match.group(1), match.group(2))
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 463, in _resolve_value
>     "{} interpolation key '{}' not found".format(inter_type, inter_key)
> KeyError: "str interpolation key 'data.first_subsampling' not found"
> Traceback (most recent call last):
>   File "train.py", line 21, in <module>
>     main()
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
>     strict=strict,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
>     overrides=args.overrides,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
>     job_subdir_key=None,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
>     ret.return_value = task_function(task_cfg)
>   File "train.py", line 12, in main
>     trainer = Trainer(cfg)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/trainer.py", line 44, in __init__
>     self._initialize_trainer()
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/trainer.py", line 90, in _initialize_trainer
>     self._model: BaseModel = instantiate_model(copy.deepcopy(self._cfg), self._dataset)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/models/model_factory.py", line 23, in instantiate_model
>     resolve_model(model_config, dataset, task)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/utils/model_building_utils/model_definition_resolver.py", line 17, in resolve_model
>     constants.update(dict(model_config.define_constants))
>   File
> wandb: Waiting for W&B process to finish, PID 4195
>  "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 93, in __getitem__
>     return self.__getattr__(key)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 85, in __getattr__
>     return self.get(key=key, default_value=None)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 99, in get
>     default_value=default_value,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 153, in _resolve_with_default
>     return self._resolve_single(value) if isinstance(value, str) else value
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 487, in _resolve_single
>     return Config._resolve_value(root, match.group(1), match.group(2))
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 463, in _resolve_value
>     "{} interpolation key '{}' not found".format(inter_type, inter_key)
> KeyError: "str interpolation key 'data.first_subsampling' not found"
> wandb: Program failed with code 1. Press ctrl-c to abort syncing.
> wandb: Process crashed early, not syncing files

**Comment by cvhabitat** [comment]
> As a side note, I don't know how performant KPConv in its current implementation is. If I may, I would suggest trying one of the sparseconv3d networks based on 3d sparse convolutions. They perform very well on many kinds of datasets

I am a newbie in this field. Could you tell me more details about what command should be used for 3d sparse convolution?

Many thanks.

**Comment by CCInc** [comment]
Take a look at my PR, I added some changes. Try copying the file directly from the PR so they're current. To use sparseconv3d you can try the following:

`    python train.py task=segmentation model_type=sparseconv3d model_name=ResUNet32 dataset=semanticKitti-sparse training=minkowski_scannet visualization.activate=True`

You'll need a sparse backend, you can find details on the readme

**Comment by cvhabitat** [comment]
> Take a look at my PR, I added some changes. Try copying the file directly from the PR so they're current. To use sparseconv3d you can try the following:
> 
> ` python train.py task=segmentation model_type=sparseconv3d model_name=ResUNet32 dataset=semanticKitti-sparse training=minkowski_scannet visualization.activate=True`
> 
> You'll need a sparse backend, you can find details on the readme

I deleted the processed file and ran the command with the updated file, but the error was the same as presented at the beginning.

Any suggestions, please?

**Comment by cvhabitat** [comment]
> Take a look at my PR, I added some changes. Try copying the file directly from the PR so they're current. To use sparseconv3d you can try the following:
> 
> ` python train.py task=segmentation model_type=sparseconv3d model_name=ResUNet32 dataset=semanticKitti-sparse training=minkowski_scannet visualization.activate=True`
> 
> You'll need a sparse backend, you can find details on the readme

Hi Christopher, 

I also tried to use the sparseconv3d backend. 

When I typed the command: `python train.py task=segmentation model_type=sparseconv3d model_name=ResUNet32 dataset=semanticKitti-sparse training=minkowski_scannet visualization.activate=True`

I got the following messages: 

> /home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/MinkowskiEngine/__init__.py:42: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
>   "It is recommended to set it below 24.",
> Traceback (most recent call last):
>   File "train.py", line 21, in <module>
>     main()
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
>     strict=strict,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
>     overrides=args.overrides,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 79, in run
>     config_file=config_file, overrides=overrides, with_log_configuration=True
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 343, in compose_config
>     config_file=config_file, overrides=overrides, strict=strict
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/config_loader.py", line 75, in load_configuration
>     cfg = self._merge_defaults(hydra_cfg, defaults, split_at)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/config_loader.py", line 427, in _merge_defaults
>     cfg = merge_defaults(cfg, user_list)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/config_loader.py", line 406, in merge_defaults
>     required=not is_optional,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/config_loader.py", line 333, in _merge_config
>     raise MissingConfigException(msg, new_cfg, options)
> hydra.errors.MissingConfigException: Could not load data/segmentation/semanticKitti-sparse.yaml

If I delete the sparse in "dataset = semanticKitti-sparse", the error becomes:

> python train.py task=segmentation model_type=sparseconv3d model_name=ResUNet32 dataset=semanticKitti training=minkowski_scannet 
> /home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/MinkowskiEngine/__init__.py:42: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
>   "It is recommended to set it below 24.",
> DEVICE : cuda
> Traceback (most recent call last):
>   File "train.py", line 21, in <module>
>     main()
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
>     strict=strict,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
>     overrides=args.overrides,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
>     job_subdir_key=None,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
>     ret.return_value = task_function(task_cfg)
>   File "train.py", line 12, in main
>     trainer = Trainer(cfg)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/trainer.py", line 44, in __init__
>     self._initialize_trainer()
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/trainer.py", line 71, in _initialize_trainer
>     Wandb.launch(self._cfg, self._cfg.wandb.public and self.wandb_log)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/utils/wandb_utils.py", line 85, in launch
>     "commit": commit_sha,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 93, in __getitem__
>     return self.__getattr__(key)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 85, in __getattr__
>     return self.get(key=key, default_value=None)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 99, in get
>     default_value=default_value,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 153, in _resolve_with_default
>     return self._resolve_single(value) if isinstance(value, str) else value
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 487, in _resolve_single
>     return Config._resolve_value(root, match.group(1), match.group(2))
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/omegaconf/config.py", line 463, in _resolve_value
>     "{} interpolation key '{}' not found".format(inter_type, inter_key)
> KeyError: "str interpolation key 'data.grid_size' not found"

Thanks

**Comment by cvhabitat** [comment]
Hi Christopher,

After changing "first_upsampling" to the original "grid_size", it now starts training with the sparseconv3d backend.

Really appreciate your help.

**Comment by cvhabitat** [comment]
Hi Christopher,

Sorry about reopening this issue.

I found that the program will be interrupted during the training process and throw out the following message:

> Available stage selection datasets:  ['test', 'val'] 
> The models will be selected using the metrics on following dataset:  val 
> EPOCH 1 / 300
>   8%| | 270/3189 [32:27<3:48:35,  4.70s/it, data_loading=0.001, iteration=1.143, train_acc=59.79, trwandb: Network error resolved after 0:00:14.256243, resuming normal operation.
>  33%|▎| 1064/3189 [2:02:30<2:50:28,  4.81s/it, data_loading=0.001, iteration=0.996, train_acc=73.67,wandb: Network error resolved after 0:00:35.004919, resuming normal operation.
>  34%|▎| 1069/3189 [2:03:07<4:22:23,  7.43s/it, data_loading=14.42, iteration=1.091, train_acc=73.67,wandb: Network error resolved after 0:00:15.651443, resuming normal operation.
>  34%|▎| 1097/3189 [2:05:57<2:39:37,  4.58s/it, data_loading=0.003, iteration=1.091, train_acc=73.90,wandb: Network error resolved after 0:00:20.852209, resuming normal operation.
>  35%|▎| 1101/3189 [2:06:30<3:10:56,  5.49s/it, data_loading=0.001, iteration=4.534, train_acc=73.96,wandb: Network error resolved after 0:00:34.533087, resuming normal operation.
>  53%|▌| 1696/3189 [3:14:22<2:51:06,  6.88s/it, data_loading=0.001, iteration=1.161, train_acc=76.98,
> Traceback (most recent call last):
>   File "train.py", line 21, in <module>
>     main()
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
>     strict=strict,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
>     overrides=args.overrides,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
>     job_subdir_key=None,
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
>     ret.return_value = task_function(task_cfg)
>   File "train.py", line 13, in main
>     trainer.train()
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/trainer.py", line 140, in train
>     self._train_epoch(epoch)
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/trainer.py", line 190, in _train_epoch
>     for i, data in enumerate(tq_train_loader):
>   File "/home/cv/anaconda3/env
> wandb: Waiting for W&B process to finish, PID 20417
> s/p3d/lib/python3.7/site-packages/tqdm/std.py", line 1170, in __iter__
>     for obj in iterable:
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
>     data = self._next_data()
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
>     return self._process_data(data)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
>     data.reraise()
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
>     raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 187, in __getitem__
>     data = self.get(self.indices()[idx])
>   File "/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/NEOLab/torch-points3d/torch_points3d/datasets/segmentation/semantickitti.py", line 128, in get
>     data = torch.load(self._scans[idx])
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
>     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch/serialization.py", line 853, in _load
>     result = unpickler.load()
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch/serialization.py", line 845, in persistent_load
>     load_tensor(data_type, size, key, _maybe_decode_ascii(location))
>   File "/home/cv/anaconda3/envs/p3d/lib/python3.7/site-packages/torch/serialization.py", line 833, in load_tensor
>     storage = zip_file.get_storage_from_record(name, size, dtype).storage()
> RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading file data/94687158907952: invalid header or archive is corrupted

The command I used is: `python train.py task=segmentation model_type=sparseconv3d model_name=ResUNet32 dataset=semanticKitti training=minkowski_scannet visualization.activate=True`

Any idea on this please?

**Comment by CCInc** [comment]
It looks like one of your files is corrupt. Try removing them all and redownloading then reprocessing, hopefully it will resolve it.

**Comment by cvhabitat** [comment]
Thanks a lot, Christopher. I will try all the process again. By the way, could you make KPConv compatible with semanticKitti, please?

Best wishes

**Comment by nicolas-chaulet** [comment]
I think that's been merged with #584 , could you let us know if that works and close the issue?

**Comment by cvhabitat** [comment]
Hi Nicolas, Thanks for your information. I'll go check it to #584 and close the issue for now.
