### ISSUE TITLE
Forward not possible without labels on pretrained PointNet2

### ISSUE THREAD

**Issue by FiratSusan** [nicolas-chaulet/torch-points3d#585]
Greetings,

I am trying out Torch-Points3D and wanted run some point clouds through pretrained models.
```python
import torch
from torch_geometric.data import Batch, Data
from torch_points3d.applications.pretrained_api import PretainedRegistry

# Setup
model = PretainedRegistry().from_pretrained('pointnet2_largemsg-s3dis-6')
device = torch.device("cpu")

# Random point cloud
num_points = 1024
pos = torch.randn((num_points, 3)).unsqueeze(0)
rgb = torch.randn((num_points, 3)).unsqueeze(0)
features = torch.cat((rgb, pos[:,:,2].unsqueeze(2)), axis=-1)

data = Data(pos=pos, x=features)
data = Batch.from_data_list([data])

model.set_input(data, device)
model.forward()
```

_Regarding the feature tensor, I came up with this by looking at the inference transform and reading through the transformations code. As far as I understood it should be the rgb channel + z-axis (but not sure if this is correct...)_

Running the given code I get an exception regarding the label tensor being a NoneType (which should be fine, since I want to make a prediction).

Looking at the [code](https://github.com/nicolas-chaulet/torch-points3d/blob/014238e53a5895531a08b1519e43adebf80d188c/torch_points3d/models/segmentation/pointnet2.py#L113) the exception is caused by a reshape with the labels tensor.
I am a bit confused here, shouldnt it be possible to run a predict without giving a label tensor?

Error:

TypeError                                 Traceback (most recent call last)
<ipython-input-1-6da83fdf00c5> in <module>
     18 
     19 model.set_input(data, device)
---> 20 model.forward()

~/.local/lib/python3.8/site-packages/torch_points3d/models/segmentation/pointnet2.py in forward(self, *args, **kwargs)
    110 
    111         self.data_visual = self.input
--> 112         self.data_visual.y = torch.reshape(self.labels, data.pos.shape[0:2])
    113         self.data_visual.pred = torch.max(self.output, -1)[1].reshape(data.pos.shape[0:2])
    114         return self.output

TypeError: reshape(): argument 'input' (position 1) must be Tensor, not NoneType

**Comment by CCInc** [comment]
@FiratSusan you're correct, it looks like a coding mistake. Probably my error. At any rate, can you try replacing the forward method like follows and see if it works? If so I can make a PR to fix it in the future.

```
    def forward(self, *args, **kwargs):
        r"""
            Forward pass of the network
            self.input:
                x -- Features [B, C, N]
                pos -- Points [B, N, 3]
        """
        data = self.model(self.input)
        last_feature = data.x
        if self._use_category:
            cat_one_hot = F.one_hot(self.category, self._num_categories).float().transpose(1, 2)
            last_feature = torch.cat((last_feature, cat_one_hot), dim=1)

        self.output = self.FC_layer(last_feature).transpose(1, 2).contiguous().view((-1, self._num_classes))

        self.data_visual = self.input
        self.data_visual.pred = torch.max(self.output, -1)[1].reshape(data.pos.shape[0:2])

        if self._weight_classes is not None:
            self._weight_classes = self._weight_classes.to(self.output.device)
        if self.labels is not None:
            self.loss_seg = F.cross_entropy(
                self.output, self.labels, weight=self._weight_classes, ignore_index=IGNORE_LABEL
            )
            self.data_visual.y = torch.reshape(self.labels, data.pos.shape[0:2])

        return self.output
```

**Comment by FiratSusan** [comment]
I commented them out (https://github.com/FiratSusan/torch-points3d/commit/c8b9f1b34a37edd1b6a56a4309b0dc25bf29eb86)

Works fine now, thanks :)
