### ISSUE TITLE
Dataset object has no attribute 'predict_original_samples'

### ISSUE THREAD

**Issue by gabrieleangeletti** [nicolas-chaulet/torch-points3d#593]
I'm trying to run a pre-trained `pointnet2` model on my own unlabeled dataset. I create a custom torch-geometric dataset:

    class MyTorchGeometricDataset(torch_geometric.data.InMemoryDataset):
        def __init__(
            self,
            root: str,
            transform: Callable = None,
            pre_transform: Callable = None,
            pre_filter: Callable = None,
        ) -> None:
            super(MyTorchGeometricDataset, self).__init__(root, transform, pre_transform, pre_filter)
            self.data, self.slices = torch.load(self.processed_paths[0])  # type: ignore
    
        @property
        def raw_file_names(self) -> List[str]:
            return [str(p) for p in Path(self.root).iterdir() if p.name.endswith(".e57")]
    
        @property
        def processed_file_names(self) -> List[str]:
            return ["data.pt"]
    
        def process(self) -> None:
            data_list = []
            for path in self.raw_file_names:
                xyz, rgb = ... load data ...
                xyz = np.ascontiguousarray(xyz, dtype=np.float32)
                rgb = np.ascontiguousarray(rgb, dtype=np.float32)
    
                data = torch_geometric.data.Data(
                    pos=torch.from_numpy(xyz),
                    rgb=torch.from_numpy(rgb),
                )
                data_list.append(data)
    
            if self.pre_filter is not None:
                data_list = [data for data in data_list if self.pre_filter(data)]
    
            if self.pre_transform is not None:
                data_list = [self.pre_transform(data) for data in data_list]
    
            data, slices = self.collate(data_list)
            torch.save((data, slices), self.processed_paths[0])

I use this dataset to initialize a torch-points3d custom dataset:

    class MyTorchPoints3DDataset(BaseDataset):
        def __init__(self, dataset_opt: Dict) -> None:
            super().__init__(dataset_opt)
    
            self.test_dataset = MyTorchGeometricDataset(
                root=self._data_path,
                pre_transform=self.pre_transform,
                transform=self.test_transform,
                pre_filter=self.pre_filter,
            )
    
        def get_tracker(self, wandb_log: bool, tensorboard_log: bool) -> SegmentationTracker:
            return SegmentationTracker(self, wandb_log=wandb_log, use_tensorboard=tensorboard_log)

I then take the model from the pre-trained registry:

    model = PretainedRegistry.from_pretrained("pointnet2_largemsg-s3dis-1")
    model = model.float()
    model = model.eval()
    model = model.to(device)

And then run an inference script based on the one in `torch-points3d/forward_scripts/forward.py`. My initial config for the test transform was as follows:

    test_transform:
    - transform: FixedPoints
      params:
        num: 20000
        replace: True
    - transform: AddFeatsByKeys
      params:
        list_add_to_x: [True]
        feat_names: [rgb]
        delete_feats: [True]
    - transform: Center
    - transform: ScalePos
      params:
        scale: 0.5

But I got the following error: `RuntimeError: Given groups=1, weight of size [16, 7, 1, 1], expected input[1, 6, 1024, 16] to have 7 channels, but got 6 channels instead`. After expecting the model's inner transform, I saw that I needed to add `pos_z` as an additional feature. So I changed the test transform to:

    test_transform:
      - transform: FixedPoints
        params:
          num: 20000
          replace: True
      - transform: XYZFeature
        params:
          add_x: False
          add_y: False
          add_z: True
      - transform: AddFeatsByKeys
        params:
          list_add_to_x: [True, True]
          feat_names: [rgb, pos_z]
          delete_feats: [True, True]
      - transform: Center
      - transform: ScalePos
        params:
          scale: 0.5

Now I'm able to generate predictions but I'm getting the following error: `AttributeError: 'MyTorchPoints3DDataset' object has no attribute 'predict_original_samples'`. I copied the code in `forward.py` which calls:

    predicted = {
                    **predicted,
                    **dataset.predict_original_samples(data, model.conv_type, model.get_output()),
                }

This method is defined for the Shapenet dataset and the docstring says: `Takes the output generated by the NN and upsamples it to the original data`. Why is it implemente only for Shapenet? And can I safely remove the call to this method?

**Comment by nicolas-chaulet** [comment]
I hope you found the solution! The missing method is here to upsample predictions assuming that your input point clouds would be downsized by the FixedPoints transform.

**Comment by gabrieleangeletti** [comment]
Thank you @nicolas-chaulet! Yes I figured that I don't need that method because I don't use the FixedPoints transform.

**Comment by lookquad** [comment]
Hi, i am having a similar kind of issue
I just followed the instructions on GitHub to for :
 [Getting started: Train pointnet++ on part segmentation task for dataset shapenet](https://github.com/nicolas-chaulet/torch-points3d#getting-started-train-pointnet-on-part-segmentation-task-for-dataset-shapenet)

Training went all well but when i run 
`python forward_scripts/forward.py`
It gives the following error

`Traceback (most recent call last):
  File "forward_scripts/forward.py", line 112, in main
    run(model, dataset, device, cfg.output_path)
  File "forward_scripts/forward.py", line 51, in run
    predicted = {**predicted, **dataset.predict_original_samples(data, model.conv_type, model.get_output())}
AttributeError: 'ShapeNetDataset' object has no attribute 'predict_original_samples'`

Please have a look at this.
