### ISSUE TITLE
CPU-only installation

### ISSUE THREAD

**Issue by Stakhan** [nicolas-chaulet/torch-points3d#600]
Hi !

In the process of installing the library for CPU only, I stumbled upon some troubles with the  `torch-points-kernels` dependency. Version 0.7.0 is required to have CPU-only support, but dependencies registered in pip wouldn't allow it to be used (`torch-points-kernels (>=0.6.6,<0.7.0)`). I managed to do a complete installation by removing this constraint (through a modified requirements.txt list) in the hope that it will not break somewhere else. Could you confirm ?

Thanks for your feedback.

**Comment by nicolas-chaulet** [comment]
Yes that would work. We need to update the pyproject.toml and the requirements.txt

**Comment by Stakhan** [comment]
Great !

**Comment by nicolas-chaulet** [comment]
I just merged a PR in tp3d that does that! It should be good if you use the latest in master

**Comment by Stakhan** [comment]
Good timing: I just need to reinstall on another machine this afternoon :)
Thank you !
