### ISSUE TITLE
Is it available to git clone + pip install torch-points3d

### ISSUE THREAD

**Issue by amiltonwong** [nicolas-chaulet/torch-points3d#603]
Hi, all,

I'd like to git clone torch-points3d locally with the newest status, and then pip install it, e.g.
```
git clone https://github.com/nicolas-chaulet/torch-points3d
pip install ./torch-points3d
```

But the commands above don't work. Could someone suggest how to achieve it?

Thanks~

**Comment by nicolas-chaulet** [comment]
Could you post more details?

**Comment by amiltonwong** [comment]
Hi, @nicolas-chaulet ,

One question I'm concerning is to modify the code inside torch-points3d package. Therefore, I choose to clone it locally and pip install it (not using PyPI):

`git clone https://github.com/nicolas-chaulet/torch-points3d` , then try to manually install it by

`pip install -e ./torch-points3d`

It returns the error as the following:
`ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /data/code13/torch-points3d/torch_points3d`

Is that possible to install torch-points3d package manually.

Thanks~

**Comment by amiltonwong** [comment]
@nicolas-chaulet , thanks a lot. It works :)
