### ISSUE TITLE
How to do forward pass on shapenet-fixed data?

### ISSUE THREAD

**Issue by harry1576** [nicolas-chaulet/torch-points3d#612]
Hi there,

I recently trained a model using the command:

`python train.py task=segmentation models=segmentation/pointnet2 model_name=pointnet2_charlesssg data=segmentation/shapenet-fixed
`
Now I am attempting to do a forward pass, and I am struggling to get it working.
I have edited the forward_scripts/conf file to be: 

num_workers: 2
batch_size: 16
cuda: 0
weight_name: "miou" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "/local/torch-points3d/outputs/2021-05-27/09-40-02" # "{your_path}/outputs/2020-01-28/11-04-13" for example
model_name: pointnet2_charlesssg
enable_dropout: False
output_path: "/local/torch-points3d/forward_scripts/out" # Where the output goes
input_path: "/local/torch-points3d/forward_scripts/test_data"
defaults:
    - dataset: "shapenet"
      optional: True`

but when I do the command:
` python forward_scripts/forward.py
`

I get this error:

[2021-05-27 11:15:15,810][__main__][INFO] - DEVICE : cpu
[2021-05-27 11:15:15,810][torch_points3d.metrics.model_checkpoint][INFO] - Loading checkpoint from /local/torch-points3d/outputs/2021-05-27/09-40-02/pointnet2_charlesssg.pt
Traceback (most recent call last):
  File "forward_scripts/forward.py", line 78, in main
    checkpoint.data_config.update(key, value)
TypeError: update() takes from 1 to 2 positional arguments but 3 were given

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Any help would be greatly appreciated, 
Cheers,
Harry

**Comment by harry1576** [comment]
I have update the config (forward_scripts/conf)  to be as follow: 

![update](https://user-images.githubusercontent.com/27661260/119744630-82b84c00-bee0-11eb-98e5-f780d827e21d.png)

and now get the following error:

![error](https://user-images.githubusercontent.com/27661260/119744678-9bc0fd00-bee0-11eb-9649-14ad4bfb85e3.png)

**Comment by juanmed** [comment]
@harry1576 Hi! I am facing the same problem, where you able to solve it? If yes, what did you do? Thanks!

**Comment by juanmed** [comment]
What I see so far is that indeed ```dataset``` has no attribute `feature_dimension` but rather a *key* `feature_dimension`, since it is a dictionary. In fact, it has 3 keys `'feature_dimension', 'num_classes', 'class_to_segments'`. However, changing the code to access the keys does not work since in a posterior section the code requires keys that are non-existent in the dataset dictionary...

**Comment by zack2020-star** [comment]
Hi! I am facing the same problem, where you able to solve it? If yes, what did you do? Thanks!

**Comment by zack2020-star** [comment]
Hi! I am facing the same problem, where you able to solve it? If yes, what did you do? Thanks!

**Comment by harry1576** [comment]
> What I see so far is that indeed `dataset` has no attribute `feature_dimension` but rather a _key_ `feature_dimension`, since it is a dictionary. In fact, it has 3 keys `'feature_dimension', 'num_classes', 'class_to_segments'`. However, changing the code to access the keys does not work since in a posterior section the code requires keys that are non-existent in the dataset dictionary...

I found the same... Not sure how to fix it.

**Comment by juanmed** [comment]
Hi, the fix to this issue is in #636.
