### ISSUE TITLE
Data format and positional arguments on custom dataset

### ISSUE THREAD

**Issue by LucaRom** [nicolas-chaulet/torch-points3d#629]
Hi everyone, 

I have been strugling to integrate a custom dataset to run in the different models. I think part of my problem is how I build the dataset in pytorch.

Information about what I want to do : 

My goal is to predict the class (segmentation) of my dataset (DALES) through different models, but especially KPConv. 
The dataset is in LAS. I tried to follow other dataset.py format, especially semantickitty but still can't create a working dataset. 

Any help or pointers would mean a lot, especially feedback on how the data is created (Data(pos and x)) and data.y (labels).

Here is my current error :

```
Traceback (most recent call last):
  File "/torch-points3d/torch_points3d/datasets/segmentation/dales.py", line 266, in <module>
    DalesDataset(Dales(dataroot))
  File "/torch-points3d/torch_points3d/datasets/segmentation/dales.py", line 210, in __init__
    super().__init__(dataset_opt)
  File "/torch-points3d/torch_points3d/datasets/base_dataset.py", line 65, in __init__
    dataset_name = dataset_opt.get("dataset_name", None)
TypeError: get() takes 2 positional arguments but 3 were given
```

Here is my code : 

```
import os
from glob import glob
import numpy as np
import multiprocessing
import logging
import torch
import laspy

from torch_geometric.data import InMemoryDataset, Dataset, Data

from torch_points3d.datasets.base_dataset import BaseDataset
from torch_points3d.metrics.segmentation_tracker import SegmentationTracker

log = logging.getLogger(__name__)

###################################Memory dataset ###################################

class Dales(InMemoryDataset):
    """
    Class to handle DALES dataset for segmentation task.
    """

    def __init__(self, root, transform=None, pre_transform=None, pre_filter=None):
        super().__init__(root, transform=transform, pre_transform=pre_transform, pre_filter=pre_filter)

        self.data, self.slices = torch.load(self.processed_paths[0])

    @property
    def raw_file_names(self):
        return las_list

    @property
    def processed_file_names(self):
        return ['data.pt']

    def download(self):
        pass

    def process(self):
        data_list = []

        for i in las_num:
            las_file = laspy.read(os.path.join(dataroot, "raw", "{}.las".format(i)))
            print(las_file)
            las_xyz = np.vstack((las_file['X'], las_file['Y'], las_file['Z'])).astype(np.float32).T 
            las_label = np.reshape(las_file.classification, (len(las_file), 1))
            print(las_xyz)
            data = Data(pos=las_xyz)
            data.y = las_label.T

            log.info("Processed file %s, nb points = %i", i, data.pos.shape[0])

            data_list.append(data)

        data, slices = self.collate(data_list)
        torch.save((data, slices), self.processed_paths[0])

################################### Wrapper ###################################

class DalesDataset(BaseDataset):
    """ Wrapper around Dales that creates train and test datasets.
    Parameters
    ----------
    dataset_opt: omegaconf.DictConfig
        Config dictionary that should contain
            - root,
            - transform,
            - pre_transform
            - process_workers
    """

    def __init__(self, dataset_opt):
        super().__init__(dataset_opt)
        self.train_dataset = Dales(
            self._data_path,
            transform=self.train_transform,
            pre_transform=self.pre_transform
        )
        #
        # self.val_dataset = SemanticKitti(
        #     self._data_path,
        #     split="val",
        #     transform=self.val_transform,
        #     pre_transform=self.pre_transform,
        #     process_workers=process_workers,
        # )
        #
        # self.test_dataset = SemanticKitti(
        #     self._data_path,
        #     split="test",
        #     transform=self.test_transform,
        #     pre_transform=self.pre_transform,
        #     process_workers=process_workers,
        # )

    def get_tracker(self, wandb_log: bool, tensorboard_log: bool):
        """Factory method for the tracker
        Arguments:
            wandb_log - Log using weight and biases
            tensorboard_log - Log using tensorboard
        Returns:
            [BaseTracker] -- tracker
        """
        return SegmentationTracker(self, wandb_log=wandb_log, use_tensorboard=tensorboard_log)


if __name__ == "__main__":
    DIR = os.path.dirname(os.path.realpath(__file__))
    dataroot = os.path.join(DIR, "..", "..", "..", "data", "dales")

    las_list = [f for f in os.listdir(os.path.join(dataroot, "raw")) if f.endswith('.las')] 
    las_num = [os.path.splitext(x)[0] for x in las_list] 

    #Dales(dataroot)
    
    DalesDataset(Dales(dataroot))

```

**Comment by CCInc** [comment]
> Any help or pointers would mean a lot, especially feedback on how the data is created (Data(pos and x)) and data.y (labels).

I can give you a basic implementation of las->Data:

```
las = laspy.file.File(file, mode='r')
points = np.stack([las.x, las.y, las.z], axis=1)

classification = las.classification.astype(np.int)
y = torch.from_numpy(classification)
y = self._remap_labels(y)
data = Data(pos=torch.from_numpy(points).type(torch.float), y=y)
```

You can find a sample of self._remap_labels in torch_points3d\datasets\segmentation\scannet.py. Unnecessary if your classifications are consecutive starting from 0.

You're getting that error because you're not using an OmegaConf config file. You need an omegaconf object for `cfg` for the dataset code to work properly. https://omegaconf.readthedocs.io/en/2.1_branch/usage.html#from-a-dictionary

**Comment by LucaRom** [comment]
Hi @CCInc 

Thank you for the reply, it is useful.

I did realized I had to run the config file, but still had a dimension problem with my data that your code fixed. Though, I think I'm using a newer version of laspy which was released a few days ago, and therefore the code is slightly different to handle the SubFieldView class (which is used for classification). 

`las_label = np.array(las_file.classification).astype(np.int)`

I am now able to slowly get through the debugging for implementing the dataset into KPConv segmentation. Slowly getting there :) 

If you see other obvious things I am missing for using KPConv segmentation on a custom dataset do not hesitate as it helps a lot. Otherwise I will be posting the updated code and config filed that worked for me to share with others who might try to do the same.

Thanks again!

**Comment by CCInc** [comment]
Yep I haven't upgraded my laspy yet, glad you figured it out! Your code looks fine to me as far as datasets go. I'm not very familiar with kpconv so I can't say but it should work fine as long as your config file is correct.

**Comment by nicolas-chaulet** [comment]
@LucaRom For KPconv make sure you use the AddOnes transform (which means adding it to the train val and test transform like here: https://github.com/nicolas-chaulet/torch-points3d/blob/5378a2ae7ef612433acedaa497073971ec66ff09/conf/data/segmentation/s3disfused-addones.yaml#L37-L42)

**Comment by LucaRom** [comment]
Hello again, quick update... (I use number from last post to update corresponding topics)

1) I got a slightly better understanding of the sampling strategies and what I was looking for is definitely the Grid sampling instead of the random sphere one. My understanding is that the GridSampling is like a stratified sampling and has better potential to represent my data. This seems especially true for testing data, where you want to make sure to predict as much points as possible. Also, I found that the `GridSphereSampling` function would compute faster for my data. Note that I did not use it in the config file but coded it directly in the dataset function as it was easier to follow what and when were the outputs. So basically, I removed the `RandomSphere` from the config file :

```
# @package data
task: segmentation
class: dales.DalesDataset
dataset_name: "dales"
dataroot: data
#first_subsampling: 0.02
first_subsampling : 10 
use_category: False

train_transform:
  - transform: AddOnes
  - transform: AddFeatByKey
    params:
      add_to_x: True
      feat_name: 'ones'
  - transform: XYZFeature

test_transform:
  - transform: AddOnes
  - transform: AddFeatByKey
    params:
      add_to_x: True
      feat_name: 'ones'
  - transform: XYZFeature
```

And coded the `GridSphereSampling` inside the dataset as such :

```
        if self._split == "train":
            data_list = []
            for i in train_num:
                las_file = laspy.read(os.path.join(dataroot, "train", "{}.las".format(i)))
                las_xyz = np.stack([las_file.x, las_file.y, las_file.z], axis=1)
                las_label = np.array(las_file.classification).astype(np.int)
                y = torch.from_numpy(las_label)
                data = Data(pos=torch.from_numpy(las_xyz).type(torch.float), y=y)

                sampler = GridSphereSampling(radius=15, grid_size=15, delattr_kd_tree=True, center=True)
                data_samples = sampler(data.clone()) # create a whole list of samples

                for sample in data_samples:
                    data_list.append(sample)

                log.info("Processed file %s, nb points = %i, nb samples = %i", i, data.pos.shape[0], len(data_samples))

            data, slices = self.collate(data_list)
            torch.save((data, slices), self.processed_paths[0])
```

2) Notes on memory usage :  A) From my tests, it feels like the `first_subsampling` size from the dataset config file has a direct impact on the memory usage. This parameter seems to be fetched from the kpconv model which affects the radius sampling and/or the grid size of the model. B) The `GridSphereSampling` uses CPU only but is not that long for my dataset. The good thing is **now that the kpconv training uses between 96 to 100% of the GPU** which answers another part of my concerns from last post.

So now I have 1 question left for the moment : Does using `GridSphereSampling` as a `pre_transform` in the dataset config file act the same way as my code implementation?

Bonus question on data format understanding (:P) : Since kpconv is implemented with `partial_dense` data format, is there some kind of validation/transformation that is made on the data before being fed to the model or it should be handled beforehand (to make sure the data is in the right format)?

I'm sorry to keep using this issue to update my progress, but I hope it can be useful to another beginner going through similar steps... 

Any inputs/answer are always more than welcome as they most likely will 'propel' my understanding! I feel I am almost there!

Thank you again!

**Comment by LucaRom** [comment]
Thanks for all the help, I think this form for `DALES` dataset and `.las` file is ok so I will close it!

As for my last question about `GridSphereSampling` as a `pre_transform` I found my answer through #638 where the author of the issue experiment with it.
