### ISSUE TITLE
Training on Large Point Clouds ~ 2.5 Million Points (PointNet++)

### ISSUE THREAD

**Issue by harry1576** [nicolas-chaulet/torch-points3d#638]
Hi there,

I am trying to train PointNet++ on large points clouds. However I run out of memory.
How can I work around this (without sub-sampling) - is there a way to feed in parts of point cloud as batches?

Kind regards,
Harry

**Comment by harry1576** [comment]
Or how can you feed the data in as fixed size blocks?

**Comment by tiger-bug** [comment]
I don't know if this would help, but you can use numpy to block your point data.  

```python
# We are going to block it along x and y axis.  
import numpy as np
pnts # Some array of size [num_points, 3] 
block_size = some_block_size
blocks = ((pnts[:,:2] - np.min(pnts[:,:2], axis = 0) // block_size).astype(np.int32)
# These are the block ids for points in 2 dimensions
# get unique blocks with counts.  You may want to combine blocks with small numbers of points or just disregard them
block_ids, pnt_counts = np.unique(blocks, return_counts = True, axis = 0)

###### Store point data into a dictionary
block_dic = {}
for id_ in block_ids:
# loop through block_ids and get indices for each block
   idx = np.all(blocks == id_, axis = 1)
# Get points within the block and store it in the block_dic dictionary
   block_dic[tuple(id_)] = pnts[idx]
```

Also, you can subsample the point cloud using voxel grids instead of random sampling, which may remove points you would rather keep.  Good APIs for this can be found in [open3d](http://www.open3d.org/) or using [PDAL](https://pdal.io/)

**Comment by CCInc** [comment]
The way to do this within torch-points is using GridSphereSampling or RandomSphere (https://torch-points3d.readthedocs.io/en/latest/src/api/transforms.html) however, the sampled spheres are still variable size. Outside of torch points, if you want contiguous fixed size blocks, I suggest preprocessing with https://pdal.io/stages/filters.chipper.html

**Comment by harry1576** [comment]
Thanks alot guys! I will give it a go 👌

**Comment by harry1576** [comment]
Hi thanks for the help.
I have setup the data yaml file as follows: 
`# @package data
task: segmentation
class: vine.VineDataset
dataroot: data
normal: False
use_category: True
feature_dimension: 0
first_subsampling: 0.001

pre_transforms:
  - transform: GridSphereSampling
    params:
      radius: 0.015
      grid_size: 0.015
`

However now I am getting an Error:
'
[2021-07-12 17:37:56,883][torch_points3d.trainer][INFO] - DEVICE : cuda
Processing...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [02:26<00:00, 48.80s/it]
Traceback (most recent call last):
  File "train.py", line 13, in main
    trainer = Trainer(cfg)
  File "/local/vine-seg/torch-points3d/torch_points3d/trainer.py", line 44, in __init__
    self._initialize_trainer()
  File "/local/vine-seg/torch-points3d/torch_points3d/trainer.py", line 91, in _initialize_trainer
    self._dataset: BaseDataset = instantiate_dataset(self._cfg.data)
  File "/local/vine-seg/torch-points3d/torch_points3d/datasets/dataset_factory.py", line 46, in instantiate_dataset
    dataset = dataset_cls(dataset_config)
  File "/local/vine-seg/torch-points3d/torch_points3d/datasets/segmentation/vine.py", line 225, in __init__
    self.train_dataset = Vine(
  File "/local/vine-seg/torch-points3d/torch_points3d/datasets/segmentation/vine.py", line 44, in __init__
    super(Vine, self).__init__(
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    super(InMemoryDataset, self).__init__(root, transform, pre_transform,
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 92, in __init__
    self._process()
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 165, in _process
    self.process()
  File "/local/vine-seg/torch-points3d/torch_points3d/datasets/segmentation/vine.py", line 199, in process
    self._save_data_list(data_list, self.processed_paths[i])
  File "/local/vine-seg/torch-points3d/torch_points3d/datasets/segmentation/vine.py", line 168, in _save_data_list
    torch.save(self.collate(datas), path_to_datas)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 111, in collate
    keys = data_list[0].keys
AttributeError: 'list' object has no attribute 'keys'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
'
Any help would be greatly appreciated :)
Thanks

**Comment by LucaRom** [comment]
It seems that you are feeding a list where it is expecting a dictionary. From what I understand, you need to feed 2 arguments in torch.save as such : 

```
  data, slices = self.collate(data_list)
  torch.save((data, slices), self.processed_paths[0])
```

I am a beginner with this and had difficulties figuring out how the sampling interact with the processing of the dataset when it is called from the config file. As a work around, I coded the sampling directly in the processing part because it was easier for me to visualize and debug. Maybe it could work for you as well. Here is a simplified version of what I did, hope it can help!

```
sampler = GridSphereSampling(radius=15, grid_size=20, delattr_kd_tree=True, center=True)
data_samples = sampler(data.clone())
	
data, slices = self.collate(data_samples)
torch.save((data, slices), self.processed_paths[0])
```

**Comment by CCInc** [comment]
@harry1576 it looks like your error is coming from `self.collate(datas)`. Make sure that your `datas` var is a list of `Data` objects.

**Comment by harry1576** [comment]
Oh I see cheers, I noticed that I get the same error with the shapenet dataset too.

**Comment by harry1576** [comment]
Ah so I have done a bit of investigation and it seems that the pre_transforms is the root of the problem. It works fine when I do RandomSphere sampling, however GridSphereSampling seems to alter the data type:

'''
``````[2021-07-12 17:37:56,883][torch_points3d.trainer][INFO] - DEVICE : cuda
Processing...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [02:26<00:00, 48.80s/it]
Traceback (most recent call last):
  File "train.py", line 13, in main
    trainer = Trainer(cfg)
  File "/local/vine-seg/torch-points3d/torch_points3d/trainer.py", line 44, in __init__
    self._initialize_trainer()
  File "/local/vine-seg/torch-points3d/torch_points3d/trainer.py", line 91, in _initialize_trainer
    self._dataset: BaseDataset = instantiate_dataset(self._cfg.data)
  File "/local/vine-seg/torch-points3d/torch_points3d/datasets/dataset_factory.py", line 46, in instantiate_dataset
    dataset = dataset_cls(dataset_config)
  File "/local/vine-seg/torch-points3d/torch_points3d/datasets/segmentation/vine.py", line 225, in __init__
    self.train_dataset = Vine(
  File "/local/vine-seg/torch-points3d/torch_points3d/datasets/segmentation/vine.py", line 44, in __init__
    super(Vine, self).__init__(
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    super(InMemoryDataset, self).__init__(root, transform, pre_transform,
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 92, in __init__
    self._process()
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 165, in _process
    self.process()
  File "/local/vine-seg/torch-points3d/torch_points3d/datasets/segmentation/vine.py", line 199, in process
    self._save_data_list(data_list, self.processed_paths[i])
  File "/local/vine-seg/torch-points3d/torch_points3d/datasets/segmentation/vine.py", line 168, in _save_data_list
    torch.save(self.collate(datas), path_to_datas)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 111, in collate
    keys = data_list[0].keys
AttributeError: 'list' object has no attribute 'keys'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.``````
``````

def _process_filenames(self, filenames):
        data_raw_list = []
        data_list = []
        categories_ids = [self.category_ids[cat] for cat in self.categories]
        cat_idx = {categories_ids[i]: i for i in range(len(categories_ids))}

        has_pre_transform = self.pre_transform is not None

        id_scan = -1
        for name in tq(filenames):
            cat = name.split(osp.sep)[0]
            if cat not in categories_ids:
                continue
            id_scan += 1
            data = read_txt_array(osp.join(self.raw_dir, name))
            pos = data[:, :3]
            x = data[:, 3:6]
            y = data[:, -1].type(torch.long)
            category = torch.ones(x.shape[0], dtype=torch.long) * cat_idx[cat]
            id_scan_tensor = torch.from_numpy(np.asarray([id_scan])).clone()
            data = Data(pos=pos, x=x, y=y, category=category,
                        id_scan=id_scan_tensor)
            data = SaveOriginalPosId()(data)
            if self.pre_filter is not None and not self.pre_filter(data):
                continue
            data_raw_list.append(data.clone() if has_pre_transform else data)
            if has_pre_transform:
                print(type(data))
                data = self.pre_transform(data)
                print(type(data))
                data_list.append(data)
                quit()
```

**Comment by harry1576** [comment]
oh okay I see whats happening - the pre_transform returns a list of the split up data.

**Comment by harry1576** [comment]
Update: Managed to get the pre-transform working - here is the code snippet: 
```
def _process_filenames(self, filenames):
        data_raw_list = []
        data_list = []
        categories_ids = [self.category_ids[cat] for cat in self.categories]
        cat_idx = {categories_ids[i]: i for i in range(len(categories_ids))}

        has_pre_transform = self.pre_transform is not None

        id_scan = -1
        for name in tq(filenames):
            cat = name.split(osp.sep)[0]
            if cat not in categories_ids:
                continue
            id_scan += 1
            data = read_txt_array(osp.join(self.raw_dir, name))
            pos = data[:, :3]
            x = data[:, 3:6]
            y = data[:, -1].type(torch.long)
            category = torch.ones(x.shape[0], dtype=torch.long) * cat_idx[cat]
            id_scan_tensor = torch.from_numpy(np.asarray([id_scan])).clone()
            data = Data(pos=pos, x=x, y=y, category=category,
                        id_scan=id_scan_tensor)
            data = SaveOriginalPosId()(data)

            if self.pre_filter is not None and not self.pre_filter(data):
                continue
            data_raw_list.append(data.clone() if has_pre_transform else data)
            if has_pre_transform:
                #data_list = self.pre_transform(data)
                transformed_data = self.pre_transform(data)
                for tdata in transformed_data:
                    if(tdata.pos.shape[0] > 512): # data with less than 512 points is removed...
                        data_list.append(tdata)
                #data_list.extend(self.pre_transform(data))
                #data_list.append(data)
                             
        if not has_pre_transform:
            return [], data_raw_list
        return data_raw_list, data_list

```

Does anyone have a recommended (tidy) way of reassembling the spherical samples back into a full model?
Thanks for the help.

**Comment by nicolas-chaulet** [comment]
The way we've done it in the past was through tracker or in the inference scripts. s3dis tracker is a good example, we use the SaveOriginPoseId to map the predictions back to the original unsampled point cloud:

https://github.com/nicolas-chaulet/torch-points3d/blob/5378a2ae7ef612433acedaa497073971ec66ff09/torch_points3d/metrics/s3dis_tracker.py#L35-L57
