### ISSUE TITLE
Problem while loading older checkpoint after updating torch-points3d

### ISSUE THREAD

**Issue by IdeGelis** [nicolas-chaulet/torch-points3d#642]
Hello!
I recently updated my version of torch-points 3D, the previous version that I had was cloned from the git depository on last January.
Since January, I made several experiments that were working well and I kept all the checkpoint files. 
Now, I wanted to perform some evaluation of some previous experiments with the new version of tp3d, but I have the following error when loading the checkpoint: 

>   trainer = Trainer(cfg)
>   File "/share/castor/home/degelis/dev/torch-points3d/torch_points3d/trainer_Urb3DS.py", line 46, in __init__
>     self._initialize_trainer()
>   File "/share/castor/home/degelis/dev/torch-points3d/torch_points3d/trainer_Urb3DS.py", line 83, in _initialize_trainer
>     resume=resume,
>   File "/share/castor/home/degelis/dev/torch-points3d/torch_points3d/metrics/model_checkpoint.py", line 171, in __init__
>     self._checkpoint = Checkpoint.load(load_dir, check_name, run_config=rc, strict=strict, resume=resume)
>   File "/share/castor/home/degelis/dev/torch-points3d/torch_points3d/metrics/model_checkpoint.py", line 86, in load
>     objects = torch.load(checkpoint_file, map_location="cpu")
>   File "/share/home/degelis/.local/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
>     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>   File "/share/home/degelis/.local/lib/python3.7/site-packages/torch/serialization.py", line 853, in _load
>     result = unpickler.load()
> AttributeError: Can't get attribute 'UntypedNode' on <module 'omegaconf.nodes' from '/share/home/degelis/.local/lib/python3.7/site-packages/omegaconf/nodes.py'>

From what I read, I understood that it comes from the updated version of OmegaConf coming with hydra >1.0. Did you have the same problem? I conducted some quite long training, I don't really want to retrain everything in order to be able to load weights again... Have you got any idea?

Thank you,
Iris

**Comment by humanpose1** [comment]
You can use the following [script](https://github.com/nicolas-chaulet/torch-points3d/blob/master/scripts/omegaconf2dict.py). But you need the old version of OmegaConf to execute the script(because yo need to open the old checkpoints).

example:

```
 python scripts/omegaconf2dict.py -f path/of/your/checkpoint.pt --old path/where/you/want/to/store/the/old/checkpoint.pt-o path/of/your/new/checkpoint.pt
```

**Comment by IdeGelis** [comment]
Perfect! It seems to work. Thank you very much.
