### ISSUE TITLE
KPConv is slow on validation after first epoch

### ISSUE THREAD

**Issue by pvnieo** [nicolas-chaulet/torch-points3d#648]
Hi,

Thanks for the amazing library.

I'm using KPConv for segmentation. It works well for the first epoch train and validation, but starting from the second epoch, the train is working normally (less than 1 second per iteration), but the validation becomes really slow, up to 30 second per iteration (so what happens is that 1 or 2 iterations of the validation are fast, and then it got stuck in the next iteration, and this cycle repeats it self). It should be noted that the data used in validation is the same. Also I'm using the `MultiScaleTransform`.

Is this a known issue, how can I debug it?

Thank you in advance!

**Comment by nicolas-chaulet** [comment]
Hey! Glad to see you back 😄 
That's definitely not normal and not know as a bug. Is this happening on a custom dataset? Slowness on validation could come from the metrics that get computed in the tracker, I would start there to understand what's happening.

**Comment by pvnieo** [comment]
@Hey!
Glad to be back :smile:

Actually, this happens starting from the second epoch which is weird!
You suggested to to look for the metrics computed in the tracker, can you please tell me more! what is the tracker you are talking about?

**Comment by nicolas-chaulet** [comment]
If you are using our trainer, this is where validation happens:
https://github.com/nicolas-chaulet/torch-points3d/blob/5378a2ae7ef612433acedaa497073971ec66ff09/torch_points3d/trainer.py#L222-L265

And here we track the loss and any other metrics:
https://github.com/nicolas-chaulet/torch-points3d/blob/5378a2ae7ef612433acedaa497073971ec66ff09/torch_points3d/trainer.py#L251

This depends on the tracker that is automatically generated off the dataset
https://github.com/nicolas-chaulet/torch-points3d/blob/5378a2ae7ef612433acedaa497073971ec66ff09/torch_points3d/trainer.py#L124

**Comment by pvnieo** [comment]
Oh, I see
Actually, I'm just using the network `KPConv` found in `torch_points3d.applications.kpconv`.

Ok, so I should search somewhere else! 

maybe the fact that in the validation, some iterations are fast, and others are very slow, suggests that there is problem happening in the data loader, but it's happening only in the validation, and starting from the second epoch


The only transforms I'm using are:
```
test_transforms:
    - transform: AddOnes
    - transform: AddFeatsByKeys
      params:
        list_add_to_x: [True]
        feat_names: ["ones"]
        delete_feats: [True]
```
in addition to the `MultiScaleTransform`

**Comment by pvnieo** [comment]
Hi @nicolas-chaulet 

Yes, I can confirm that the transforms are taking too much time and they are slowing the iterations, but I have no idea why, also it appears that one iteration of `MultiScaleTransform` is fast!

This is some weird bug! I'll keep you updated!

**Comment by pvnieo** [comment]
Solved the issue,
It was because of a bug on my end, that makes the transforms be computed an exponential number of times as the evaluation progresses!

Thanks for the support!

**Comment by nicolas-chaulet** [comment]
Great!
