### ISSUE TITLE
Creating a custom object detection dataset - feature composition

### ISSUE THREAD

**Issue by Alphastrick** [nicolas-chaulet/torch-points3d#663]
I'm trying to implement a new dataset for object detection. As reference for the input tensor I've used your Scannet dataset implementation. Since not all features are well document, I am not sure what some of them are used for:

- heading_class_label -- why is it 0?
- heading_residual_label -- why is it 0?
- sem_cls_label -- why is it identical to size_class_label? 
- angle_residual_label -- why is it documented but not set?

Can someone explain these input features?

Currently, training with this dataset is impossible (no training progess), since these attributes are either set to zero or have any invalid value.

**Comment by dodgerblue11** [comment]
Hi, did you manage to figure this out? If so, would you be able to give me pointers? I tried scannet but I am getting a Forbidden link even with trying to load the scannet dataset. Thanks!

**Comment by Alphastrick** [comment]
Hi @dodgerblue11, sure! Have a look at the [repository](https://github.com/facebookresearch/votenet)of the original paper of VoteNet.

In order to download the dataset ScanNet you now need to register an request access. I can't help you with that but if you have any further question please ask me directly.
