### ISSUE TITLE
Issue extending library beyond examples

### ISSUE THREAD

**Issue by TrevorThomasBC21** [nicolas-chaulet/torch-points3d#683]
I'm having trouble extending torch-points3d beyond the example commands given.  I was able to successfully run the following from my terminal:

python train.py task=segmentation models=segmentation/pointnet2 model_name=pointnet2_charlesssg\  
     data=segmentation/shapenet-fixed

Now I am trying to run the same segmentation task using _any_ other model, but I'm getting an error regardless of which I use.  For example, I will change the terminal command to:

python train.py task=segmentation models=segmentation/kpconv model_name=KPConvPaper data=segmentation/shapenet-\ 
    fixed

And I get the following error:

    raise ConfigCompositionException(
    hydra.errors.ConfigCompositionException: models appears more than once in the final defaults list

I get this same error regardless of whether I run KPConv, sparseconv3d, RSConv, etc.  I'm almost certain the issue is in the "models" parameter, but I don't know where to find a list of acceptable command-line arguments for these files.  Thank you to anyone who can help.

Edit:

Interestingly, I tried again with PointNet and got it to work.  The command I used was:

python train.py task=segmentation models=segmentation/pointnet model_name=PointNet data=segmentation/shapenet-fixed

If anyone has ideas for the other models, I would still greatly appreciate them.

**Comment by CCInc** [comment]
I'm not sure what the issue could be, could you try running:

```
python train.py task=segmentation models=segmentation/sparseconv3d model_name=ResUNet32 training=minkowski_scannet data=segmentation/s3dis1x1-sparse training.wandb.log=False
```

and let me know if it works?

**Comment by nicolas-chaulet** [comment]
Ok, thanks, marking as resolved now
