### ISSUE TITLE
Save Original PosID after voxelization

### ISSUE THREAD

**Issue by jcorrochanoj** [nicolas-chaulet/torch-points3d#698]
Hi,

First of all, congratulations for the work done on the library, it is very useful.

I am working with my own dataset with very large point clouds and I want to apply voxelization. The problem is that I would like to somehow preserve the original indices of the points that each centroid represents after downsampling. 

I am using the SaveOriginalPosID transformation but it only saves one of the indices.

How can I do this?

**Comment by nicolas-chaulet** [comment]
Ha interesting! You could store that as a dictionary (mapping cellid -> [list of origin id])  and save that in a file somewhere next to your data tensors after pre processing?

**Comment by jcorrochanoj** [comment]
We have achieved what we were looking for by following this process:

This method allows to undo the voxelisation ir order to get the original point cloud fully labelled. The general procedure is as follows:

1. Load the original and the voxelised point cloud (labeled).

2. The transformations prior to voxelisation are applied to the original point cloud.

3.  The clustering of the original point cloud is obtained in the same way as in training. The clusters for all points of the original cloud are obtained. Then they are transformed to be consecutive clusters, we have as many data as initial (original) points. The voxelized point cloud has the origin id, generated by the SaveOriginalPosId, this indicates the position in which one of the points contributing to the centroid appears within the vector of clustered data. Using this last vector we are able to relate each cluster with each point of the voxelized point clloud (centroids). This last step may not be necessary because the voxelised point cloud has the points sorted by cluster.

4. Finally, we obtain a dictionary that has the transformation between cluster and class in which the cluster has been classified. Using this transformation and the clusters to which each point of the original cloud belongs, we are able to obtain the original fully labelled cloud.
